### ISSUE TITLE
Minor improvement to C++

### ISSUE THREAD

**Issue by igorlfs** [catppuccin/nvim#103]
Currently, class members and types are the same color, eg
![image](https://user-images.githubusercontent.com/84649544/152709357-32ce7b2e-5366-466d-aaf0-a45d24810c11.png)
It would be nice if members names' were some other color.

**Comment by Pocco81** [comment]
What about rosewater? It's used for `TSProperty` on Lua and Rust (if I remember well, that is).

**Comment by igorlfs** [comment]
What I find odd about using rosewater is that it is also used for namespaces. But if you want to use it for consistency with Lua/Rust, I guess that's fine too :)

**Comment by igorlfs** [comment]
I've been using mauve for a while and I think it's a solid alternative.
