### ISSUE TITLE
Support for hlargs.nvim

### ISSUE THREAD

**Issue by ofseed** [catppuccin/nvim#113]
[hlargs.nvim](https://github.com/m-demare/hlargs.nvim) is a plugin that highlights arguments' definitions and usages, asynchronously, using Treesitter. However, It is useless for catppuccin.nvim.
### catppuccin
![image](https://user-images.githubusercontent.com/61115159/160967746-58c9cc36-3310-4832-904d-437f07d92672.png)
### nightfox
![image](https://user-images.githubusercontent.com/61115159/160967901-d0322011-8f5a-4832-a9f8-55d67d85c284.png)
### tokyonight
![image](https://user-images.githubusercontent.com/61115159/160968228-ae2a6004-8acc-4e9b-b07f-0150b830bfab.png)
As you can see, hlargs.nvim works well with other colorschemes. It's strange why it doesn't work for catppuccin, I think in theory it shouldn't have any additional configuration requirements for colorshemes.

**Comment by epixinvites** [comment]
![20220410-104111](https://user-images.githubusercontent.com/54717060/162598877-521dfd81-ea1c-483e-8749-61b961a09227.png)
Are you sure it doesn't work? It works perfectly for me.

**Comment by ofseed** [comment]
> ![20220410-104111](https://user-images.githubusercontent.com/54717060/162598877-521dfd81-ea1c-483e-8749-61b961a09227.png) Are you sure it doesn't work? It works perfectly for me.

As you can see in the picture I've shown, It not works for me. But since it works perfectly for you, I tested again and 
found that it may because hlargs.nvim should be loaded after the colorscheme. Now it works well.
![image](https://user-images.githubusercontent.com/61115159/162599452-c44d4824-b376-474f-a570-a2b3dec9fbea.png)

I think it would be better if there is some adjustment for the color of the arguments, so I won't close this issue unless the maintainers close it themselves.

**Comment by Pocco81** [comment]
Since this issue was first opened the theme has gone through _a lot_ of changes. This should be working now.

Here is a [small example](https://github.com/catppuccin/nvim/issues/157#issuecomment-1182246836).
