### ISSUE TITLE
[Request] Change style for diff to looks like `git-delta`

### ISSUE THREAD

**Issue by latipun7** [catppuccin/nvim#114]
> About making it look like `git-delta`, I believe that could be given some thought as it seems a nice option.
> Only thing to take into account is the colors used in the palette, as they could be a bit too much if used as is for the background.
>
> _Originally posted by @jorgebef in https://github.com/catppuccin/nvim/issues/75#issuecomment-1004402008_

As mentioned in that comment, it would be nice to add background to the diff and leave the foreground to its syntax highlighting. I'm too used to see diff in that format from `git-delta` and GitHub, so I am easier to see diff with background and emphasized background if possible, and original syntax highlighting for the foreground.

Thank you.

![git-delta](https://i.imgur.com/LCMaJdj.png)
_background and emphasized background from `git-delta`_

![github](https://i.imgur.com/cxI4VSU.png)
_background and emphasized background from GitHub_

**Comment by Pocco81** [comment]
So let me get this straight: we are talking about the `diff*` and `Diff*` highlight groups, right? or are we talking about the particular highlights of a git integration plugin (e.g. `neogit`)?

**Comment by latipun7** [comment]
yes, I'm not using neogit (yet).

**Comment by Pocco81** [comment]
![image](https://user-images.githubusercontent.com/58336662/181065635-e134707d-0314-448b-ad69-f9f42f8db26a.png)

done.

**Comment by latipun7** [comment]
That looks nice, thank you @Pocco81 . But I didn't see the highlighted change. I mean the different highlight color for the same type of diff.
![image](https://user-images.githubusercontent.com/20012970/181182808-123d2806-bd36-4bd0-a7eb-5b875ec2e78f.png)
At the image above, diff for deletion is red, but at the exact what characters is deleted, that was highlighted with brighter red. 

Is it possible to achieve that in nvim?
