### ISSUE TITLE
Catppuccin theme issue in neovim

### ISSUE THREAD

**Issue by ciscohack** [catppuccin/nvim#115]
Hello Experts,

I have installed Catppuccin nvim theme on my macOS and observed some highlight around text and within text file. I don't know why this is coming as i haven't chanded yet just installed the theme through vim-plug. Can someone help me to fix it. is it a theme issue or some issue. I am not facing this issue with other themes

![image](https://user-images.githubusercontent.com/11479557/162592642-a67af0e1-f17c-48d5-a49c-2fcbb17b7910.png)

**Comment by EdenEast** [comment]
Does your terminal support true color? If it does then what is the value of your `$TERM` env var. Make sure that it is something that states that it supports 256 colors like `xterm-256color`

**Comment by ciscohack** [comment]
@ciscohack Issue resolved please close the ticket
