### ISSUE TITLE
Leap.nvim support

### ISSUE THREAD

**Issue by Suyashtnt** [catppuccin/nvim#118]
plugin URL: https://github.com/ggandor/leap.nvim

what can be customized:
On the screenshot:

![e](https://raw.githubusercontent.com/ggandor/leap.nvim/media/quick_example_3.png)

underlined: LeapMatch (note: as opposed to the screenshot, in the most recent version these are only shown if they cover a label)
green labels: LeapLabelPrimary
blue labels: LeapLabelSecondary
everything else: LeapBackdrop (nothing by default, but you can customize)

taken from https://github.com/ggandor/leap.nvim/issues/11

**Comment by Suyashtnt** [comment]
Still waiting :)

**Comment by Suyashtnt** [comment]
I'll make a PR soon to add it. Just gotta figure out how this works :)

**Comment by vinibispo** [comment]
I'll create a PR if you don't

**Comment by ggandor** [comment]
#159 assigned the same color for `LeapLabelPrimary` and `LeapLabelSecondary`, making the plugin unusable.
