### ISSUE TITLE
indent-blankline highlighting not working

### ISSUE THREAD

**Issue by RyanzpLee** [catppuccin/nvim#121]
I've enabled indent_blankline in my catpuccin setup, however the indentation line colours are just black, with or without transparent background. When I run `:verbose highlight IndentBlanklineIndent1-6` they show up as the correct colours, but they're still not showing. Please how do I get this working?

[Here's my dotfiles](https://github.com/RyanzpLee/dotfiles/blob/main/nvim/lua/user/plugins/catppuccin.lua)  

<img width="344" alt="image" src="https://user-images.githubusercontent.com/69594457/165940051-697c4a3e-d2ed-4dde-9358-c7246c4e3485.png">

```
indent_blankline = {
	enabled = true,
	colored_indent_levels = true,
}
```

**Comment by jorgebef** [comment]
After looking into your config, I see the options seem to be correct.
I suggest setting catppuccin as a colorscheme at the end, most importantly, after all plugins, so that the colors are loaded afterwards.
Please let us know if it works or not!

**Comment by RyanzpLee** [comment]
Turns out I had to explicitily add  the `char_highlight_list` to the indent_blankline setup and then it worked!

```
  char_highlight_list = {
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent3",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent5",
    "IndentBlanklineIndent6",
  },
```
