### ISSUE TITLE
Changing the style does not take effect

### ISSUE THREAD

**Issue by j2501987804** [catppuccin/nvim#127]
![image](https://user-images.githubusercontent.com/41771911/168707357-94834418-66a6-4832-b4d9-218db6115763.png)
neovim7.0
Excuse me, some styles are still tilted. Is this influenced by the theme? I changed it. It doesn't seem to work.

**Comment by sgoudham** [comment]
@j2501987804 I believe there's already an issue that addresses this (#95) with a workaround in the comments?
