### ISSUE TITLE
[Question] How to set up or select custom theme

### ISSUE THREAD

**Issue by asmodeus812** [catppuccin/nvim#128]
So i have noticed that in the old branch, there were a couple of pre built themes. Now with this master branch there are none. Only one (default) one which is pretty basic. My question is how on earth do you customize this plugin and what exactly is this plugin ? I have noticed that people fork this repo to be able to customize the default theme which imo is very bad design and idea.

**Comment by Pocco81** [comment]
Hey @asmodeus812! We recently released Catppuccin v0.2.0! This update brought some new variants of Catppuccin based off of the original palette we all know and love :)

So, for what its worth, you should consider checking the new palettes out: https://github.com/catppuccin/catppuccin/releases/tag/v0.2.0

And btw, the update already arrived here, in the neovim port! Check out the "setup" section in the readme and you'll be good to go.

**Comment by Pocco81** [comment]
Hope it's all clear now :+1:
