### ISSUE TITLE
Original Palette

### ISSUE THREAD

**Issue by axieax** [catppuccin/nvim#134]
Seems like the colorscheme for Catppuccin has completely changed after the latest merge. However, I prefer the original colours and was wondering how to get that back (last working f079dda3dc23450d69b4bad11bfbd9af2c77f6f3)

**Comment by ayamir** [comment]
Prefer original too.

**Comment by Pocco81** [comment]
Hey @axieax! What you are referring as original is, in fact, what we now called Catppuccin Mocha. It's the same palette, but just with a different name. I did chahe, but just a little. Nothing substantial.

Please refer to: https://github.com/catppuccin/catppuccin/issues/157

**Comment by axieax** [comment]
Hi I've tried Mocha already but it does seem that the colours are completely different (please see below). Not sure if I need to update my config in any way either.

OG Theme

![image](https://user-images.githubusercontent.com/62098008/170625086-0a18adfd-c4c8-436a-9152-43d3208d0952.png)

Mocha

![image](https://user-images.githubusercontent.com/62098008/170625016-cccfd223-6924-4522-ada0-6adca9084a06.png)

**Comment by Pocco81** [comment]
Oh wait I think I understand what you are referring to :)

The syntax highlighting changed a lot. So syntactical elements do look different from the original, however that's okay since the current syntactic rules are better 👍 

Also, please use [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) to get the full Catppuccin experience.

**Comment by axieax** [comment]
I see. I guess my issue is related to #157 where it would be nice to get another palette identical or close to what the original theme was (perhaps offered as another theme variant). Due to the merge, it's also difficult to pinpoint what exact changes have been made to manually remap to the original colours. Personally, this new palette looks closer to the colorschemes of material and tokyonight, which I do not like as much.

p.s. nvim-treesitter is enabled

**Comment by jonathan-nichols** [comment]
I prefer the old syntax highlight too. The color palette might be the same but the theme feels off now. It would be nice to have the old setup as an option.

**Comment by sandangel** [comment]
could we have an option to override the palette? I would like to keep the full list of support plugins, but want to change the palette. That would also fix this issue.

**Comment by goingtosleep** [comment]
Agree with @sandangel, an option to override the palette would be great.

**Comment by 3rd** [comment]
@sandangel @goingtosleep 
Ended up having the same need today, made a PR with my proposal:
https://github.com/catppuccin/nvim/pull/165
