### ISSUE TITLE
Non visible comments and other background highlight issues since last update

### ISSUE THREAD

**Issue by zakissimo** [catppuccin/nvim#136]
![image](https://user-images.githubusercontent.com/64891486/170582434-793b0277-b15d-4db1-927f-1754511637f0.png)

Hello,

Let me first thanks everyone involved in the making of this color theme that I find amazing. A pleasure for my eyes since day one. This is my first real issue with it.

As you can see here, the comments are no longer visible and I get this blackish background behind my virtual text and logos on the margin. 

It was all fine before the latest update.

**Comment by Pocco81** [comment]
Glad to hear you like the theme :)

> the comments are no longer visible

1. Which branch are you on?
2. Which flavour were you using in the screenshot?

> I get this blackish background behind my virtual text

That's normal and expected. They should make virtual text easier to see. The background colors of those things isn't black, they are a very opaque version of the color of their foreground(e.g. an error (which uses red foreground) has an opaque red background). It should look more normal if you were to be using a solid background color. But don't worry! You can disable them if you want :) Catppuccin provides an API for that:  https://github.com/catppuccin/nvim#overwriting-highlight-groups

Let me know if you'd like to have a snippet on how to do this exact thing.

> logos on the margin.

Those are sign column diagnostics. If I remember correctly you can disable them using: `vim.g.signcolumn = true`.

**Comment by zakissimo** [comment]
> * Which branch are you on?
> * Which flavour were you using in the screenshot?

I'm on the main branch using the following config:

```lua
local status_ok, catppuccin = pcall(require, "catppuccin")
if not status_ok then
	return
end

catppuccin.setup()

vim.cmd([[colorscheme catppuccin]])
```

> Let me know if you'd like to have a snippet on how to do this exact thing.

If you could help me out settings the background of the virtual text to transparent, I would really appreciate it. That being said, is there an easy way to detect the highlight group of a specific text ?

**Comment by zakissimo** [comment]
Okay, I figured it out :), here's my current config:

```lua
local status_ok, catppuccin = pcall(require, "catppuccin")
if not status_ok then
	return
end

catppuccin.setup()

local colors = require("catppuccin.api.colors").get_colors()

catppuccin.remap({
	Comment = { fg = colors.overlay2 },
	DiagnosticError = { bg = colors.none },
	DiagnosticInfo = { bg = colors.none },
	DiagnosticHint = { bg = colors.none },
	DiagnosticWarn = { bg = colors.none },
})

vim.cmd([[colorscheme catppuccin]])
```

And here's what it looks like:
![image](https://user-images.githubusercontent.com/64891486/170744142-1460f964-063e-41a5-a871-0a8ed28babbe.png)

Thanks for the directions, it really helped!

**Comment by zakissimo** [comment]
Okay, I thought it was fixed, but if I exit neovim and reopen, all the 'Diagnostic*' remaps are not applied, I have to open my theme config file and execute `:luafile %` for it to take effect. What am I missing ?

**Comment by arnavb** [comment]
I'm having the same issue; The remapping doesn't seem to stick until I manually reload my config file. I'm not sure why this is occurring.

**Comment by zakissimo** [comment]
> I'm having the same issue; The remapping doesn't seem to stick until I manually reload my config file. I'm not sure why this is occurring.

I'm temporarily loading the highlights in my settings file, this is what I currently have:

```lua
local status_ok, catppuccin = pcall(require, "catppuccin")
if not status_ok then
	return
end

catppuccin.setup()

local colors = require("catppuccin.api.colors").get_colors()

catppuccin.remap({
	Comment = { fg = colors.overlay1 },
	LineNr = { fg = colors.overlay1 },
	CursorLineNr = { fg = colors.sky },
	NvimTreeRootFolder = { fg = colors.sky },
	-- DiagnosticInfo = { bg = colors.none },
	-- DiagnosticError = { bg = colors.none },
	-- DiagnosticHint = { bg = colors.none },
	-- DiagnosticWarn = { bg = colors.none },
})

vim.cmd([[colorscheme catppuccin]])
```

```lua
vim.cmd([[hi DiagnosticError guibg=NONE]])
vim.cmd([[hi DiagnosticInfo guibg=NONE]])
vim.cmd([[hi DiagnosticHint guibg=NONE]])
vim.cmd([[hi DiagnosticWarn guibg=NONE]])
```

for me only the diagnostic highlights only load when I reload the config, but the rest works right away. Loading them separately in my settings.lua fixes it. Maybe it gets read too late? or too soon? I'm not really sure...

**Comment by CSpencerND** [comment]
> ```
> vim.cmd([[hi DiagnosticError guibg=NONE]])
> vim.cmd([[hi DiagnosticInfo guibg=NONE]])
> vim.cmd([[hi DiagnosticHint guibg=NONE]])
> vim.cmd([[hi DiagnosticWarn guibg=NONE]])
> ```

Putting this at the bottom of my init.lua works perfectly!

**Comment by zakissimo** [comment]
I had a doubt when I first wrote it but I just verified, you can write multiple commands in one go:

```lua
vim.cmd([[
    hi DiagnosticError guibg=NONE
    hi DiagnosticInfo guibg=NONE
    hi DiagnosticHint guibg=NONE
    hi DiagnosticWarn guibg=NONE
]])
```
Making it much cleaner. That being said it's still janky and odd that it won't work with catppuccin's settings imo.

**Comment by sgoudham** [comment]
> Okay, I thought it was fixed, but if I exit neovim and reopen, all the 'Diagnostic*' remaps are not applied, I have to open my theme config file and execute `:luafile %` for it to take effect. What am I missing ?

> I'm having the same issue; The remapping doesn't seem to stick until I manually reload my config file. I'm not sure why this is occurring.

I'm also getting this problem, some highlights and configurations are simply not loaded at the start and I have to reload the source config while in nvim for it to be properly applied. It didn't happen before the v2.0 changes so something recent must be causing this?

**Comment by nullchilly** [comment]
I have written a transparency FAQ on the dev branch https://github.com/catppuccin/nvim/tree/dev#transparent-background-tweak on how to achieve custom highlights. Personally I like the following:

![image](https://user-images.githubusercontent.com/56817415/179356392-a09408ea-43ee-4122-981d-4e24700eafe5.png)

Closing this issue since most default settings won't please users with different types of background images
