### ISSUE TITLE
The top part of nvim-tree not visible

### ISSUE THREAD

**Issue by Rishabh672003** [catppuccin/nvim#139]
as you can see in the image below that the first line which shows the working directory is invisible until you move the cursor there
![image](https://user-images.githubusercontent.com/53911515/170808390-43620f5a-efca-4534-8376-42020f00c7be.png) 
![image](https://user-images.githubusercontent.com/53911515/170808771-ae740978-b53b-4722-b00d-45382223b655.png)

**Comment by Pocco81** [comment]
Yep, that's intentional. I added that to give it a cool, clean look to `nvim-tree`. You can make it visible in your personal config:

```dev
nvimtree = {
	enabled = true,
	show_root = true, -- set this to `true`
}
```

**Comment by Rishabh672003** [comment]
thanks for the reply, i tried your solution but unfortunately it didn't worked for me 
![image](https://user-images.githubusercontent.com/53911515/170885460-d5570530-4b92-46a2-a41f-35a3e0c490a0.png)
is there something wrong with my config? 
Thanks for your help

**Comment by sgoudham** [comment]
I'm also getting the same issue as described above, even with enabling `show_root`

**Comment by d11638104** [comment]
The `nvimtree` setting does not seem to work, and this problem makes me sad
