### ISSUE TITLE
feline integration is broken

### ISSUE THREAD

**Issue by gmr458** [catppuccin/nvim#140]
![Captura de pantalla de 2022-05-29 13-51-54](https://user-images.githubusercontent.com/53343401/170886917-e8c3c512-3b92-4617-8d94-6c78d2f94369.png)

I thought it could be Packer, but if I use the default configuration of feline.nvim there are no errors.
![Captura de pantalla de 2022-05-29 13-50-22](https://user-images.githubusercontent.com/53343401/170886963-1b16d3f3-84a3-49e1-a5e3-fd9831307632.png)

**Comment by lispyclouds** [comment]
#137 should fix it.

**Comment by Pocco81** [comment]
Not anymore!
