### ISSUE TITLE
inconsistent colors for bufferline.nvim

### ISSUE THREAD

**Issue by gmr458** [catppuccin/nvim#141]
`highlight BufferLineCloseButton` has a different color background:
![Captura de pantalla de 2022-05-29 16-23-382 png](https://user-images.githubusercontent.com/53343401/170892079-e6baf0bb-0d8f-4ca5-b4a0-e66af1d3db7f.jpg)

`highlight BufferLineIndicatorVisible` has a different color background compared to the tab when I open a floating window like Telescope for example:
![Captura de pantalla de 2022-05-29 16-35-452 png](https://user-images.githubusercontent.com/53343401/170892362-41439c34-0531-41b9-a87c-8c3d96852dfe.jpg)

Please look at the images in a new browser tab and look at the mouse pointer that points to the incostences, all this because the resolution of my screen is 1366x768, so the screenshots do not have very good quality.

**Comment by bennypowers** [comment]
Doesn't look great with `transparent_background` either:
<img width="727" alt="Screen Shot 2022-05-30 at 19 04 37" src="https://user-images.githubusercontent.com/1466420/171028868-a022e764-0b04-41e2-bc3c-3b7ccd83c469.png">

**Comment by corei8** [comment]
Slant does not work, padded slant does not work, colors seem off. I am using Kitty terminal on macOS. I agree that it looks worse with `transparent_background`.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/38426287/173044488-7623cf99-a01f-40db-ba07-c7796dc2b557.png">

**Comment by Pocco81** [comment]
@bennypowers' PR should fix this.

**Comment by gmr458** [comment]
when I open NvimTree and one file is open there is an inconsistency (inside red circle)
![Captura desde 2022-06-16 22-12-32](https://user-images.githubusercontent.com/53343401/174217939-6195fea3-188c-4d36-be71-6163fa166560.png)

when I open NvimTree and two file are open there is other inconsistency (inside red circle)
![Captura desde 2022-06-16 22-21-07](https://user-images.githubusercontent.com/53343401/174218588-128c92e2-4f96-47b3-b906-0263d9005513.png)

the background of the close button on tabs that are not focused is inconsistent
![Captura desde 2022-06-16 22-17-29](https://user-images.githubusercontent.com/53343401/174218336-0ca65a65-365d-4949-b770-a1c1bf0d7b6d.png)
