### ISSUE TITLE
configuring nvim-tree using integration setup does not seem to work

### ISSUE THREAD

**Issue by Rishabh672003** [catppuccin/nvim#142]
i posted an issue about colors in nvim-tree here [Issue 139](https://github.com/catppuccin/nvim/issues/139), after that i tried your solution and configured nvim-tree using the setup(see in the image) but for me that isn't doing anything even changing other option of transparent background doesn't seem to do anything
![image](https://user-images.githubusercontent.com/53911515/170885460-d5570530-4b92-46a2-a41f-35a3e0c490a0.png)
it seems like the integration with nvim-tree is broken or is there something wrong with my config?  
Thanks for your help

_Originally posted by @Rishabh672003 in https://github.com/catppuccin/nvim/issues/139#issuecomment-1140500060_

**Comment by vanarok** [comment]
![2022-06-11T21:34:18,754029969+04:00](https://user-images.githubusercontent.com/6105977/173198738-b5431ed5-a1eb-4ca9-8e16-76b559b7430b.png)
It works for me.

**Comment by Icy-Thought** [comment]
Setting the colorscheme in a live neovim environment does the same thing, @drinkitup777.

**Comment by drinkitup777** [comment]
I figured it out, partially. `catppuccin.setup()` needs to run _very_ early, before anything else. I haven't found out what yet, but there must be an option or plugin somewhere that interferes with catppuccin's setup.
