### ISSUE TITLE
nvim-tree current directory text is too dark to see

### ISSUE THREAD

**Issue by drinkitup777** [catppuccin/nvim#144]
The cwd text in [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) doesn't show up anymore. The text color is too dark. This first started happening a few weeks back with an update of catppuccin.

![screenshot-hidden](https://user-images.githubusercontent.com/59168253/171064542-e4377b91-00ea-4629-81dc-5b0db79c0e47.png)

The text is still there, but it's normally too dark to see.
![screenshot with point](https://user-images.githubusercontent.com/59168253/171064475-761530c5-ca0a-425f-9a50-68bf2e5997fb.png)

This doesn't happen with other color schemes--only catppuccin.

**Comment by flor-morada** [comment]
I've had the same issue — it seems to update to the correct color upon executing :Catppuccin {flavor}.

**Comment by Pocco81** [comment]
@drinkitup777 that's intentional. You can enable that by setting the following in the `intergrations` section of your Catppuccin conf:

```lua
nvimtree = {
	enabled = true,
	show_root = true,
}
```

![image](https://user-images.githubusercontent.com/58336662/174171893-fcff229e-8400-49c8-b917-de95f060c102.png)
