### ISSUE TITLE
Need Transparent Background

### ISSUE THREAD

**Issue by sivaplaysmC** [catppuccin/nvim#145]
hello catppuccin t(h)eam ,

I am having trouble setting up  transparent background i think it is not possible

thanking you 
siva

**Comment by laxtiz** [comment]
```lua
local catppuccin = require('catppuccin')
catppuccin.setup {
  transparent_background = true,
}
```

btw, you may need set your terminal transparent yet, like gnome-terminal.
may be some other terminal like kitty and neovide, no need set nvim as trans.

**Comment by Pocco81** [comment]
Hey @sivaplaysmC! as @laxtiz pointed, you not only need to enable the `transparent_background` field in your Catppuccin settings, but also need to set transparency in your terminal.

Hope it's all clear now :+1:
