### ISSUE TITLE
Vim diagnostic signs not integrating with catppuccin

### ISSUE THREAD

**Issue by ggrangel** [catppuccin/nvim#146]
![1654005216](https://user-images.githubusercontent.com/20937937/171190757-46089334-d865-46c8-bb16-4eb0dacf86ea.png)

I haven't changed any default config. Should I do something to integrate catppuccin with vim diagnostic signs?

**Comment by CSpencerND** [comment]
If you're talking about the colored bg behind the icons in the gutter, I noticed this too. Cappuccin is the only scheme I have that does this.

**Comment by ggrangel** [comment]
> If you're talking about the colored bg behind the icons in the gutter, I noticed this too. 
Yes,  that's what I'm talking about.

**Comment by ggrangel** [comment]
> If you're talking about the colored bg behind the icons in the gutter, I noticed this too.

Yes, that's what I'm talking about.

PS: Sorry for accidentally closing the issue.

**Comment by vanarok** [comment]
Will there be a fix? I'm using the light version of theme.
![2022-06-11T18:17:51,676926883+04:00](https://user-images.githubusercontent.com/6105977/173191658-dbc946eb-8ffc-4376-be9b-714f3ac6623d.png)

**Comment by Pocco81** [comment]
Should be working by now :+1: 
![image](https://user-images.githubusercontent.com/58336662/178581200-45702d92-7e26-43de-b4a9-856e80329fc8.png)
