### ISSUE TITLE
Better highlights for search? 

### ISSUE THREAD

**Issue by her** [catppuccin/nvim#147]
I sincerely love this color scheme and it's making me so happy to use it. 

How can I boost the highlights for `/` searching in vim?

This is what highlights look like right now for searching. 
<img width="352" alt="Latte Highlights" src="https://user-images.githubusercontent.com/10278096/171331003-5de21572-36f1-40dc-bb8c-58173fb18754.png">
 
 This is what I would like instead, something bright and eye catching (The intense yellow)
<img width="358" alt="Screen Shot 2022-05-31 at 11 10 28 AM" src="https://user-images.githubusercontent.com/10278096/171331092-56a5a93a-c77c-488a-aec3-0ba21c5af2af.png">
 
 Perhaps there's an obvious way to configure this? If so I'll close the issue right away. Thanks again!

**Comment by vanarok** [comment]
Also on this thread:
![2022-06-11T18:38:03,888969756+04:00](https://user-images.githubusercontent.com/6105977/173192418-f46e4994-789a-4eaa-abe1-d81da8a9ab65.png)
![2022-06-11T18:39:56,817563176+04:00](https://user-images.githubusercontent.com/6105977/173192448-f0bfe17d-8f09-4ef6-8e92-ea71b84ced7a.png)
