### ISSUE TITLE
BUG: after_loading will recursion execute

### ISSUE THREAD

**Issue by laxtiz** [catppuccin/nvim#153]
if anywhere have created `catppuccin.after_loading` callback, the code below will create a new function then wrapped origin callback.

but this code have a bug, the new callback will recursive execute self, because here not old callback saved.

https://github.com/catppuccin/nvim/blob/773d339cbd307fe218cf7b3ea04eac26b345a3b7/lua/catppuccin/core/integrations/lightspeed.lua#L17-L26

maybe we need closure.

```lua
if catppuccin.after_loading ~= nil then
	local callback = catppuccin.after_loading
	catppuccin.after_loading = function ()
		callback()
		require'lightspeed'.init_highlight()
	end
else
	catppuccin.after_loading = function ()
	require'lightspeed'.init_highlight()
end

```

**Comment by Pocco81** [comment]
Closing because of #162
