### ISSUE TITLE
`italic` not configurable in `treesitter.lua`

### ISSUE THREAD

**Issue by kdheepak** [catppuccin/nvim#155]
There are some examples of `italic` not configurable in `treesitter.lua`:

https://github.com/catppuccin/nvim/blob/d46425163dad4cc74910c0c81eeedb00cadf8a61/lua/catppuccin/core/integrations/treesitter.lua#L38

https://github.com/catppuccin/nvim/blob/d46425163dad4cc74910c0c81eeedb00cadf8a61/lua/catppuccin/core/integrations/treesitter.lua#L45

https://github.com/catppuccin/nvim/blob/d46425163dad4cc74910c0c81eeedb00cadf8a61/lua/catppuccin/core/integrations/treesitter.lua#L83-L84

Is there a reason this was done in a way that is not configurable? I was because it results in inconsistent styling between filetypes that have treesitter support and those that do not, and I find it a little disorienting some times.

Happy to submit a PR to support this if there isn't a reason it should be this way.

The following lines have incorrect comments btw:

https://github.com/catppuccin/nvim/blob/d46425163dad4cc74910c0c81eeedb00cadf8a61/lua/catppuccin/core/integrations/treesitter.lua#L87-L88

**Comment by vinibispo** [comment]
@Pocco81 I think it's a good issue for analyzing

**Comment by Pocco81** [comment]
Fixed :tada:
