### ISSUE TITLE
remap of highlights doesn't seem to have an effect

### ISSUE THREAD

**Issue by desdic** [catppuccin/nvim#156]
I'm trying to make this via catppuccin
```
vim.cmd[[hi DiagnosticError guibg=Base]]
```

so I'm trying
```
local colors = require'catppuccin.api.colors'.get_colors()
require('catppuccin').remap({
        DiagnosticError = { bg = colors.Base },
})
```

but color doesn't change or do I get an error. Using plain settings with macchiato flavor set.

I just want to change it since the macchiato seems to have these off

```
vim.cmd[[hi NormalFloat guibg=Base]]
vim.cmd[[hi DiagnosticError guibg=Base]]
vim.cmd[[hi DiagnosticWarn guibg=Base]]
vim.cmd[[hi DiagnosticInfo guibg=Base]]
vim.cmd[[hi DiagnosticHint guibg=Base]]
```

**Comment by Pocco81** [comment]
For now check #138. I'll be updating the README with the new instructions on how to work this out.
