### ISSUE TITLE
Italic highlight granularity 

### ISSUE THREAD

**Issue by danielyrovas** [catppuccin/nvim#157]
Is there a way to italicize the `pub async fn` without italicizing the `Ok()` in Rust code?
Coming from `folke/tokyonight` and it has split those groups I think.
I have set keywords to be italic and set conditionals to be NONE.

**Comment by Pocco81** [comment]
Yes! we recently changed the way custom highlights are made so from now on you can set said highlights by using:

```lua
local cp = require("catppuccin.core.palettes.init").get_palette()

require("catppuccin").setup({
    custom_highlights = {
        TSConstBuiltin = { fg = cp.peach, style = "NONE" }, -- For constant that are built in the language: nil in Lua
    }
})
```

Keep in mind that a bunch of changes to the overall architecture of the plugin have arrived, so I'd recommend you to check out #178.
