### ISSUE TITLE
Gitsign icons have weird background

### ISSUE THREAD

**Issue by OlegGulevskyy** [catppuccin/nvim#160]
Hi!
First off - really great theme, thanks for great efforts!
I have a question / issue that I am not sure how to deal with. Gitsign icons have slightly different background in `nvim-tree` and in the buffers as well, making it look like broken a bit.
Would you have any advice on that?
![image](https://user-images.githubusercontent.com/43781031/175493951-df71bfa1-582b-453e-9cfc-4438fa081d2d.png)
![image](https://user-images.githubusercontent.com/43781031/175493969-33852f9a-13d6-4fd6-89d7-af94ec72bf14.png)

Thanks!

**Comment by ps-143** [comment]
I have observed the same thing. I would like to try to fix this issue. But I'm not sure if I can.

**Comment by OlegGulevskyy** [comment]
> If I am correct, is this because you have set the _G.cnf variable as nil because it is not required, and in the git signs file it is used to set the bg of the highlight?

I don't think I did, at least not explicitly. Where can I check if this variable is set or not?

**Comment by ps-143** [comment]
> > If I am correct, is this because you have set the _G.cnf variable as nil because it is not required, and in the git signs file it is used to set the bg of the highlight?
> 
> I don't think I did, at least not explicitly. Where can I check if this variable is set or not?

Sorry, I meant the developer has set this in the code and there is a comment that read that _G.cnf is not needed anymore but it is used to set the bg of the GitsignAdd highlight.

**Comment by OlegGulevskyy** [comment]
Hm, I know I said `gitsigns` in my initial message, but aren't those icons actually from LSP or something? They show status of diagnostics inside the file.
I am sorry if I caused confusion, I am fairly new to the world of (neo)vim

**Comment by ps-143** [comment]
The icons are from LSP, but there are highlight groups in neovim that are basically fg and bg colour values for specific elements. They are defined by our colorscheme of choice, such as our beautiful catppuccin colorscheme.

**Comment by ps-143** [comment]
Ohh I'm really sorry, I messed up these are lsp highlight groups. Sorry for the confusion. That's soo dumb of me.

**Comment by ps-143** [comment]
@OlegGulevskyy I've found out one thing if we use `require("catppuccin").load()` to set the colorscheme instead of the colorscheme command then the settings that we set for the theme are applied correctly. If we use the colorscheme command then the settings are ignored. I'm not sure why but it seems that the settings are applied (user options are loaded) after the colorscheme has been applied.

As for this issue. I think that the hl groups used in this colorscheme to set the color for sign column diagnostics and virtual text diagnostics are wrong. Let me see if I can fix those.

**Comment by OlegGulevskyy** [comment]
> @OlegGulevskyy I've found out one thing if we use `require("catppuccin").load()` to set the colorscheme instead of the colorscheme command then the settings that we set for the theme are applied correctly. If we use the colorscheme command then the settings are ignored. I'm not sure why but it seems that the settings are applied (user options are loaded) after the colorscheme has been applied.
> 
> As for this issue. I think that the hl groups used in this colorscheme to set the color for sign column diagnostics and virtual text diagnostics are wrong. Let me see if I can fix those.

Hm, unless I am loading it wrong way, it doesn't change anything.
Here is how I load it

```lua
local status_ok, catppuccin = pcall(require, "catppuccin")
if not status_ok then
	return
end

catppuccin.setup({
	integration = {
		nvimtree = {
			enabled = true,
			show_root = false,
			transparent_panel = false,
		},
		indent_blankline = {
			enabled = true,
			color_indent_levels = true,
		},
		gitsigns = true,
	}
})

vim.g.catppuccin_flavour = "macchiato" -- latte, frappe, macchiato, mocha
catppuccin.load()

```

**Comment by ps-143** [comment]
> 
> Hm, unless I am loading it wrong way, it doesn't change anything. Here is how I load it
> 
> ```lua
> local status_ok, catppuccin = pcall(require, "catppuccin")
> if not status_ok then
> 	return
> end
> 
> catppuccin.setup({
> 	integration = {
> 		nvimtree = {
> 			enabled = true,
> 			show_root = false,
> 			transparent_panel = false,
> 		},
> 		indent_blankline = {
> 			enabled = true,
> 			color_indent_levels = true,
> 		},
> 		gitsigns = true,
> 	}
> })
> 
> vim.g.catppuccin_flavour = "macchiato" -- latte, frappe, macchiato, mocha
> catppuccin.load()
> ```

You are loading it correctly.

**Comment by ps-143** [comment]
Hey, @Pocco81 can you help me a little. I think I've found a way to fix this issue and I would love to contribute. But I'm not able to raise the PR. Can you please guide me.

**Comment by Pocco81** [comment]
Hey @ps-143! sorry for not responding. I've been a tad bit busy here. Anyways the problem seems to have to have been solved, right? In that case, I'm going to be closing the issue... Let me know if guys still have problems!

**Comment by OlegGulevskyy** [comment]
Hey @Pocco81 , the problem is not solved I am afraid, at least not for me. (sorry I wasn't able to keep up with the issue)
I still have the same icons as showed in my initial report. Anything I can do to check if I have the actual `solved` version?
