### ISSUE TITLE
invalid key: bold,italic

### ISSUE THREAD

**Issue by hahuang65** [catppuccin/nvim#177]
#173 was fixed, but now it looks like there's a new issue...

```
packer.nvim: Error running config for catppuccin: /home/hao/.config/nvim/lua/plugin/catppuccin.lua:62: Vim(lua):E5108: Error executing lua ...ck/packer/start/catppuccin/lua/catppuccin/utils/util.lua:26: invalid key: bold,italic
stack traceback:
^I[C]: in function 'nvim_set_hl'
^I...ck/packer/start/catppuccin/lua/catppuccin/utils/util.lua:26: in function 'highlight'
^I...ck/packer/start/catppuccin/lua/catppuccin/utils/util.lua:48: in function 'syntax'
^I...ck/packer/start/catppuccin/lua/catppuccin/utils/util.lua:94: in function 'load'
^I...ite/pack/packer/start/catppuccin/lua/catppuccin/main.lua:19: in function 'load'
^I...ite/pack/packer/start/catppuccin/lua/catppuccin/main.lua:32: in function 'main'
^I...ite/pack/packer/start/catppuccin/lua/catppuccin/init.lua:4: in function 'load'
^I[string ":lua"]:1: in main chunk
^I[C]: in function 'cmd'
^I/home/hao/.config/nvim/lua/plugin/catppuccin.lua:62: in main chunk
^I[C]: in function 'require'
^I[string "..."]: in function <[string "..."]:0>
^I[C]: in function 'pcall'
^I/home/hao/.config/nvim/plugin/packer_compiled.lua:60: in function 'try_loadstring'
^I/home/hao/.config/nvim/plugin/packer_compiled.lua:479: in function </home/hao/.config/nvim/plugin/packer_compiled.lua:10>
^I[C]: in function 'pcall'
```

**Comment by nullchilly** [comment]
I am to blame for this, this was for the performance

https://github.com/catppuccin/nvim/pull/176

Please change `style = "bold,italic"` to `style = { "bold, "italic" }`

I intended to notify users about the deprecation but it seems like there is no way to do that without performance issue

Missed opportunity to include it in the pull request commit message

**Comment by Pocco81** [comment]
@nullchilly I can amend the commit of yours and append a `BREAKING CHANGE` to it. Does that sound good?

**Comment by nullchilly** [comment]
@Pocco81 And update the readme while you are at it :)
```
#### Styles

Handles the style of general hi groups (see `:h highlight-args`):

-   `comments`: (String/Table) changed the style of the comments.
-   `functions`: (String/Table) changed the style of the functions.
-   `keywords`: (String/Table) changed the style of the keywords.
-   `strings`: (String/Table) changed the style of the strings.
-   `variables`: (String/Table) changed the style of the variables.
```

**Comment by Pocco81** [comment]
Alright! I'm also planning on making a [migration](https://github.com/catppuccin/nvim/commit/12ca216fe9c5156d4db9943e8b8089d0935e244b#commitcomment-78321686) guide btw.

**Comment by Pocco81** [comment]
@nullchilly https://github.com/catppuccin/nvim/commit/eb5410f250cd50a9f2663857f2cf6d46a9e5ef24

**Comment by Pocco81** [comment]
@nullchilly I found another issue: most highlight styles that are taken from the users' conf are still written in `strings` and not in Lua tables. So for instance, this doesn't work:

**default config:**
```lua
	styles = {
		comments = "italic",
		conditionals = "italic",
		loops = "NONE",
		functions = "NONE",
		keywords = "NONE",
		strings = "NONE",
		variables = "NONE",
		numbers = "NONE",
		booleans = "NONE",
		properties = "NONE",
		types = "NONE",
		operators = "NONE",
	},

```

**treesitter integration (example):**

```lua
		TSKeywordFunction = { fg = cp.mauve, style = cnf.styles.keywords or "NONE" }, -- For keywords used to define a fuction.
		TSKeyword = { fg = keywords, style = cnf.styles.keywords or "NONE" }, -- For keywords that don't fall in previous categories.
		TSKeywordReturn = { fg = cp.mauve, style = cnf.styles.keywords or "NONE" },

```

Don't worry tho! I'm gonna go over every integration and amend them :+1:

**Comment by nullchilly** [comment]
@Pocco81 But I specifically have an if condition for that

https://github.com/catppuccin/nvim/blob/edd620668b4f547d89c68cda9b1911c17fa51780/lua/catppuccin/utils/util.lua#L15-L22

Seems to be working for me
![image](https://user-images.githubusercontent.com/56817415/178645345-6220b9aa-bc61-48ac-b388-e42be44b348c.png)

**Comment by nullchilly** [comment]
@Pocco81 The core is still mostly written in string

The reason I didn't make them all table is to avoid too many lines of pull request

If you want to go all out, here is the pull request from my local :)
