### ISSUE TITLE
Theme not appyling to telescope even after setting it true in integrations

### ISSUE THREAD

**Issue by Rishabh672003** [catppuccin/nvim#180]
![image](https://user-images.githubusercontent.com/53911515/178714126-1f2e7735-3538-4cfb-b9db-ee726fd08028.png)
![image](https://user-images.githubusercontent.com/53911515/178714425-12c73fb7-04b5-4dc9-884e-b349fa261f8b.png)

**Comment by nullchilly** [comment]
This is the catppuccin's telescope theme, nothing is wrong here according to the code

https://github.com/catppuccin/nvim/blob/edd620668b4f547d89c68cda9b1911c17fa51780/lua/catppuccin/core/palettes/mocha.lua#L7-L34

https://github.com/catppuccin/nvim/blob/edd620668b4f547d89c68cda9b1911c17fa51780/lua/catppuccin/core/integrations/telescope.lua#L5-L18

If anything it wasn't working properly before

**Comment by Rishabh672003** [comment]
oh my bad, but yeah in my opinion it looked way better with border, so if the theme wont have any border how can i add it myself?

**Comment by Rishabh672003** [comment]
thanks for your help I just forked the theme and added the border myself

**Comment by nullchilly** [comment]
Haha, I didn't tell you how to remap tho... 
It looks like this:
```
require("catppuccin").setup({
    custom_highlights = {
	TelescopeBorder = { fg = cp.blue },
    },
})
```

@Pocco81 Should we add an option to enable telescope border?

**Comment by Pocco81** [comment]
sure @nullchilly!

**Comment by her** [comment]
hi hi! just finding this. for me, the way Telescope looked before this update was great IMO. would really like that back :) if the path forward is making telescope integration user configurable, then the previous styling would make an excellent sane default. love this theme!

**Comment by her** [comment]
@brunobmello25 yes it is! yay!
