### ISSUE TITLE
Telescope styles broke after last update

### ISSUE THREAD

**Issue by brunobmello25** [catppuccin/nvim#185]
I'm not sure what went wrong, but I ran packerSync and it updated a bunch of plugins (been about 3 weeks since I last did this).

Here is how telescope is currently looking. I didn't change anything in telescope config nor in catppuccin config. Notice it is missing transparency, and some other stuff (ignore the blue squares. I censored some stuff):
![image](https://user-images.githubusercontent.com/29875060/178832830-d24b9d5c-ffe1-4949-a36b-4bd930cbd0ae.png)

---

Previously it would look like this:
![image](https://user-images.githubusercontent.com/29875060/178832791-2638d487-0b0b-457d-9562-1022af843d1d.png)

Here is my current config, branch main: https://github.com/brunobmello25/skeleton.nvim

**Comment by nullchilly** [comment]
https://github.com/catppuccin/nvim/issues/180

**Comment by brunobmello25** [comment]
the border doesn't seem to be the only issue. It also lost transparency and finder info (text that tells you if you are finding files, finding with grep, etc)

**Comment by nullchilly** [comment]
@brunobmello25 You can disable telescope integration until we fix it

**Comment by nullchilly** [comment]
@brunobmello25 Kindly reopen the issue so other user don't open another issue about this!

**Comment by brunobmello25** [comment]
@nullchilly of course!
