### ISSUE TITLE
MatchParen Inverse/Reverse for greater visibility?

### ISSUE THREAD

**Issue by her** [catppuccin/nvim#187]
Hi y'all, looking at [MatchParen](https://github.com/catppuccin/nvim/blob/edd620668b4f547d89c68cda9b1911c17fa51780/lua/catppuccin/core/mapper.lua#L46) in `mapper.lua` how can we make this inverse? 

Right now a foreground only highlight choice of `cp.peach` has a low contrast when a closing glyph is already a yellow-type hue

<img width="529" alt="image" src="https://user-images.githubusercontent.com/10278096/178895043-17ecfd2d-4904-49ed-8cd7-8789fd377ea2.png">

Thoughts? 

As always, loving this theme :) happy to make a PR too if someone wants to point me in the general direction!

**Comment by Pocco81** [comment]
Heya @her! are you using `treesitter`? your syntax seems a bit off.

**Comment by her** [comment]
oh hi @Pocco81! I do have `treesitter`, maybe I need to run `TSUpdate`? or what are ya thinking? thanks :)

**Comment by nullchilly** [comment]
@her I think you didn't install lua treesitter, do `:TSInstall lua` and it should look like this:

![image](https://user-images.githubusercontent.com/56817415/178924183-56a217d2-5838-4f3a-8113-cc57ce7ceca4.png)

If you actually installed it `setup` shouldn't have the same color as `integrations` or `telescope` In any case to make it more visible override your own color. For example:
```lua
require("catppuccin").setup {
	custom_highlights = {
		MatchParen = { fg = "#FE640B", bg = "#000000", style = { bold = true } },
	},
}
```

**Comment by her** [comment]
thank you so much @nullchilly 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/10278096/179145405-c325e75a-d5a6-40fb-9e51-d88ccddc8039.png">

I didn't have the Lua tree sitter parser installed :) it does make the match paren more noticeable. Appreciate the guide on how to custom set the colors as well! cheers 🎉
