### ISSUE TITLE
remap not working anymore

### ISSUE THREAD

**Issue by RitschAlex** [catppuccin/nvim#197]
Since the last update, the remap function is not working anymore

![image](https://user-images.githubusercontent.com/70853152/179276331-bcbf6d0f-386b-4d38-8835-5a39437dbbec.png)
![image](https://user-images.githubusercontent.com/70853152/179276472-87f86cde-3e27-4228-891e-c9d60cabb5da.png)

**Comment by nullchilly** [comment]
Deprecated by the new option

```lua
require("catppuccin").setup {
	custom_highlights = {
		MatchParen = { fg = "#FE640B", bg = "#000000", style = { "bold" } },
	},
}
```

**Comment by Pocco81** [comment]
Also! the `api` module was deprecated to. Use `("catppuccin.palettes").get_palette()` instead.
