### ISSUE TITLE
Toggle based on background value? 

### ISSUE THREAD

**Issue by her** [catppuccin/nvim#199]
Is there a way to hook Catppuccin to auto toggle when the background of nvim changes?

the docs has this 

>Remember that if you want to switch your Catppuccin flavour "on the fly" you may use the :Catppuccin <flavour> command.
>Note: the command has autocompletion enabled, so you can just press tab to cycle through the flavours

but I want `latte` if the background is `light, and `mocha` is the background is `dark`. 

How can I make this happen? 

thanks you guys!

**Comment by her** [comment]
also, am happy to update the docs on how to do this if that makes sense!

**Comment by nullchilly** [comment]
You can try this, cheers!
```lua
vim.api.nvim_create_autocmd("OptionSet", {
	pattern = "background",
	callback = function()
		vim.cmd("Catppuccin " .. (vim.v.option_new == "light" and "latte" or "mocha"))
	end,
})
```
> also, am happy to update the docs on how to do this if that makes sense!
Pull requests are welcome, thank you so much :)

**Comment by nullchilly** [comment]
I have created a FAQ section, let me know what you think!

https://github.com/catppuccin/nvim/tree/dev#toggle-lightdark-theme-based-on-background-value

Pull requests to improve it are welcome :)
