### ISSUE TITLE
Add nvim-dap and nvim-dap-ui integration

### ISSUE THREAD

**Issue by igorlfs** [catppuccin/nvim#205]
Hello!

As an inspiration, I've been using a [custom branch](https://github.com/catppuccin/nvim/commit/8d196b8552ddbb869d9dd0c19816e464c982b17e) which broke with the latest changes to master (I think it's pointless to try and maintain something only I'll use)

**Comment by nullchilly** [comment]
Instead of running a custom branch, can you make a pull request? I will happily merge it :)

**Comment by Pocco81** [comment]
Otherwise we can add it ourselves. You decide :)

**Comment by igorlfs** [comment]
> Instead of running a custom branch, can you make a pull request? I will happily merge it :)

Oh sure, at first I didn't wanna open a PR because the colors I've used are highly opinionated (though based on nvim-dap-ui's default theme), but I'll look into that.

**Comment by nullchilly** [comment]
@igorlfs 
![image](https://user-images.githubusercontent.com/56817415/179411513-2da28797-48d8-4821-a49e-f41c2cb1cce0.png)
Is this what you had in mind?

**Comment by igorlfs** [comment]
> Is this what you had in mind?
That's exactly what I had in mind :)

**Comment by rubenmate** [comment]
@Pocco81 Latte could be considered too? Some areas are so low contrast it's impossible to read them.
<img width="1392" alt="latte_dapui" src="https://user-images.githubusercontent.com/79601967/179867536-f4593751-f320-4df1-86a8-76d03904ab86.png">
