### ISSUE TITLE
`catppuccin_flavour` seems broken

### ISSUE THREAD

**Issue by usmcamp0811** [catppuccin/nvim#211]
I just started using this colorscheme (very nice btw..) but it seems that the `catppuccin_flavour` is hard coded or some how not working from my config. 

I set my `colorscheme` this way:

```
vim.cmd [[
try
  let g:catppuccin_flavour = "mocha" " latte, frappe, macchiato, mocha
  colorscheme catppuccin
catch /^Vim\%((\a\+)\)\=:E185/
  colorscheme auto
  set background=dark
endtry
]]
```
and nothing changes from the default. 

If I do `:Catppuccin mocha` things change.. and I like how they change.. but  I don't want to have to manually do this every time. 

What am I doing wrong.. or is this a real bug? 

TIA

**Comment by nullchilly** [comment]
auto is not a colorscheme and `set background=dark` will break your highlights

Please read the readme section: https://github.com/catppuccin/nvim#usage

```
vim.g.catppuccin_flavour = "macchiato" -- latte, frappe, macchiato, mocha

require("catppuccin").setup()

vim.cmd [[colorscheme catppuccin]]
```

**Comment by usmcamp0811** [comment]
```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
  use {
    "catppuccin/nvim",
    as = "catppuccin",
    run = ":CatppuccinCompile"
  }
  if packer_bootstrap then
    require('packer').sync()
  end
end)

vim.cmd [[
try
  let g:catppuccin_flavour = "mocha" " latte, frappe, macchiato, mocha
  colorscheme catppuccin
catch /^Vim\%((\a\+)\)\=:E185/
  colorscheme auto
  set background=dark
endtry
]]
```

Just tried it on another system (like just this minute so I haven't fully tested everything) and it seems like whats happening is when I do `:Catppuccin mocha` it makes the background more transparent maybe.. definitely darker (which is what I was wanting)
