### ISSUE TITLE
colorscheme with bufferline separator_style 'slant' does not work

### ISSUE THREAD

**Issue by ShiChenCong** [catppuccin/nvim#212]
![image](https://user-images.githubusercontent.com/22486446/180352773-1a22293e-f85b-4cda-8a46-a25ed6230498.png)
title is the summary
expect work like
![image](https://user-images.githubusercontent.com/22486446/180352867-45b98662-81e8-4351-bad8-360d3e836f1f.png)

**Comment by nullchilly** [comment]
Will this do the trick?
![image](https://user-images.githubusercontent.com/56817415/180366290-0f3fbd25-4755-4f61-8420-9922886db17b.png)

**Comment by ShiChenCong** [comment]
how you do that？ not work here

**Comment by nullchilly** [comment]
@ShiChenCong You can use the dev branch for now. I added a fast fix and still need to debate about colors and such

```lua
	use {
		"catppuccin/nvim",
		branch = "dev",
		as = "theme",
	}
```

**Comment by ShiChenCong** [comment]
something weird here
![image](https://user-images.githubusercontent.com/22486446/180388718-8b3eb1cc-952c-439c-902d-99c6c013dcb7.png)

**Comment by nullchilly** [comment]
@ShiChenCong Fixed, try updating again

**Comment by ShiChenCong** [comment]
@nullchilly  works! Thank you for the work and timely reply
