### ISSUE TITLE
`transparent_background` not respected on nvim open

### ISSUE THREAD

**Issue by garcia5** [catppuccin/nvim#213]
After updating Catppuccin this morning, my config of `transparent_background = true` no longer takes effect when I open neovim. However, If I run `:Catppuccin [any flavor]`, the setting is picked up and I get a transparent background. Running `:CatppuccinClean`/`:CatppuccinCompile` does not work either, only manually setting a flavor seems to pick up the setting

My config:

`lua/ag/plugin-conf/catppuccin.lua`
```lua
local catp = require("catppuccin")

vim.g.catppuccin_flavour = "mocha"
catp.setup({
    transparent_background = true,
    term_colors = true,
    compile = {
        enabled = true,
        path = vim.fn.stdpath("cache") .. "/catppuccin",
    },
    styles = {
        comments = { "italic" },
        strings = { "italic" },
    },
    integrations = {
        gitsigns = true,
        telescope = true,
        treesitter = true,
        cmp = true,
        nvimtree = {
            enabled = true,
            show_root = false,
        },
        dap = {
            enabled = true,
            enable_ui = true,
        },
        native_lsp = {
            enabled = true,
        },
        ts_rainbow = true,
        indent_blankline = {
            enabled = true,
            colored_indent_levels = false,
        },
    },
})
```

`lua/ag/plugins.lua`
```lua
-- Bootstrap packer if necessary
local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
local packer_bootstrap = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    packer_bootstrap = vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end

-- Init setup
vim.cmd("packadd packer.nvim") -- load packer
local packer = require("packer")

packer.startup(function(use)

    use({
        "catppuccin/nvim",
        as = "catppuccin",
        branch = "main",
        config = function() require("ag.plugin-conf.catppuccin") end,
        run = ":CatppuccinCompile",
    })
)
```

output of `nvim --version`
```
NVIM v0.8.0-dev+2054-g5c3bbb67e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by agarcia@MacBook-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-5c3bbb6/share/nvim"

Run :checkhealth for more info
```

**Comment by nullchilly** [comment]
I think you missed `vim.cmd [[colorscheme catppuccin]]` at the end of your config?

**Comment by garcia5** [comment]
Ah sorry, forgot to include that in my config. I do have that in my `init.lua`

```lua
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.cmd("colorscheme catppuccin")
```

**Comment by nullchilly** [comment]
@garcia5 Can you push an update to your nvim config so I can test?

**Comment by nullchilly** [comment]
Your config works fine for me

![image](https://user-images.githubusercontent.com/56817415/180463219-6866a6d6-f6dd-4230-9930-ad8eacd08b19.png)

Not sure what went wrong on your side?

**Comment by garcia5** [comment]
Hm that's very weird, I just tried with a minimal config and am still getting the same issue

`/tmp/minimal.lua`
```lua
-- /tmp/minimal.lua
-- Init setup
vim.cmd("packadd packer.nvim") -- load packer
local packer = require("packer")

packer.startup(function(use)
    use({
        "catppuccin/nvim", -- another another lua colorscheme
        as = "catppuccin",
        branch = "main",
        config = function ()
            require('catppuccin').setup({
                transparent_background = true,
            })
        end,
        run = ":CatppuccinCompile",
    })
end)

vim.cmd("colorscheme catppuccin")
```

`nvim -nu /tmp/minimal.lua`
![image](https://user-images.githubusercontent.com/21695295/180465100-dfa3edc1-925a-4a74-9e74-e18682213e08.png)
`:CatppuccinStatus`
![image](https://user-images.githubusercontent.com/21695295/180465304-7ac7271c-9dd2-408b-a290-b413a701fa72.png)
`:Catppuccin mocha`
![image](https://user-images.githubusercontent.com/21695295/180465352-f21d3551-4097-472b-82ed-796e52f3f98e.png)

**Comment by Pocco81** [comment]
@garcia5 did you try to re-compile? Also, which branch are you on?

**Comment by nullchilly** [comment]
Why is the compile status said all failed?

**Comment by garcia5** [comment]
> @garcia5 did you try to re-compile? Also, which branch are you on?

In the minimal config I don't have `compile` enabled. On my normal one though the compile status looks okay

`:CatppuccinStatus` on my normal config
```
[✓]: latte      /Users/agarcia/.cache/nvim/catppuccin/latte_compiled.lua                                                                                                                      
[✓]: frappe     /Users/agarcia/.cache/nvim/catppuccin/frappe_compiled.lua                                                                                                                     
[✓]: macchiato  /Users/agarcia/.cache/nvim/catppuccin/macchiato_compiled.lua                                                                                                                  
[✓]: mocha      /Users/agarcia/.cache/nvim/catppuccin/mocha_compiled.lua
```

**Comment by nullchilly** [comment]
@garcia5 Can you open `/Users/agarcia/.cache/nvim/catppuccin/mocha_compiled.lua` and search for "Normal"

What is the content of the line?

**Comment by Pocco81** [comment]
Similar to @nullchilly, the transparent background does work on my end too:

![image](https://user-images.githubusercontent.com/58336662/180466846-39e4068f-c855-44e8-8189-90fc816b53a1.png)

**Comment by garcia5** [comment]
> @garcia5 Can you open `/Users/agarcia/.cache/nvim/catppuccin/mocha_compiled.lua` and search for "Normal"
> 
> What is the content of the line? is `bg = nil`?

I have `vim.api.nvim_set_hl(0, "Normal", { bg = "NONE", fg = "#CDD6F4" })`

There are also a few other `"Normal"` hl groups being set, and not all of them have bg = "NONE"
```
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE", fg = "#CDD6F4" })
vim.api.nvim_set_hl(0, "NormalSB", { bg = "#11111B", fg = "#CDD6F4" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#181825", fg = "#CDD6F4" })
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE", fg = "#CDD6F4" })
```

**Comment by nullchilly** [comment]
Yeah bg = "NONE" on Normal is enough for transparency

**Comment by Pocco81** [comment]
@garcia5 do you mind sharing your nvim conf?

**Comment by nullchilly** [comment]
Yeah your updated config would help since it could be the config loading order. Loading order can be undefined which leads to "But it works on my side"

**Comment by garcia5** [comment]
https://github.com/garcia5/dotfiles/tree/master/files/nvim

Thanks for helping so much on this btw! Love the colorscheme

**Comment by nullchilly** [comment]
I am able to reproduce your error now :D

**Comment by garcia5** [comment]
`:verbose hi Normal` outputs
```
Normal         xxx guifg=#cad3f5 guibg=#24273a
        Last set from Lua
```

that guibg is coming from the [macchiato base](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/palettes/macchiato.lua#L32), even though my flavor should be 'mocha'

**Comment by garcia5** [comment]
So if I add a `catp.load()` call at the end of my `catppuccin.lua` config file it works? I used to have it there but then I thought there was a change recently to remove the need for it

```lua
-- lua/ag/plugin-conf/catppuccin.lua
local catp = require("catppuccin")

vim.g.catppuccin_flavour = "mocha"
catp.setup({
    transparent_background = true,
    term_colors = true,
    compile = {
        enabled = true,
        path = vim.fn.stdpath("cache") .. "/catppuccin",
    },
    styles = {
        comments = { "italic" },
        strings = { "italic" },
    },
    integrations = {
        gitsigns = true,
        telescope = true,
        treesitter = true,
        cmp = true,
        nvimtree = {
            enabled = true,
            show_root = false,
        },
        dap = {
            enabled = true,
            enable_ui = true,
        },
        native_lsp = {
            enabled = true,
        },
        ts_rainbow = true,
        indent_blankline = {
            enabled = true,
            colored_indent_levels = false,
        },
    },
})
catp.load() -- NOW CONFIG LOADS AS EXPECTED
```

**Comment by nullchilly** [comment]
@garcia5 If you call `colorscheme catppuccin` it will `doautocmd ColorschemePre` then execute https://github.com/catppuccin/nvim/blob/main/colors/catppuccin.lua then `doautocmd ColorScheme`

I am still unable to locate the error in your config tho, the colorscheme on my end is correcly set to mocha but transparent doesn't work...

**Comment by nullchilly** [comment]
Ok nevermind, I go inside `lua/ag/plugin-conf/catppuccin.lua` did a `source | CatppuccinCompile` and transparency works now

**Comment by nullchilly** [comment]
I think I got it
Add the enable_reload_compiled for it to work first try

```
require("packer").init {
	auto_reload_compiled = true
}
```

Refer to: https://github.com/catppuccin/nvim#auto-compile

**Comment by garcia5** [comment]
I think this might be something about how packer handles loading my config. If I move the config inline, I get transparency. With my config being `require`d in another file, I have to manually call `catp.load()` or `vim.cmd("colorscheme catppuccin")` from my config

```lua
packer.setup(function(use)
    use({
        "catppuccin/nvim", -- another another lua colorscheme
        as = "catppuccin",
        branch = "main",
        config = function()
            -- this works!
            local catp = require("catppuccin")

            vim.g.catppuccin_flavour = "mocha"
            catp.setup({
                transparent_background = true,
                term_colors = true,
                compile = {
                    enabled = true,
                    path = vim.fn.stdpath("cache") .. "/catppuccin",
                },
                styles = {
                    comments = { "italic" },
                    strings = { "italic" },
                },
                integrations = {
                    gitsigns = true,
                    telescope = true,
                    treesitter = true,
                    cmp = true,
                    nvimtree = {
                        enabled = true,
                        show_root = false,
                    },
                    dap = {
                        enabled = true,
                        enable_ui = true,
                    },
                    native_lsp = {
                        enabled = true,
                    },
                    ts_rainbow = true,
                    indent_blankline = {
                        enabled = true,
                        colored_indent_levels = false,
                    },
                },
            })
        end,
        run = ":CatppuccinCompile",
    })
end)
```

**Comment by nullchilly** [comment]
Which is exactly the reason you need `auto_reload_compiled`

**Comment by garcia5** [comment]
There we go, the `auto_reload_compiled` did it! Thanks so much

**Comment by nullchilly** [comment]
Thanks you for your time!

**Comment by garcia5** [comment]
All this effort just to see a little bit of my wallpaper while I code 🤦

**Comment by hiql** [comment]
I use LazyVim, sometimes ok,sometimes not, it was a tad confusing...
