### ISSUE TITLE
Consider setting `IndentBlanklineContextStart`

### ISSUE THREAD

**Issue by johnallen3d** [catppuccin/nvim#215]
indent-blankline.nvim recently [added support for underlining context](
https://github.com/lukas-reineke/indent-blankline.nvim/commit/33f6f9faa993efdd28f067d58c80dcffd1e97a8f). By default it looks like this with Catppuccin (Mocha palette).

<img width="750" alt="CleanShot 2022-07-23 at 14 11 00@2x" src="https://user-images.githubusercontent.com/184915/180617685-c69d837c-2a8b-4fbc-b8aa-94a76e6a9e13.png">

In my opinion it looks better when the underline matches the indent line. By setting a custom highlight I can make that happen.

```lua
vim.cmd([[highlight IndentBlanklineContextStart guisp=#CDD6F4 gui=underline]])
```
(edit: corrected `guisp` 👆)

<img width="544" alt="CleanShot 2022-07-24 at 09 43 26@2x" src="https://user-images.githubusercontent.com/184915/180649830-5ae29954-38e8-4fa3-8fd2-5f8084fadfaa.png">

Perhaps this should be the default behaviour of `catppuccin/nvim`?

**Comment by nullchilly** [comment]
Added on the dev branch: https://github.com/catppuccin/nvim/commit/afd581cdfa1f50e6d14aea77f50de168fc7296c1

**Comment by johnallen3d** [comment]
That works perfectly, thank you @nullchilly!

re: `fg` vs `sp`... yes, @lukas-reineke [schooled me](https://github.com/lukas-reineke/indent-blankline.nvim/issues/459#issuecomment-1193242705) on that. I seem to have copied an older version of that line into this issue, my bad.
