### ISSUE TITLE
List points in VimWiki look ugly.

### ISSUE THREAD

**Issue by matthias-Q** [catppuccin/nvim#216]
In the VimWiki integration, the fg and bg are both set to "peach"
```lua		
VimwikiList = { fg = cp.peach, bg = cp.peach },
VimwikiTag = { fg = cp.peach, bg = cp.peach },
```
which lets them look like big orange blocks, directly before the text starts. 
I have fixed that for myself with a custom HL group, but I am not sure if that is intentional.

**Comment by nullchilly** [comment]
I fixed it with `bg = cp.none`. Thank you 👍🏻
