### ISSUE TITLE
Latest change for DiffDelete has same bg and fg

### ISSUE THREAD

**Issue by bharat-ap** [catppuccin/nvim#217]
Both Fg and Bg has the same color for DiffDelete, which causes the issue shown in screenshot. 
The issue is in the this line https://github.com/catppuccin/nvim/blob/484c7d741176f471ae4425af40e3c0cd97da188e/lua/catppuccin/groups/syntax.lua#L77
 
 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/85085338/181156512-a828bfff-f403-46ab-ab34-97f8662bb632.png">

**Comment by vinibispo** [comment]
@Pocco81

**Comment by nullchilly** [comment]
Temporary reverted to `DiffDelete = { fg = cp.red, bg = cp.base }`

Wait for pocco.
