### ISSUE TITLE
Error while calling lua chunk: ...ite/pack/packer/start/catppuccin/lua/catppuccin/init.lua:37: attempt to call local 'command' (a nil value)

### ISSUE THREAD

**Issue by LukeOrth** [catppuccin/nvim#219]
I am getting this error when installing Catppuccin with Packer.

![image](https://user-images.githubusercontent.com/35306887/182021068-9fab9347-ea4f-4f2a-829b-b64591a71bc0.png)

More info:
- Commit: [2d687d5](https://github.com/catppuccin/nvim/commit/2d687d5bc769941fd38a9c9be1f860b4c848943b)
- Nvim: v0.6.1
- Ubuntu 22.04 (jammy)
- Kernel: 5.15.0-43-generic

I'm not passing any custom configurations to Catppuccin's `setup()` function.

**Comment by nullchilly** [comment]
This plugin requires nvim >= 0.7
