### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by alessandroDeIturbe** [catppuccin/nvim#221]
I've just installed this plugin, and it gives me this error, what do I do?

<img width="1552" alt="Schermata 2022-08-03 alle 00 20 19" src="https://user-images.githubusercontent.com/63016931/182492664-0427fd29-a863-4878-acbd-749c63a9aa9e.png">

**Comment by nullchilly** [comment]
Replace `require("catppuccin.core.palettes.init").get_palette()` with `require("catppuccin.palettes").get_palette()` on the line 277

How can you use the old api if you just installed the plugin today 🤔

**Comment by alessandroDeIturbe** [comment]
Thank you.
I've discovered this plugin from a forum, maybe it wasn't up to date. Sorry for the inconvenience

**Comment by nullchilly** [comment]
No problem 👍🏻
