### ISSUE TITLE
Invalid flavour

### ISSUE THREAD

**Issue by thomashoggard** [catppuccin/nvim#223]
After the latest update it seems that the there is a problem with the flavour.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/9698979/182653944-54f78fac-7405-49a2-a8f7-ba5adf754d65.png">

The issue occurs when importing the module `local colors = require("catppuccin.palettes").get_palette()`.  If I remove this line it resolves the issue.

**Comment by nullchilly** [comment]
Did you read the error message?

**Comment by thomashoggard** [comment]
That seems to have fixed it 🎉 .  I'm not sure which error message you were referring to, the only message I saw was the screeshot above which wasn't very informative on the root cause.

**Comment by nullchilly** [comment]
Can you test it with your original config?

**Comment by nullchilly** [comment]
Sorry for the abomination of commits, I am on auto-pilot right now..

Honestly, I am going to revert the error messages as it will cause more frustration even if it's user's fault.

**Comment by thomashoggard** [comment]
Just looked at the docs now and I think it's clear that you need to set the flavour before the `get_palette`.  I think they changed since the last time I configured things but for any new configs they make sense.  Too bad that there's no way to lazy load `get_palette` until after the flavour global is set 🤔
