### ISSUE TITLE
Problem with Leap.nvim integration

### ISSUE THREAD

**Issue by ggandor** [catppuccin/nvim#229]
Bug: #159 assigned the same color for LeapLabelPrimary and LeapLabelSecondary, making the plugin unusable.

Subjective note: I also find it a bit odd that `LeapMatch` has a saturated color, while the labels are grey (and barely visible).

P.S.: is `Backdrop` necessary? I guess users can set it easily if they want "greywash", it's better to leave it opt-in.

@Suyashtnt  @Pocco81

**Comment by nullchilly** [comment]
I will make leap.nvim integration close to default

**Comment by nullchilly** [comment]
@ggandor Can you try the dev branch, is this correct?

![image](https://user-images.githubusercontent.com/56817415/182828843-cb8acdd2-2293-457c-9ff2-4f0d0ac55910.png)

![image](https://user-images.githubusercontent.com/56817415/182828929-84afba27-3cf2-476b-80df-87e48d90db61.png)

**Comment by ggandor** [comment]
Looks great, sure. Maybe we could choose different base colors for `latte`, and make it somehow "softer", instead of following the defaults? But it's totally fine like this too, with its cheerful summery ice-cream-stand vibe 🍧

> To be honest I am switching to leap.nvim, this seems way less complicated!

Yeah, exactly, this was the aim :)
