### ISSUE TITLE
Can't install with Vim-plug

### ISSUE THREAD

**Issue by NicolaiRuckel** [catppuccin/nvim#240]
I tried to install Catppuccin with Vim-plug, but I ran into some issues. I tried it with
```
Plug 'catppuccin/nvim', {'as': 'catppuccin', 'branch': 'main' }
```
in my `init.vim` and get the following error:

```
Error detected while processing /home/nicolai/dotfiles/config/nvim/plugged/nvim/lua/catppuccin/init.lua:
E5113: Error while calling lua chunk: ...icolai/.config/nvim/plugged/nvim/lua/catppuccin/init.lua:37: attempt to call local 'command' (a nil value)
stack traceback:
        ...icolai/.config/nvim/plugged/nvim/lua/catppuccin/init.lua:37: in main chunk
```

I run Neovim in WSL2 with Ubuntu 22.04.

```
$ nvim -v
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Any ideas what the problem might be?

**Comment by nullchilly** [comment]
You need neovim 0.7 I don't understand why ubuntu latest release version is 4 months outdated

Anyway, update it using the unstable ppa: https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

**Comment by NicolaiRuckel** [comment]
That helped, thanks a lot!

I guess what you get for using Ubuntu... 😅

**Comment by Pocco81** [comment]
@NicolaiRuckel from my personal experience I'd you to switch to Fedora. [It's much better IMHO](https://www.youtube.com/watch?v=54aoIGKEMnk).

**Comment by NicolaiRuckel** [comment]
I'll get a new laptop soon, and then I don't have to deal with WSL any more anyway, but thanks for the recommendation. :)
