### ISSUE TITLE
Add options to modify style of function parameters and namespaces (treesitter)

### ISSUE THREAD

**Issue by nfejzic** [catppuccin/nvim#242]
Hello everyone!

Thank you for the theme, I enjoy using it for my config. 

Could we add styles for function parameters and namespaces as well? I would like to disable italics for namespaces in Rust for example:

![image](https://user-images.githubusercontent.com/40841816/183900516-e08e27f0-b377-46dc-9e3f-d7a8360e81f2.png)

Would it be possible to differentiate between variable and namespace in this case?

I would gladly implement this and open a PR, with your guidance and help (if necessary).

**Comment by nullchilly** [comment]
https://github.com/catppuccin/nvim#overwriting-highlight-groups You can change it via custom_highlight

See `:h nvim-treesitter-highlights`

**Comment by nfejzic** [comment]
Oh, I should read the documentation better... Thank you very much!
