### ISSUE TITLE
packer/start/nvim/lua/catppuccin/lib/highlighter.lua:11: bad argument #1 to 'ipairs' (table expected, got string)

### ISSUE THREAD

**Issue by zhanglin2018** [catppuccin/nvim#245]
:colorscheme catppucError detected while processing /root/.local/share/nvim/site/pack/packer/start/nvim/colors/catppuccin.lua:
E5113: Error while calling lua chunk: ...ack/packer/start/nvim/lua/catppuccin/lib/highlighter.lua:11: bad argument #1 to 'ipairs' (table expected, got string)
stack traceback:
        [C]: in function 'ipairs'
        ...ack/packer/start/nvim/lua/catppuccin/lib/highlighter.lua:11: in function 'highlight'
        ...ack/packer/start/nvim/lua/catppuccin/lib/highlighter.lua:22: in function 'syntax'
        ...ack/packer/start/nvim/lua/catppuccin/lib/highlighter.lua:40: in function 'load'
        ...nvim/site/pack/packer/start/nvim/lua/catppuccin/init.lua:27: in function 'load'
        ...e/nvim/site/pack/packer/start/nvim/colors/catppuccin.lua:1: in main chunk

**Comment by zhanglin2018** [comment]
I don't know how to fix this issue quickly.

**Comment by nullchilly** [comment]
`style = "italic"` -> `style = { "italic" }`

Just a quick glance at https://github.com/catppuccin/nvim#configuration please thank you
