### ISSUE TITLE
nvim-tree and lualine background is not being set to transparent

### ISSUE THREAD

**Issue by mslalith** [catppuccin/nvim#247]
## Description

I'm using [nvim-transparent](https://github.com/xiyaowong/nvim-transparent) plugin for transparency but background colors of nvim-tree & lualine are not being applied

## Behavior

**Expected behavior**
Background colors are to be made transparent

**Screenshots**
<img width="1440" alt="Screenshot 2022-08-22 at 2 38 30 PM" src="https://user-images.githubusercontent.com/15076234/185885037-995ddd39-80f1-47b2-8289-e29e6756bd02.png">

## Configuration

```lua
local catppuccin = require("catppuccin")

vim.g.catppuccin_flavour = "macchiato" -- latte, frappe, macchiato, mocha
catppuccin.setup {
    transparent_background = true,
    term_colors = true,
    compile = {
        enabled = true,
        path = vim.fn.stdpath("cache") .. "/catppuccin",
    },
    integrations = {
        gitsigns = true,
        telescope = true,
        treesitter = true,
        cmp = true,
        nvimtree = {
            enabled = true,
            show_root = true,
            transparent_panel = false,
        },
        native_lsp = {
            enabled = true,
        },
        notify = true,
        hop = true,
        aerial = true,
        bufferline = true,
    },
}
vim.cmd("colorscheme catppuccin")
```

<details>
<summary>minimal_init.lua</summary>

A [minimal_init.lua](https://github.com/catppuccin/nvim/blob/main/minimal_init.lua) file template is located at the root of the project.

```
-- this is how I install
use {
  "catppuccin/nvim",
  as = "catppuccin",
  run = ":CatppuccinCompile"
}
```

</details>

## Additional info / context
here's my [nvim config](https://github.com/mslalith/dotfiles/tree/main/nvim/.config/nvim)

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

**Comment by nullchilly** [comment]
```
        nvimtree = {
            enabled = true,
            show_root = true,
            transparent_panel = false,
        },
```

Change `transparent_panel` to true

**Comment by mslalith** [comment]
@nullchilly even the above is not working for some reason

<img width="1440" alt="Screenshot 2022-08-23 at 7 09 49 AM" src="https://user-images.githubusercontent.com/15076234/186049769-3e2108f1-4154-4f08-9bef-cb9906689184.png">

**Comment by nullchilly** [comment]
@mslalith Sorry for the inconvenient, I will look into it

**Comment by mslalith** [comment]
@nullchilly thanks for fixing this. I see in your commit, you've only made changes for lualine. Issue still exists for nvim-tree

**Comment by nullchilly** [comment]
@mslalith nvimtree is also fixed on my side

**Comment by nullchilly** [comment]
@mslalith 
![image](https://user-images.githubusercontent.com/56817415/186102301-6b15d3b9-516d-4ed2-b90c-348304635492.png)

**Comment by mslalith** [comment]
@nullchilly can you try with this setup. I still see a bg color in mine

<img width="1435" alt="Screenshot 2022-08-23 at 1 23 30 PM" src="https://user-images.githubusercontent.com/15076234/186103164-777b3a5a-f24e-4d78-a0f2-9df6780f4219.png">

```lua
local nvim_tree = require("nvim-tree")
local tree_cb = require("nvim-tree.config").nvim_tree_callback

nvim_tree.setup {
    create_in_closed_folder = true,
    respect_buf_cwd = true,
    view = {
        width = 30,
        height = 30,
        hide_root_folder = false,
        side = "left",
        preserve_window_proportions = false,
        mappings = {
            custom_only = false,
            list = {
                { key = { "l", "<CR>", "o" }, cb = tree_cb("edit") },
                { key = "h", cb = tree_cb("close_node") },
                { key = "v", cb = tree_cb("vsplit") },
            },
        },
    },
    diagnostics = {
        enable = true,
        show_on_dirs = false,
        icons = {
            hint = "",
            info = "",
            warning = "",
            error = "",
        },
    },
    actions = {
        open_file = {
            quit_on_open = true,
            resize_window = false,
            window_picker = {
                enable = true,
                chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
            },
        },
    },
    trash = {
        cmd = "trash",
        require_confirm = true,
    },
    renderer = {
        root_folder_modifier = ":~",
        highlight_git = true,
        add_trailing = true,
        group_empty = true,
        highlight_opened_files = "icon",
        indent_markers = {
            enable = true,
        },
        special_files = {
            ["Cargo.toml"] = true,
            Makefile = true,
            MAKEFILE = 1,
            ["README.md"] = true,
            ["readme.md"] = true,
        },
        icons = {
            show = {
                git = true,
                folder = true,
                file = true,
                folder_arrow = true,
            },
        },
    },
}

-- Will automatically close the tab/vim when nvim-tree is the last window in the tab
vim.cmd([[
  autocmd BufEnter * ++nested if winnr("$") == 1 && bufname() == "NvimTree_" . tabpagenr() | quit | endif
]])

```

**Comment by nullchilly** [comment]
Have you recompile catppuccin?

**Comment by mslalith** [comment]
I did not, let me try

**Comment by mslalith** [comment]
getting this

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/15076234/186104738-3826df97-7e34-4f5b-9bee-b52800247187.png">

**Comment by nullchilly** [comment]
Oh my gosh I shouldn't have trusted the backward compatibility claim

**Comment by mslalith** [comment]
Seems like it. I switched to nightfox for the time being. Let me know after your changes, I'm happy to try

**Comment by nullchilly** [comment]
@mslalith Can you try updating

**Comment by nullchilly** [comment]
I have pushed https://github.com/catppuccin/nvim/commit/3a5f324694b0bef9206bc85c10bbf14817f81f98

**Comment by mslalith** [comment]
@nullchilly yup, working now !!

**Comment by mslalith** [comment]
thanks for you efforts man
