### ISSUE TITLE
Support for coc's new popup menu

### ISSUE THREAD

**Issue by pulcinello** [catppuccin/nvim#250]
In the recent release of coc.nvm, the author replaced vim's built-in pum with custom popup menu, so `PmenuSel` won't work in coc's completion menu anymore, and the highlight is now controlled by `CocMenuSel`. You can find more details in [this page](https://github.com/neoclide/coc.nvim/pull/3862), Please consider add support for it. Thanks!

**Comment by nullchilly** [comment]
I don't use coc myself, is it possible for you to send a pull request?

**Comment by pulcinello** [comment]
pr sent.
