### ISSUE TITLE
File icons have transparent background in Bufferline

### ISSUE THREAD

**Issue by ilias777** [catppuccin/nvim#251]
Hi! I have the problem, that the file icons in the Bufferline are transparent. 
I like to have the option _transparent_background_ to **false**, but you can see in the screenshot below, that the background are not the same as the background with the file name.

<img width="660" alt="1" src="https://user-images.githubusercontent.com/39212564/186517715-7fb37648-a3da-4c96-9d7c-c6753a23408a.png">

I tried of course to set the background-highlight to *manle*, in the *custom_highlichts* table and after in the *highlight_overrides* table, but unfortunately without success. The highlight groups that I have tried, was **BufferLineBackcrust**, **BufferLineVisible** and **BufferLineBufferVisible**. None of them solved the problem.
Then I searched with Telescope other highlights for the file icons. I found **BufferLineDevIconLua**, **BufferLineDevIconLuaSelected** and **BufferLineDevIconLuaInactive**. But that is only for Lua language. 
For Python, for example, exist the highlight groups **BufferLineDevIconPy**, **BufferLineDevIconPySelected** and **BufferLineDevIconPyInactive**. And all of them have no background, only foreground as you can see in the screenshots.

<img width="1517" alt="lang1" src="https://user-images.githubusercontent.com/39212564/186521565-179c7cc7-3af1-47b8-90bd-d382c89110a6.png">

<img width="1498" alt="lang2" src="https://user-images.githubusercontent.com/39212564/186521585-16c44993-c8b8-4fad-a63a-cdaf4ea20217.png">

It is possible to set the background for all languages at once, without to set the background for the specific language in the *custom_highlights* section?

This was the first problem.  The second is, the buffers there are not selected, so the visible buffers, have the *text* foreground and not the *surface1* background, that I have seen in other screenshots, like in issue #141. Same here, all the highlight groups that I've tried not changing the foreground from the visible (not selected) buffers, as you can see in the screenshot below.

<img width="1912" alt="3" src="https://user-images.githubusercontent.com/39212564/186524687-41fde387-18fe-4695-8fab-26894b642957.png">

If I open Telescope for example, only the selected buffer *(the selected buffer in the screenshot was bufferline.lua)* turns the foreground from *text* to *mante*, but the other buffers stay the same...

<img width="1912" alt="2" src="https://user-images.githubusercontent.com/39212564/186525386-d53580bc-f5cf-486d-9f48-4faf19ab4f0c.png">

If I set the option *transparent_background* to **true**, then the other buffers are turn to **blue** and I don't know why!!!

<img width="767" alt="blue" src="https://user-images.githubusercontent.com/39212564/186526682-e3e423da-d6ee-4bc8-8ca3-a68bcb581fd3.png">

Then if I leave the *transparent_background* to **true**, have the Beacon plugin different highlight.

Normal **Beacon** behavior, with **transparent_background = false**...

https://user-images.githubusercontent.com/39212564/186527413-116134c1-7789-4507-8a4e-d18122a52dce.mov

And with **transparent_background = true**...

https://user-images.githubusercontent.com/39212564/186527719-179c2010-93aa-4c45-acee-aa14bdaca49c.mov

The color is darken!!

So my Catppuccin configuration are...

```lua
vim.g.catppuccin_flavour = 'macchiato' -- latte, frappe, macchiato, mocha

local catppuccin = require('catppuccin')
local cp = require('catppuccin.palettes').get_palette()

catppuccin.setup({
    dim_inactive = {
        enabled = false,
        shade = 'dark',
        percentage = 0.15,
    },
    transparent_background = false,
    term_colors = false,
    compile = {
        enabled = false,
        path = vim.fn.stdpath('cache') .. '/catppuccin',
    },
    styles = {
        comments = { 'italic' },
        conditionals = { 'italic' },
        loops = {},
        functions = {},
        keywords = { 'italic' },
        strings = {},
        variables = { 'italic' },
        numbers = {},
        booleans = { 'italic' },
        properties = { 'italic' },
        types = {},
        operators = {},
    },
    integrations = {
        treesitter = true,
        native_lsp = {
            enabled = true,
            virtual_text = {
                errors = { 'italic' },
                hints = { 'italic' },
                warnings = { 'italic' },
                information = { 'italic' },
            },
            underlines = {
                errors = { 'underline' },
                hints = { 'underline' },
                warnings = { 'underline' },
                information = { 'underline' },
            },
        },
        lsp_trouble = true,
        cmp = true,
        lsp_saga = false,
        gitgutter = false,
        gitsigns = true,
        telescope = true,
        nvimtree = {
            enabled = false,
            show_root = true,
            transparent_panel = false,
        },
        dap = {
            enabled = true,
            enable_ui = true,
        },
        which_key = false,
        indent_blankline = {
            enabled = true,
            colored_indent_levels = true,
        },
        dashboard = true,
        neogit = true,
        vim_sneak = false,
        barbar = false,
        bufferline = {
            enable = false,
            italics = true,
            bolds = true,
        },
        markdown = true,
        ts_rainbow = true,
        hop = true,
        notify = false,
        telekasten = false,
        symbols_outline = true,
        aerial = false,
        beacon = true,
        navic = true,
    },
    custom_highlights = {
        TelescopeBorder = { fg = cp.blue },
        TelescopeSelectionCaret = { fg = cp.flamingo },
        TelescopeSelection = { fg = cp.text, bg = cp.surface0, style = { 'bold' } },
        TelescopeMatching = { fg = cp.blue },
        TelescopePromptPrefix = { bg = cp.crust },
        TelescopePromptNormal = { bg = cp.crust },
        TelescopeResultsNormal = { bg = cp.mantle },
        TelescopePreviewNormal = { bg = cp.crust },
        TelescopePromptBorder = { bg = cp.crust, fg = cp.crust },
        TelescopeResultsBorder = { bg = cp.mantle, fg = cp.mantle },
        TelescopePreviewBorder = { bg = cp.crust, fg = cp.crust },
        TelescopePromptTitle = { fg = cp.mauve },
        TelescopeResultsTitle = { fg = cp.mauve },
        TelescopePreviewTitle = { fg = cp.mauve },
        Beacon = { bg = cp.teal },
        BufferLineIndicatorSelected = { fg = cp.pink },
        BufferLineModifiedSelected = { fg = cp.teal },
        BufferLineVisible = { fg = cp.pink, bg = cp.mantle },
        BufferLineIndicatorVisible = { bg = cp.mante },
        BufferLineBackcrust = { fg = cp.surface1, bg = cp.mantle },
    },
    highlight_overrides = {},
})

vim.cmd([[colorscheme catppuccin]])
```

I tried for the last 3 days to fix this, but I can't get any further. 😥

I am on macOS Monterey with Kitty 0.25.2

Thank you for any help!

**Comment by nullchilly** [comment]
You can see https://github.com/dracula/vim/issues/284 for the reason why this happens

Would you like to pull request a hack for this issue?

**Comment by ilias777** [comment]
I forgot to write, that I have no transparency set in my Kitty config. And I use the cattppuccin theme (macchiato) for Kitty as well.

Bufferline have updated before a few hours to version 2.8.1 and it looks like this now...

<img width="734" alt="bufferline-v2 8 1" src="https://user-images.githubusercontent.com/39212564/186613089-b9039af5-e551-4a10-8289-d0a310aaf545.png">

The icon background is a little bit darker as the Catppuccin background.

If I make the Kitty's background darker, it has no affect to the Catppuccin background. I think the Catppuccin theme is on top of the Kitty theme, and that's why it doesn't helps. This only helps when I set the *transparent_background* to **true**, but in this case it's not necessary to darken Kitty's background, because Kitty have the same theme (macchiato) as Neovim.

I think the problem was in the Bufferline plugin. Now it is partially solved with the new Bufferline version, but I can live with that. The icon background is now a little bit darker.

But my problem with the other buffers still exist. Es you can see in the screenshot below, the other Buffers *(bufferline.lua and lsp-config.lua)* have the foreground *"text"* and not *"surface1"*. 

<img width="678" alt="buffers" src="https://user-images.githubusercontent.com/39212564/186624308-a9f59675-4e49-4eb5-9312-e9087730aa37.png">

How can I set the filename, to be darker? Like in the screenshot in issue #141. If you see the first screenshot in this issue, the *init.lua* and the *plugins.lua* have a darker foreground. 
What is the highlight group for the other buffers?

Thank you again 😊

**Comment by nullchilly** [comment]
Yeah bufferline theme support is very problematic :(

I will see what I can do.

**Comment by nullchilly** [comment]
@ilias777 In the mean time you can set `bufferline = false`

**Comment by ilias777** [comment]
If I set `bufferline = false`, stay the Bufferline the same as `bufferline = true`. I don't know why.

Look the screen capture below on the three buffers in the Bufferline. If I work with split panes, bufferline behaves perfectly.

https://user-images.githubusercontent.com/39212564/187002927-4bd903d6-656c-41db-ae95-b56a0c507937.mov

That's exactly how I imagine it when I work with no split-windows.
Maybe it helps you to understand what's going on there!! I still don't get it!! 😅

**Comment by nullchilly** [comment]
@ilias777 Check https://github.com/catppuccin/nvim#special-integrations out!

**Comment by ilias777** [comment]
Yes I have checked! Now is all working as expected!
Thank you very much! 😊
