### ISSUE TITLE
Colors are different after changes to rules for defining highlights in tree-sitter

### ISSUE THREAD

**Issue by heygarrett** [catppuccin/nvim#255]
After [#169](https://github.com/catppuccin/nvim/issues/169) was opened a bunch of changes have taken place. Please read the MIGRATION GUIDE before opening an issue then tick the box below
- [x] I have read [MIGRATION GUIDE](https://github.com/catppuccin/nvim/issues/178)

## Description

Breaking change in the neovim repo:  
https://github.com/neovim/neovim/issues/14090#issuecomment-1228444035

Before:  
<img width="470" alt="Screen Shot 2022-08-26 at 12 52 00" src="https://user-images.githubusercontent.com/1154912/186955436-c395ee50-d2a5-4686-8229-0618580c9536.png">

After:  
<img width="470" alt="Screen Shot 2022-08-26 at 12 52 10" src="https://user-images.githubusercontent.com/1154912/186955471-92cc1287-337f-4e44-9466-255b5c824f68.png">

## Configuration

Included in above screenshots.

**Reproduce**

1. Use Neovim built from the main branch

<details>
<summary>minimal_init.lua</summary>

A [minimal_init.lua](https://github.com/catppuccin/nvim/blob/main/minimal_init.lua) file template is located at the root of the project.

Reproducible using the minimal_init.lua template without any changes (though I'm using mocha instead of macchiato in my screenshots).

</details>

## Additional info / context

NVIM v0.8.0-dev-2417-g2ecb4076d-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by garrett@Garretts-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-2ecb407_1/share/nvim"

**Comment by nullchilly** [comment]
I will look into it.
