### ISSUE TITLE
SignColumn and FoldColumn is not shading

### ISSUE THREAD

**Issue by Wansmer** [catppuccin/nvim#259]
First, thank you for great colorscheme. I am using shading inactive buffers, but it not working for SignColumn and FoldColumn. When SingColumn contains some icons and in inactive state - it's look like this columns belong to active buffer.
I have trying to overide this behavior with `cp.dim`, but it no working for me.
How can i do this?
<img width="915" alt="1" src="https://user-images.githubusercontent.com/46977173/187022146-de8fc33e-99f0-4e58-8a33-cf3fb36d0ef7.png">
<img width="794" alt="2" src="https://user-images.githubusercontent.com/46977173/187022152-4f4222f2-2d0d-4bb5-bb11-2cb65d8c13ed.png">

**Comment by nullchilly** [comment]
Will see 👍🏻
