### ISSUE TITLE
Add unit and integration tests

### ISSUE THREAD

**Issue by nullchilly** [catppuccin/nvim#263]
As testing configuration by hand or reviewing pull requests takes a lot of time, I would like a way to automatically check for:
- [ ] Simple configurations (transparency, compile, etc)
- [ ] Configurations that require plugin integrations (bufferline, lualine, etc) Refer to [Special integrations](https://github.com/catppuccin/nvim#special-integrations)

This will allow us to support backward compatibitity or if there exists a breaking change it should be mentioned in https://github.com/catppuccin/nvim/issues/260

**Comment by nullchilly** [comment]
@vinibispo I saw your repo [ruby.nvim](https://github.com/vinibispo/ruby.nvim/tree/main/tests) with [plenary](https://github.com/nvim-lua/plenary.nvim#plenarytest_harness)

May I ask if you are up to tackle this issue

**Comment by vinibispo** [comment]
Sure

**Comment by nullchilly** [comment]
Added in the latest release https://github.com/catppuccin/nvim/releases/tag/v1.1.0
