### ISSUE TITLE
colorscheme isnt correctly applied in markdown when vim.opt_local.spell = true

### ISSUE THREAD

**Issue by Rishabh672003** [catppuccin/nvim#280]
### Description

when you set vim.opt_local.spell = true in markdown file, with treesitter installed for markdown, colorscheme is very weird 
 

### Neovim version

```markdown
VIM v0.8.0-dev-1073-g2ea6584a1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux

### Catppuccin version / branch / rev

catppuccin main

### Steps to reproduce

1. nvim --clean -u minimal.lua
2. open any markdown file

### Expected behavior

this is with tokyonight colorscheme - 
![image](https://user-images.githubusercontent.com/53911515/189833682-5c8d50e7-8a7a-4892-9314-5e8388b94a2f.png)

### Actual behavior

this is what you see - 
![image](https://user-images.githubusercontent.com/53911515/189833804-52ee50b4-6b6f-4579-b903-a8ef6353a2d7.png)

### Minimal config

```Lua
-- `minimal.lua` used for reproducible configuration
-- Open with `nvim --clean -u minimal.lua`

local is_windows = vim.fn.has("win32") == 1
local function join(...)
	local sep = is_windows and "\\" or "/"
	return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local site_path = join(root_tmp, "nvim", "site")
local pack_path = join(site_path, "pack")
local install_path = join(pack_path, "packer", "start", "packer.nvim")
local compile_path = join(install_path, "plugin", "packer_compiled.lua")
vim.opt.packpath = site_path

local function load_plugins()
	local packer = require("packer")
	local use = packer.use
	packer.reset()
	packer.init({ compile_path = compile_path, package_root = pack_path })

	use("wbthomason/packer.nvim")
	use({ "catppuccin/nvim", as = "catppuccin" })
	-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
	use({
		"nvim-treesitter/nvim-treesitter",
		-- run = ":TSUpdate",
	})

	packer.install()
end

_G.load_config = function()
	-- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
	vim.g.catppuccin_flavour = "mocha"
	require("catppuccin").setup({
		transparent_background = false,
		integrations = {
			telescope = true,
		},
		custom_highlights = {
			WhichKeyGroup = { fg = "#FAB387" },
			WhichKeySeparator = { fg = "#cdd6f4" },
		},
	})

	local status_ok, treesitter = pcall(require, "nvim-treesitter")
	if not status_ok then
		return
	end

	local status_ok1, configs = pcall(require, "nvim-treesitter.configs")
	if not status_ok1 then
		return
	end

	configs.setup({
		ensure_installed = { "lua", "markdown", "markdown_inline", "bash", "python" }, -- put the language you want in this array
		-- ensure_installed = "all",
		sync_install = false, -- install languages synchronously (only applied to `ensure_installed`)
		ignore_install = { "vim" }, -- List of parsers to ignore installing
		autopairs = {
			enable = true,
		},
		highlight = {
			enable = true, -- false will disable the whole extension
			disable = { "vim" }, -- list of language that will be disabled
			additional_vim_regex_highlighting = true,
		},
		indent = { enable = true, disable = { "python", "css" } },
		context_commentstring = {
			enable = true,
			enable_autocmd = false,
		},
	})

	vim.api.nvim_create_autocmd({ "FileType" }, {
		pattern = { "markdown" },
		callback = function()
			vim.opt_local.wrap = true
			vim.opt_local.spell = true
		end,
	})

	vim.cmd("colorscheme catppuccin")
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])

```

**Comment by nullchilly** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua#L185

FileType autocmd call treesitter default highlight groups. Not sure how tokyonight avoided this.

**Comment by nullchilly** [comment]
Seem like we can skip treesitter default highlight group using `vim.g.skip_ts_default_groups`

Will take a look when I am back from work

**Comment by Rishabh672003** [comment]
hey @nullchilly it still not fixed for me
Actual behaviour with minimal config - 
![image](https://user-images.githubusercontent.com/53911515/190064700-9ca5fa7b-aa46-49f5-9c32-c2d3130e5f25.png)

**Comment by Rishabh672003** [comment]
also when the autocommand is enable the coloring of code inside codeblocks of markdown file is disabled
with autocommand - 
![image](https://user-images.githubusercontent.com/53911515/190068915-8f8ab2ff-7038-46e2-beb4-418667b2dc09.png)
without autocommand- 
![image](https://user-images.githubusercontent.com/53911515/190068969-4308ed15-273e-4be7-bcf3-59b21f12544e.png)

**Comment by nullchilly** [comment]
Did you recompile catppuccin?

**Comment by nullchilly** [comment]
Whats the output of `:lua print(vim.g.skip_ts_default_groups)` ?

**Comment by Rishabh672003** [comment]
> Did you recompile catppuccin?

yes

> @Rishabh672003 Whats the output of `:lua print(vim.g.skip_ts_default_groups)` ?

true

**Comment by nullchilly** [comment]
@Rishabh672003 Yes I am able to reproduce with `:lua vim.opt_local.spell = true` which I believe is equivalent to `:doautocmd FileType`. However after `:TSHighlightCapturesUnderCursor` I have no idea why is it wrong, perhaps some problem with conceal?


![image](https://user-images.githubusercontent.com/56817415/190156890-e275098a-5dee-4375-b75d-02cd56fdb1dc.png)

I have no idea for now :<

**Comment by nullchilly** [comment]
Apprently there is a `@spell` highlight group below

If I set `:hi @text.uri guifg=NONE` the error went away, tokyonight didn't have this issue simply because they [didn't set those highlight groups](https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/theme.lua#L258)

Maybe it's an upstream issue about `:set spell`?

**Comment by nullchilly** [comment]
I found the problem, you need to turn off `additional_vim_regex_highlighting`, like this:

```
	configs.setup({
		ensure_installed = { "lua", "markdown", "markdown_inline", "bash", "python" }, -- put the language you want in this array
		-- ensure_installed = "all",
		sync_install = false, -- install languages synchronously (only applied to `ensure_installed`)
		ignore_install = { "vim" }, -- List of parsers to ignore installing
		autopairs = {
			enable = true,
		},
		highlight = {
			enable = true, -- false will disable the whole extension
			disable = { "vim" }, -- list of language that will be disabled
			-- additional_vim_regex_highlighting = true,
		},
		indent = { enable = true, disable = { "python", "css" } },
		context_commentstring = {
			enable = true,
			enable_autocmd = false,
		},
	})
```

**Comment by Rishabh672003** [comment]
@nullchilly yeah that fixed it, thank you for your help
