### ISSUE TITLE
Add `vim-illuminate` integration

### ISSUE THREAD

**Issue by latipun7** [catppuccin/nvim#283]
Please add [illuminate highlight groups](https://github.com/RRethy/vim-illuminate#highlight-groups) to the catppuccin integration. Preferably without underline like in default.

Thank you.

**Comment by gotgenes** [comment]
Hi @latipun7. I use vim-illuminate myself. I think since the default vim-illuminate highlight groups don't specify any color changes, I not sure that there's something for catppuccin to do here.

What would you prefer to see?

**Comment by latipun7** [comment]
Hi @gotgenes , thanks for your response. 
I'm on `NVIM v0.8.0-dev-1134-g71e70d0c99`, when I use vim-illuminate, I didn't see background color highlight or something, only the underline. Is that true? While when I see the README of that plugin, it has a nice screenshot which don't have underline and has background highlight.

**Comment by hydroakri** [comment]
just add in catppuccin config
```
integrations = {
                illuminate = true,
                },
```
