### ISSUE TITLE
Add plugin 'Neotest'

### ISSUE THREAD

**Issue by yngwi** [catppuccin/nvim#287]
**Is your feature request related to a problem? Please describe.**
It would be great if you could add support for [Neotest](https://github.com/nvim-neotest/neotest). Out of the box the *Latte* variant currently looks like this:

![image](https://user-images.githubusercontent.com/963440/193254577-989d1b33-e9ba-4875-9400-a2bc913f3e33.png)

The dark variants look better.

**Describe the solution you'd like**
Custom colors at least for the *Latte* variant.

**Comment by nullchilly** [comment]
![image](https://user-images.githubusercontent.com/56817415/193307120-a87c3f05-6eed-4a81-b728-dfe7c293367d.png)

**Comment by yngwi** [comment]
Great, thank you!
