### ISSUE TITLE
Transparent background + integration background

### ISSUE THREAD

**Issue by axieax** [catppuccin/nvim#292]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Ex. I'm always frustrated when [...]. My workflow is like this [...]

Enabling transparent_background as a config option means I'm unable to customise the background for plugin integrations (since the code is usually `config.transparent_background and "NONE" or ...`, e.g. navic).

NOTE: currently what I'm trying to do is to set the background colours for the Navic highlight groups to be the same as my background for `WinBar` (which links to `NormalFloat`).

**Describe the solution you'd like**

Ability to specify a `custom_bg` regardless of transparency.

**Describe alternatives you've considered**

The only way is to completely disable transparency.

**Additional context**

**Comment by nullchilly** [comment]
Only navic has `custom_bg` option

If I understand correctly I just need to remove the transparent check and default `custom_bg` to NONE?

**Comment by nullchilly** [comment]
Ah that sounds good but it will be easier for me to default to cp.none

**Comment by axieax** [comment]
Thanks for the quick fix!
On second thought, it's probably best not to link to Winbar since nvim-navic can also be used as a statusline.
