### ISSUE TITLE
smartyank suppport

### ISSUE THREAD

**Issue by dhruvinsh** [catppuccin/nvim#299]
**Describe the solution you'd like**
[smartyank.nvim](https://github.com/ibhagwan/smartyank.nvim#what-is-smartyank) has yank highlight by default, and it works on [IncSearch](https://github.com/ibhagwan/smartyank.nvim/blob/master/README.md?plain=1#L122) highlight group. So adding support for this would be really great!

**Comment by dhruvinsh** [comment]
https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/editor.lua#L52

i guess, catppuccin already have support for it. https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/editor.lua#L52

i guess adding it to the readme would not hurt.

**Comment by nullchilly** [comment]
We don't add support for plugins that link to the default highlight (And works well) by default to shorten the integration table's length
