### ISSUE TITLE
Bug: Matching colors for export and const next to each other

### ISSUE THREAD

**Issue by btegs** [catppuccin/nvim#314]
### Description

**Scenario 1:**
In the VS Code version of Catppuccin, if `export` and `const` are next to each other, they are different colors. In the Neovim version, they are the same purple color. Has the team looked into doing a different color for the export keyword? Could be handy :-)

Sample JavaScript/TypeScript:
```javascript
export const myVar = 1;
```

**Scenario 2:**
The arguments in a function have a nice red/salmon color to them. Would it be possible if an argument is referenced in the function that the color of that argument variable could match the same color it had in the argument? Another thing that could make it easier for reference.

Sample JavaScript/TypeScript:
```javascript
const myFunction = (data: number): number => {
  const updated = data + 1;
  return updated;
}
```

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.5.1 and Pop!_OS 22.04

### Catppuccin version / branch / rev

v0.2.4

### Steps to reproduce

1. Install colorscheme
2. Enable colorscheme
3. Open up a .js or .ts file

### Expected behavior

1. `export` and `const` should have different colors (like in VS Code version)
2. Color of argument and its reference in the function should be the same color

### Actual behavior

1. Colors are the same between `export` and `const` in the code.
2. Colors do not match between argument and argument reference in the function.

### Minimal config

```Lua
if fn["plug#catppuccin"] then
  require("catppuccin").setup {
    styles = {
      functions = { "italic" },
    }
  }

  lvim.colorscheme = "catppuccin"
end
```

**Comment by nullchilly** [comment]
1. It ain't much but it's honest work: https://github.com/catppuccin/nvim/blob/main/after/queries/typescript/highlights.scm
2. You can use [hlargs.nvim](https://github.com/m-demare/hlargs.nvim)

**Comment by btegs** [comment]
@nullchilly - So are you fixing this in the upstream theme? Or will you still require external dependencies?

**Comment by btegs** [comment]
@nullchilly - Thanks for taking a look into this, looking forward to having this upstreamed in the main code! :-)

EDIT: I see this is a TypeScript patch, but will this also apply to JavaScript? I haven't done a lot of pure JS code lately and wanted to check.
