### ISSUE TITLE
Handle background changes vim-way

### ISSUE THREAD

**Issue by Slotos** [catppuccin/nvim#315]
**Is your feature request related to a problem? Please describe.**

`:h background`
```
	When a color scheme is loaded (the "g:colors_name" variable is set)
	setting 'background' will cause the color scheme to be reloaded.  If
	the color scheme adjusts to the value of 'background' this will work.
```

Colorscheme should use background as input and adjust based on user provided options.
Setting autocommands to react to background changes replicates the built-in functionality in a roundabout way.

**Describe the solution you'd like**

Allow setting dark/light variant in setup, select one based on `vim.g.background` value.

Tokyonight and rose-pine work perfectly well this way. Due to entire colorschemes following the background setting, neither suffer from partial color changes on background change either.
Folke's tokyonight even offers names variants as wrappers around generic background following colorscheme.

**Describe alternatives you've considered**

The one from readme.

**Additional context**

https://user-images.githubusercontent.com/314453/197058044-7c408463-0e13-4c00-b376-c84ab513dd6a.mp4

**Comment by nullchilly** [comment]
https://github.com/catppuccin/nvim#usage-with-set-background So add this to setup table right?

**Comment by Slotos** [comment]
Yes. Something like:

```lua
require("catppuccin").setup({
  flavor = "frappe",
})
```

or, if additional light variants are planned

```lua
require("catppuccin").setup({
  flavor = {
    dark = "frappe",
    light = "latte",
  },
})
```
