### ISSUE TITLE
Changes on integration with bufferline

### ISSUE THREAD

**Issue by LuisxSullivaN** [catppuccin/nvim#32]
Hello! just to bring the discussion of [#22](https://github.com/Pocco81/Catppuccino.nvim/issues/22) in a brand new issue. As I said in my last comment there, bufferline does not support color schemes to override its highlight groups anymore, so the current integration with Catppuccino doesn't work out of the box unless making some tweaks to packer.nvim (if using it). So I suggest to instead of highlight groups provide a lua table containing the desired colors which we can call from bufferline's setup function which is what bufferline expects.

**Comment by Pocco81** [comment]
I was working on a fix actually. I was reading through its source code, and it has some events which Catppuccino can't override.

But still, I'll try to see if I can get something working, if not, then I'll just do what you suggested :)

**Comment by LuisxSullivaN** [comment]
Oh, you were working on this, thanks!

**Comment by Pocco81** [comment]
Yeah I'm starting to think it's kind of impossible to "hijack" bufferline if Akinsho (creator of bufferline) doesn't do something on its side. On the other hand, there are a [quintillion hilights for bufferline](https://github.com/akinsho/bufferline.nvim/blob/master/lua/bufferline/config.lua#L209-L411) to worry about and customize, so PRs are welcomed too ;)

Also, [this event](https://github.com/akinsho/bufferline.nvim/blob/master/lua/bufferline.lua#L983) makes `colorscheme dark_catppuccino` or setting any other catppuccino theme with the `colorscheme` command fail.

Your solution might be the only working solution we have. Yet again, there are a few things I don't quite know if they'll work properly or not, like setting colors dynamically like in the example above.

**Comment by LuisxSullivaN** [comment]
I know right! I'll try to play around with the highlights and see what I can come with, but you're the good one here.

**Comment by Pocco81** [comment]
Off topic but since you like Catppuccino so much I thought I'd let you know to update your conf: 510b5a8cc2271f7e87463ab74adf4bac1da59f11. The current `.load(<flavor>)` will probably be removed in favor of the native `colorscheme` command.

**Comment by LuisxSullivaN** [comment]
You're certainly right dude, I like Catpuccino so much<3 thanks for the news, and good change!
