### ISSUE TITLE
Neorg not supported

### ISSUE THREAD

**Issue by ignamartinoli** [catppuccin/nvim#321]
### Description

[`catppuccin/nvim`](https://github.com/catppuccin/nvim) doesn't completely support **Neorg**'s highlighting.

[This](https://github.com/nvim-neorg/neorg/issues/636) _Issue_ has a preliminary analysis on what is the problem and how it could be solved.

### Neovim version

```markdown
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Gentoo Linux 2.9

### Catppuccin version / branch / rev

catppuccin v2.4.0

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Expected behavior

![image](https://user-images.githubusercontent.com/103866722/197366039-0d04ec77-96d3-439a-b0c6-6332f5aabc3b.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/103866722/197366030-ef082b7e-a5e5-45b0-a680-e2f4ca148d5c.png)

### Minimal config

```Lua
use {
	'nvim-neorg/neorg',
	after = 'nvim-treesitter',
	config = function ()
		vim.cmd [[PackerLoad nvim-treesitter]]

		require 'neorg'.setup {
			load = {
				['core.defaults'] = {},
				['core.norg.concealer'] = {}
			}
		}
	end,
	ft = 'norg',
	requires = { 'nvim-lua/plenary.nvim' }
}
```

**Comment by nullchilly** [comment]
I have improved the highlight groups in treesitter

Also your lazy loading using `ft = 'norg'` doesn't work, I had to remove it:

```lua
use "nvim-neorg/neorg" {
	after = "nvim-treesitter",
	requires = { "nvim-lua/plenary.nvim" },
	config = function()
		require("neorg").setup {
			load = {
				["core.defaults"] = {},
				["core.norg.concealer"] = {},
			},
		}
	end,
}
```

Here is what it should looks like with catppuccin

![image](https://user-images.githubusercontent.com/56817415/197379657-9c7f0b81-408c-4ff1-8fa3-6e887435b1a6.png)

**Comment by ignamartinoli** [comment]
Thanks!
