### ISSUE TITLE
Bug: hlargs.nvim and colors

### ISSUE THREAD

**Issue by btegs** [catppuccin/nvim#324]
### Description

This is related to a prior post where the attempt of the hlargs.nvim plugin was tried. For other themes like darkplus, it seems to work but I wasn't sure if this was a Catpuccin Neovim theme fix or something upstream in hlargs.nvim

Catppuccin:
![hlargs_cat](https://user-images.githubusercontent.com/5166649/197406398-cc0affa8-02db-48aa-bdd3-196aae4f4aa8.png)

Darkplus:
![hlargs_darkplus](https://user-images.githubusercontent.com/5166649/197406410-f410f3a6-cff6-4ca5-9ec9-4870f2f3d49a.png)

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.5.1 and Pop!_OS 22.04

### Catppuccin version / branch / rev

v0.2.5

### Steps to reproduce

1. Install colorscheme
2. Enable colorscheme
3. Open up a .js or .ts file
4. Create a function with arguments and a reference to arguments

### Expected behavior

Colors from argument match reference

### Actual behavior

Colors do not match

### Minimal config

```Lua
{ "m-demare/hlargs.nvim",
  config = function()
    require("hlargs").setup()
  end,
},
```

**Comment by nullchilly** [comment]
Huh that's weird, the second function works but not the first one 🤔 

![image](https://user-images.githubusercontent.com/56817415/197406820-3558d08a-1820-4bdc-879b-f0d6091e2640.png)

**Comment by btegs** [comment]
@nullchilly 

1. I'm using LunarVim and havent tried Catppuccin outside of that. Dunno if that is a cause or not
2. I thought it was the `{ "p00f/nvim-ts-rainbow" }` plugin, but disabling gave the same result

**Comment by nullchilly** [comment]
@btegs Can you try this?

```lua
use "m-demare/hlargs.nvim" {
	after = "nvim-treesitter",
	config = function() require("hlargs").setup() end,
}
```

**Comment by nullchilly** [comment]
With this minimal lvim config it works perfectly fine for me!
```lua
lvim.builtin.treesitter.highlight.enable = true
lvim.plugins = {
  {
    "catppuccin/nvim",
    as = "catppuccin",
    config = function()
      require("catppuccin").setup()
      vim.api.nvim_command("colorscheme catppuccin")
    end,
  },
  {
    "m-demare/hlargs.nvim",
    after = "nvim-treesitter",
    config = function() require("hlargs").setup() end,
  }
}
```

![image](https://user-images.githubusercontent.com/56817415/197407620-e692f547-2279-434b-b1e0-83e5444cfdb7.png)

**Comment by btegs** [comment]
@nullchilly - ill have to try that, was trying various things too

**Comment by nullchilly** [comment]
I am using kitty and yes, it works fine with tmux

**Comment by btegs** [comment]
Trying out Alacritty and iTerm2 on the Mac, hmm probably have a bad config somewhere :-(

**Comment by nullchilly** [comment]
@btegs Maybe you can try this? `:source | PackerSync | PackerCompile`

**Comment by btegs** [comment]
@nullchilly - THAT WORKED!

I was just doing Packer update in the past and the Packer Sync then Packer Compile helped.

**Comment by nullchilly** [comment]
Kindly close the lunarvim issue too, glad it worked 🍡
