### ISSUE TITLE
dim_inactive isn't affecting toggleterm buffer

### ISSUE THREAD

**Issue by WilliamHsieh** [catppuccin/nvim#325]
### Description

The `dim_inactive` feature works great on the default `:terminal` buffer, but it doesn't work in the [ToggleTerm](https://github.com/akinsho/toggleterm.nvim/) buffer. 
Is this the intended behaviour, or how should I solve this problem?

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 22

### Catppuccin version / branch / rev

294bdbe14047590fd03ff97a57ae8f6ffbb98174

### Steps to reproduce

1. nvim
2. `<C-w>v` to open a vertical split
3. `:terminal` in the right split
4. `:ToggleTerm` to open a toggleterm horizontal terminal
5. click on the different split pane, and will notice toggleterm buffer isn't responding to the `dim_inactive` feature

### Actual behavior

1. focus on left pane
![Screen Shot 2022-10-24 at 16 41 35](https://user-images.githubusercontent.com/23206205/197485125-4893f5b7-a0f3-4cdf-8b0c-16f432e3fc06.png)
2. focus on right pane (:terminal)
![Screen Shot 2022-10-24 at 16 41 51](https://user-images.githubusercontent.com/23206205/197485193-40351012-a76a-473f-b8f3-7e743b60fec6.png)
3. focus on bottom pane (:ToggleTerm)
![Screen Shot 2022-10-24 at 16 42 09](https://user-images.githubusercontent.com/23206205/197485260-0934a166-0b35-44d1-9575-783af9e09dd2.png)

### Minimal config

```Lua
local packer_bootstrap = false
local packer_path = vim.fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if vim.fn.empty(vim.fn.glob(packer_path)) > 0 then
  vim.fn.system { "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", packer_path }
  vim.cmd("packadd packer.nvim")
  packer_bootstrap = true
end

require("packer").startup {
  function(use)
    use 'wbthomason/packer.nvim'
    use {
      "akinsho/toggleterm.nvim",
      config = function()
        require("toggleterm").setup()
      end
    }
    use {
      "catppuccin/nvim",
      as = "catppuccin",
      config = function()
        require("catppuccin").setup {
          flavour = "macchiato",
          term_colors = true,
          dim_inactive = {
            enabled = true,
          },

        }
        vim.api.nvim_command "colorscheme catppuccin"
      end
    }

    if packer_bootstrap then
      require('packer').sync()
    end
  end,
}
```

**Comment by nullchilly** [comment]
```lua
require("toggleterm").setup {
	shade_terminals = false,
}
```
