### ISSUE TITLE
Request: Add Docs on What the Color Override Options Corrrespond to

### ISSUE THREAD

**Issue by nezartarbin** [catppuccin/nvim#331]
**Is your feature request related to a problem? Please describe.**
I love the customizability of Catppuccin, but I wish that there was documentation on what each of the color override options (mantle, crust, subtext, etc) correspond to.

**Describe the solution you'd like**
A document explaining what each of the color override options correspond to. This will make it easier to customize the colorscheme.

**Describe alternatives you've considered**
I found the general [Catppuccin style guide](https://github.com/catppuccin/catppuccin/blob/28e08c64c11bf7ceb54ec338bfa84668380c8b93/docs/style-guide.md). Though it is great, it is not specific enough for neovim, and it is inaccurate when it comes to neovim. It describes "surface2" field as one for surface background elements. When I changed it, it affected the comment text color.

**Comment by nullchilly** [comment]
See also: https://www.reddit.com/r/catppuccin/comments/yemffz/code_coloration_style_guide/ityusdc/
