### ISSUE TITLE
nvim-cmp documentation window is not distinguishable

### ISSUE THREAD

**Issue by ssiyad** [catppuccin/nvim#347]
Can we have a much more distinguishable background for nvim-cmp documentation window? It is currently the same as background color

<img width="891" alt="Screenshot 2022-11-19 at 3 23 55 PM" src="https://user-images.githubusercontent.com/28098330/202845277-4b8fec63-7480-4d23-93c7-9624aaa38662.png">

**Comment by ssiyad** [comment]
I guess `CmpDocumentation` and `CmpDocumentationBorder` are related highlight groups. Not sure though

**Comment by ilias777** [comment]
In the catppuccin.setup function I change under the *custom_highlights* section `NormalFloat`, `Pmenu` and `PmenuSel`:

```lua
catppuccin.setup({
    ...
    custom_highlights = function()
        return {
            NormalFloat = { bg = cp.crust },
            Pmenu = { bg = cp.crust },
            PmenuSel = { fg = cp.text, bg = cp.surface0, style = { 'bold' } },
        }
})
```

and it looks like this:
<img width="1491" alt="ctp" src="https://user-images.githubusercontent.com/39212564/202848518-140e3710-87b6-49ae-9414-747040569946.png">

I hope this helps.

**Comment by ssiyad** [comment]
Thanks, but I don't think overriding `NormalFloat` is a good idea. Also `PmenuSel` had no effect. Regardless, it could be a temporary solution. I'd prefer this as the default behaviour though, hence the issue

**Comment by nullchilly** [comment]
Yeah `NormalFloat` bg was set to none to fix this issue https://github.com/catppuccin/nvim/issues/313

**Comment by ilias777** [comment]
If we don't set `NormalFloat`to something than we have this:

<img width="1491" alt="nf" src="https://user-images.githubusercontent.com/39212564/202849616-59847a55-fa0c-4bb2-a837-31e291d71901.png">

You see the documentation in the cmp autocompletion is the same background like catppuccin background.

**Comment by ilias777** [comment]
Yes you are right.

In your screenshot you use borders and so it doesn't matter what color the background completion has.
In my case if I add borders in the completion menu I can't change the background color to the cmp menu and therefore are have no borders.

**Comment by ssiyad** [comment]
Maybe we could add multiple styles for nvim-cmp, like `bordered` and `borderless`?

**Comment by ilias777** [comment]
I don't think it' possible with catppuccin. This are specific settings for cmp.
