### ISSUE TITLE
Highlights for diffs with tree-sitter

### ISSUE THREAD

**Issue by stasjok** [catppuccin/nvim#351]
### Description

`@text.diff.add` and `@text.diff.delete` are linked to `DiffAdd` and `DiffDelete` (groups used in diff mode). I can be wrong, but shouldn't it be linked to `diffAdded` and `diffRemoved` (groups used in diff filetype by default)?

_Syntax_:
![image](https://user-images.githubusercontent.com/1353637/204083178-b9d36d97-5eb9-4f10-a027-66b4b7a671e0.png)

_Tree-sitter_:
![image](https://user-images.githubusercontent.com/1353637/204083198-1712b20e-228c-40d4-b618-7c7682a65cef.png)

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Debian

### Catppuccin version / branch / rev

4393f2a67e672ccd9507758f72fdc33bc921055d

### Steps to reproduce

In order to see it yourself:

1. Update to latest nvim-treesitter.
2. Install gitcommit and diff parser.
3. Try `git commit -v`.

`:hi @text.diff.add`
`:hi @text.diff.delete`

### Actual behavior

`@text.diff.add xxx links to DiffAdd`
`@text.diff.delete xxx links to DiffDelete`

### Minimal config

```Lua
-- `minimal.lua` used for reproducible configuration
-- Open with `nvim --clean -u minimal.lua`

local is_windows = vim.fn.has("win32") == 1
local function join(...)
  local sep = is_windows and "\\" or "/"
  return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local site_path = join(root_tmp, "nvim", "site")
local pack_path = join(site_path, "pack")
local install_path = join(pack_path, "packer", "start", "packer.nvim")
local compile_path = join(install_path, "plugin", "packer_compiled.lua")
vim.opt.packpath = site_path

local function load_plugins()
  local packer = require("packer")
  local use = packer.use
  packer.reset()
  packer.init({ compile_path = compile_path, package_root = pack_path })

  use("wbthomason/packer.nvim")
  use({ "catppuccin/nvim", as = "catppuccin" })
  -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  use("nvim-treesitter/nvim-treesitter")

  packer.install()
end

_G.load_config = function()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("catppuccin").setup({
    flavour = "macchiato",
  })

  vim.api.nvim_command("colorscheme catppuccin")

  require("nvim-treesitter.configs").setup({
    ensure_installed = { "gitcommit", "diff" },
    highlight = {
      enable = true,
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by rogeruiz** [comment]
Hi @stasjok is there a version of the minimal config that includes the other two dependencies you mentioned? There are multiple versions of `gitcommit-parser` for instance.

**Comment by stasjok** [comment]
> Hi @stasjok is there a version of the minimal config that includes the other two dependencies you mentioned? There are multiple versions of `gitcommit-parser` for instance.

A version from nvim-treesitter.

**Comment by nullchilly** [comment]
Reproduced with this comment: `git diff | nvim -`

Before
![image](https://user-images.githubusercontent.com/56817415/204126850-367e27b8-fecb-4f3c-affd-041d9b5acbf6.png)


After
![image](https://user-images.githubusercontent.com/56817415/204126834-0704c0ef-82b5-4fe2-95ac-3c8ef7900fc5.png)
