### ISSUE TITLE
Colors changed after Neovim update

### ISSUE THREAD

**Issue by ls-devs** [catppuccin/nvim#367]
### Description

Hi,
After updating neovim, theme colors changed for no reasons.
It's like something is overriding the theme colors.

Before : 
![Screenshot from 2022-12-11 13-18-10](https://user-images.githubusercontent.com/58638832/206903323-c29214f8-7441-4638-b468-327d021f20b8.png)

![Screenshot from 2022-12-11 13-22-26](https://user-images.githubusercontent.com/58638832/206903250-18530566-fb8d-4956-ae9c-1a2df13b7a3b.png)

After nvim update : 
![Screenshot from 2022-12-11 13-17-45](https://user-images.githubusercontent.com/58638832/206903081-c781811d-36c1-4349-9eec-ffa0ecd5618e.png)

![Screenshot from 2022-12-11 13-22-16](https://user-images.githubusercontent.com/58638832/206903256-045ac0fb-be48-4d32-b547-5ad4a31b3e8d.png)

Also, when saving file, I can see the theme colors kind of flickering, going from previous colors to new overrided colors.
(Ex : colors are white, saving file, colors becomes blue then instantly go green)

### Neovim version

```markdown
NVIM v0.9.0-dev-493+g3dadd3aca
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04.1 LTS

### Catppuccin version / branch / rev

main

### Steps to reproduce

Update neovim to latest version.
Open a file.
See colors overrided.

### Expected behavior

Basic mocha theme.

### Actual behavior

Mocha with overrided colors

**Comment by nullchilly** [comment]
Known issue with the new merged PR https://github.com/neovim/neovim/pull/21100

**Comment by ls-devs** [comment]
Thank you for the clarifications I should have been aware of.

**Comment by augustocdias** [comment]
@nullchilly the PR you're waiting was closed and it seems it was merged with this: https://github.com/neovim/neovim/pull/21393

**Comment by SushritPasupuleti** [comment]
I was migrating from VimPlug to Lazy and this just tripped me, I kept fussing over my termcolors setting in Lua that I moved from vimscript, then it hit me, that I should probably check the issues. So this fix will go live with nvim v0.9?

**Comment by nullchilly** [comment]
@SushritPasupuleti That's the deadline for this issue, yeah

**Comment by SushritPasupuleti** [comment]
> @SushritPasupuleti That's the deadline for this issue, yeah

Thanks for the clarification! Just rolled back to my vimscript config. I can deal with a 24s waiting time on launch, but messed up colors hurt my soul.

Thank you for your amazing work on the theme and its flavours BTW :)

**Comment by nullchilly** [comment]
Side-by-side comparison (lsp semantic is on the right)

![image](https://user-images.githubusercontent.com/56817415/213253663-632f0cb8-b06a-460b-98ed-80c420197432.png)

**Comment by SushritPasupuleti** [comment]
Just updated to latest, it fixed syntax highlighting for everything except `tsx`/`jsx` files.

Here is an example of a tsx file:

![Screenshot 2023-01-19 at 8 25 36 PM](https://user-images.githubusercontent.com/14891901/213475048-fad21736-cf21-4953-9651-89711306aa77.png)

And here is a ts file from the same repo.

![Screenshot 2023-01-19 at 8 25 55 PM](https://user-images.githubusercontent.com/14891901/213475135-bd3df52a-a9ef-4c82-84f6-d047e08476f8.png)
