### ISSUE TITLE
@tag.attribute italic unless in a TSX file

### ISSUE THREAD

**Issue by jackfranklin** [catppuccin/nvim#369]
As per the title - is this on purpose? No worries if not, please close, but I've just [overridden this in my dotfiles](https://github.com/jackfranklin/dotfiles/commit/d6bf94f9f18d9122e854b67cf8fe8b7eaa172ddc) having enjoyed it being italic in other languages.

If this is a bug, I'd be happy to submit a PR :)

**Comment by nullchilly** [comment]
Yes it is a mistake, kindly submit a PR :)

**Comment by jackfranklin** [comment]
Thanks for fixing! This was on my list to PR today - sorry you beat me to it :D
