### ISSUE TITLE
Add option to show ~ character after end of buffer

### ISSUE THREAD

**Issue by primeapple** [catppuccin/nvim#371]
**Is your feature request related to a problem? Please describe.**
By default VIM shows a `~` character after each line after the end of the buffer. This plugin seems to hide that.

**Describe the solution you'd like**
Add an option in the config to show the tilde sign.
This colorscheme: https://github.com/Mofiqul/dracula.nvim solves it with the `show_end_of_buffer` setting.

**Additional context**
No tilde shown :(
![screenshot](https://user-images.githubusercontent.com/35628420/209152934-e5d4a328-302f-42ae-b42b-ebd3313984c3.png)

**Comment by nekowinston** [comment]
Hi there 👋 

As a quick fix, you could currently use this in your setup function:
```lua
catppuccin.setup({
  highlight_overrides = {
    all = function(colors)
      return {
        EndOfBuffer = { fg = colors.surface0 },
      }
    end,
  }
})
```
