### ISSUE TITLE
Make the dependency on nvim-web-devicons optional for the feline integration

### ISSUE THREAD

**Issue by creativecreature** [catppuccin/nvim#374]
I would like to submit a feature request for having the dependency on _ nvim-web-devicons_ optional for the **Feline** integration.

Thanks for a really good plugin and theme!

**Comment by nullchilly** [comment]
https://github.com/catppuccin/nvim/commit/33aac072c713e2e5a87aecf02247441507ecc652 It's done.

![image](https://user-images.githubusercontent.com/56817415/212534518-5253fc4a-34f0-49de-a3b4-de2bf2547912.png)
