### ISSUE TITLE
LspDiagnostics Warning unreadable in light_melya theme

### ISSUE THREAD

**Issue by ashincoder** [catppuccin/nvim#38]
![2021-10-05-110146_1100x129_scrot](https://user-images.githubusercontent.com/83629316/135966070-8625ac89-2411-4202-8a4e-56fc96c3efae.png)

As u can see the warning cannot be read clearly inside the popup window.

Great colorscheme. No complaints :smile:

**Comment by Pocco81** [comment]
By any chance, do you know the name of the exact hi group?

**Comment by ashincoder** [comment]
I think it belongs to this group
LspDiagnosticsFloatingError
LspDiagnosticsFloatingError

**Comment by Pocco81** [comment]
closed because of #44.
