### ISSUE TITLE
[Suggestion] Rename this repo to something indicative of catppuccin

### ISSUE THREAD

**Issue by opalmay** [catppuccin/nvim#385]
Hi,
So I know this goes against the way all the other Catppuccin ports are named, but I think there's a justification here.
This is how my plugin manager (Lazy) showed an update from Catppuccin:
![image](https://user-images.githubusercontent.com/65673442/212402589-f0f760b7-8ada-4a0e-88ed-8e6ad9c95777.png)
This is also how it's shown in the plugins list.
I was genuinely confused as to what plugin that was, and had to go inside the plugin folder (which was of course also named nvim) to find out.
Renaming the repo to `catppuccin.nvim` or `nvim-catppuccin` will be much clearer and match the naming convention of other Neovim plugins.

**Comment by nullishamy** [comment]
```lua
  { 'catppuccin/nvim', name = 'catppuccin' },
```

**Comment by opalmay** [comment]
> ```lua
>   { 'catppuccin/nvim', name = 'catppuccin' },
> ```

It's nice that there's a way to workaround it. But it's not really a solution.
If you're aware enough of the issue to add a workaround in your own config you probably don't really need it.

**Comment by nullishamy** [comment]
It's written in the README for this reason. We use a naming scheme for all of our ports, and breaking it for one when there is already a solution doesnt seem beneficial. We could perhaps make it clearer in the README, and add a line for lazy, though.

**Comment by opalmay** [comment]
> It's written in the README for this reason. We use a naming scheme for all of our ports, and breaking it for one when there is already a solution doesnt seem beneficial. We could perhaps make it clearer in the README, and add a line for lazy, though.

That's fair, didn't notice it was in the README.
Though I'm likely not the only one to have missed it.
