### ISSUE TITLE
Lspsaga breaking changes

### ISSUE THREAD

**Issue by matthewsia98** [catppuccin/nvim#386]
Integration for lspsaga no longer works.

**Comment by lotus-x** [comment]
![image](https://user-images.githubusercontent.com/43782734/212535777-53f979ef-fd0b-46ec-a488-c9b61999cbb7.png)

Btw code actions are unreadable with given colors.

**Comment by matthewsia98** [comment]
Also adding that title is not readable with green background.
I found it best to title_bg to base.

![image](https://user-images.githubusercontent.com/71731492/212818400-c55a8492-25e1-4eea-9b5b-c89244ef4449.png)
![image](https://user-images.githubusercontent.com/71731492/212818547-208dc1db-31c8-4d05-9956-b9698bd648cb.png)

**Comment by nullchilly** [comment]
@lotus-x I sent a PR to upstream lspsaga to fix code action's fg

@matthewsia98 Can't reproduce
![image](https://user-images.githubusercontent.com/56817415/212959162-74727bbf-32ce-4adc-bb46-6ad6d82d4739.png)

**Comment by matthewsia98** [comment]
ah i am overriding the highlight group

**Comment by nullchilly** [comment]
https://github.com/glepnir/lspsaga.nvim/issues/720

All issues was fixed upstream
