### ISSUE TITLE
Broken syntax highlighting in reacttypescript/javascript files.

### ISSUE THREAD

**Issue by SushritPasupuleti** [catppuccin/nvim#387]
Just updated to latest, it fixed syntax highlighting for everything except `tsx`/`jsx` files.

Here is an example of a `.tsx` file:

![Screenshot 2023-01-19 at 8 25 36 PM](https://user-images.githubusercontent.com/14891901/213475048-fad21736-cf21-4953-9651-89711306aa77.png)

And here is a `.ts` file from the same repo.

![Screenshot 2023-01-19 at 8 25 55 PM](https://user-images.githubusercontent.com/14891901/213475135-bd3df52a-a9ef-4c82-84f6-d047e08476f8.png)

Manually setting filetype confirms this theory as well.

_Originally posted by @SushritPasupuleti in https://github.com/catppuccin/nvim/issues/367#issuecomment-1397105780_

**Comment by nullchilly** [comment]
Kindly send the code snippets

**Comment by nullchilly** [comment]
Can't reproduce, please hover over `import` and run `:Inspect`

![image](https://user-images.githubusercontent.com/56817415/213500900-805db2c7-b3b9-4f11-9ff6-700891482dbd.png)

**Comment by SushritPasupuleti** [comment]
I downgraded from nightlies to v8 a while ago, so have no access to `:Inspect` not sure if there an equivalent for it pre v9. Also pulled `v0.2.9`.

Here are the new screenshots with code snippets included:

A `.tsx` file.

![Screenshot 2023-01-20 at 10 20 42 AM](https://user-images.githubusercontent.com/14891901/213619683-412af297-683f-4386-8a0b-76de05fd801a.png)

Setting the `filetype` to `typescript` yields this:

![Screenshot 2023-01-20 at 10 21 59 AM](https://user-images.githubusercontent.com/14891901/213619838-325fbc38-badb-424d-b245-acbfc8fcd116.png)

Code from snippet:

```tsx
import * as React from 'react';
import { Menu, useResourceDefinitions, usePermissions } from 'react-admin';
import BookIcon from '@mui/icons-material/Book';
import ChatBubbleIcon from '@mui/icons-material/ChatBubble';
```

And here is a `.ts` file from the same repo:

![Screenshot 2023-01-20 at 10 23 19 AM](https://user-images.githubusercontent.com/14891901/213619968-6b7e0de9-aa34-4485-ac01-6a3d8856fd86.png)


Code from snippet:

```
require('dotenv').config()
import express, { Express, Request, Response } from 'express';
import cors from 'cors';
import { default as helmet } from 'helmet';
```

I even disabled all other plugins in a different config to test this out. The behaviour was the same. It looks like with `typescriptreact` the `import` highlights use a very light pink where as the `typescript` version uses the purple we are familiar with, this also happens with const and other tokens.

Would be happy to provide any other environment info: 

```bash
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

**Comment by nullchilly** [comment]
Downgraded to 0.8.2, still can't reproduce :<

![image](https://user-images.githubusercontent.com/56817415/213665270-47e6d059-f37a-4dc7-a1f0-4b32c3e28553.png)

Can you install https://github.com/nvim-treesitter/playground and hover over `import` and do `:TSHighlightCapturesUnderCursor`

**Comment by nullchilly** [comment]
From v0.2.8 to v0.2.9 there is no changes that touched the pink highlights

In fact, your color is only achievable using `:TSDisable highlight` for me

[Screencast from 2023-01-21 19-22-08.webm](https://user-images.githubusercontent.com/56817415/213866624-d8ef56e2-afaf-4ddb-be28-8aa020675c37.webm)

In conclusion, it's 100% tsx treesitter not working properly, try to run `:TSInstall tsx` again.

**Comment by SushritPasupuleti** [comment]
> From v0.2.8 to v0.2.9 there is no changes that touched the pink highlights
> 
> In fact, your color is only achievable using `:TSDisable highlight` for me
> 
>  Screencast.from.2023-01-21.19-22-08.webm 
> In conclusion, it's 100% tsx treesitter not working properly, try to run `:TSInstall tsx` again.

I was rewriting my config with Lazy the last 2 days and checking everything that loads manually. Turns out I just forgot to have `tsx` installed in my new Lua config, which was already on the old vimscript config.

Thanks a lot for taking the time to look into it!
