### ISSUE TITLE
Broken dosini highlighting

### ISSUE THREAD

**Issue by Maritsu** [catppuccin/nvim#394]
### Description

After updating catppuccin, the syntax highlighting on dosini (.ini) files is completely messed up or not working at all.
When treesitter is enabled, some keys are highlighted, whereas with treesitter disabled, the file is not highlighted at all.

### Neovim version

```markdown
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

Arch Linux

### Catppuccin version / branch / rev

latest commit (491f0a5)

### Steps to reproduce

1. Open Neovim with catppuccin theme installed (any variant)
2. Open a file with the filetype `dosini` (e.g. a polybar configuration)

### Expected behavior

No changes to syntax highlighting

### Actual behavior

Broken highlighting, messed up comments, incorrect colors in comparison to other formats
![image](https://user-images.githubusercontent.com/66056347/215334671-fa4ca010-028c-45be-b3ca-7c0b0b095d9c.png)
example of another file with correct highlighting: 
![image](https://user-images.githubusercontent.com/66056347/215334794-f4a0fa0c-fdd9-488e-98e0-ea5e2ece69ca.png)

### Minimal config

```Lua
require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'catppuccin/nvim'
  use 'nvim-treesitter/nvim-treesitter'
end)
require('catppuccin').setup()
vim.cmd "colorscheme catppuccin-mocha"
require'nvim-treesitter.configs'.setup({ensure_installed={"ini"}})
```

**Comment by nullchilly** [comment]
treesitter shows the highlight is indeed `@text`. I don't think this is a catppuccin issue?

![image](https://user-images.githubusercontent.com/56817415/215335677-266ebc8c-da19-4c72-b560-92ede43e37d9.png)

**Comment by nullchilly** [comment]
In fact the parser is _really_ new, [nvim-treesitter just added it last week](https://github.com/nvim-treesitter/nvim-treesitter/pull/4189)

**Comment by Maritsu** [comment]
If I disable the treesitter parser, nothing is highlighted though 
![image](https://user-images.githubusercontent.com/66056347/215338733-1213e21b-e0d3-4bcb-849e-f7ab3e370a8c.png)

**Comment by nullchilly** [comment]
Can't reproduce, I am very sorry :<

I tried `TSDisable highlight` and it is highlighted correctly, dunno what's wrong on your side

[Screencast from 2023-01-29 23-17-23.webm](https://user-images.githubusercontent.com/56817415/215345794-2eb1d230-7a80-46ec-942a-76f91ecc4d7d.webm)
