### ISSUE TITLE
Disabled by setting dim_inactive enabled to true

### ISSUE THREAD

**Issue by yuki-yano** [catppuccin/nvim#397]
### Description

SSIA

### Neovim version

```markdown
$ nvim --version
NVIM v0.9.0-dev-3501+g4c90a84c6-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.6.1

### Catppuccin version / branch / rev

8769e767f12f5bf0b7d1250ee067088e7054809a

### Steps to reproduce

Set
```
dim_inactive = {
  enabled = true,
},
```

### Expected behavior

dim_inactive is enabled

### Actual behavior

dim_inactivate is disabled

### Minimal config

```Lua
require('catppuccin').setup({
  dim_inactive = {
    enabled = true,
  },
})
```

**Comment by nullchilly** [comment]
What's your expected behavior?

**Comment by yuki-yano** [comment]
Sorry, I wrote Expected behavior and Actual behavior backwards.
Fixed

**Comment by nullchilly** [comment]
I unfortunately can't reproduce

[Screencast from 2023-02-04 13-22-10.webm](https://user-images.githubusercontent.com/56817415/216752534-aea7385e-6a65-4dc8-a110-fd8cc26ca60e.webm)

**Comment by nullchilly** [comment]
Would you mind sending me the output of:

```
:hi Normal
```

and

```
```
:hi NormalNC
```
```

**Comment by yuki-yano** [comment]
Sorry, as I verbose it, it was overwritten in an unrelated place.
No problem.
