### ISSUE TITLE
Catppuccin breaks alpha-nvim autocmds

### ISSUE THREAD

**Issue by sharpenedblade** [catppuccin/nvim#399]
### Description

When using Catppuccin and alpha-nvim at the same time, alpha-nvim autocmds do not get triggered. alpha-nvim will usually start the `AlphaReady` autocmd, but when using `colorscheme catppuccin`, the autocmd is not run. Interestingly, it does not matter if Catppuccin is installed or `require`-ed, it only matters if Catppuccin is set as the active colorscheme. This does not happen with any other colorschemes.

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
```

### Operating system and version

macOS 13.0.1

### Catppuccin version / branch / rev

main

### Steps to reproduce

1. `nvim -nu minimal.lua`

### Expected behavior

The autocmd is run, so you see `AlphaReady called` in the command window.

### Actual behavior

The autocmd is not run, so you do not see anything in the command window. Commenting out the `colorscheme catppuccin` call makes the autocmd work again.

### Minimal config

```Lua
-- `minimal.lua` used for reproducible configuration
-- Open with `nvim --clean -u minimal.lua`

local is_windows = vim.fn.has("win32") == 1
local function join(...)
  local sep = is_windows and "\\" or "/"
  return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local lazypath = join(root_tmp, "nvim", "lazy")

if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    { "catppuccin/nvim", name = "catppuccin" },
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    { "goolord/alpha-nvim" } 
})

require("catppuccin").setup({
    flavour = "mocha"
})

-- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

local alpha_config = {
    layout = {},
    opts = {}
}
require("alpha").setup(alpha_config)

vim.api.nvim_create_autocmd("User", {
    pattern = "AlphaReady",
    callback = function()
        print("AlphaReady called")
    end,
})

-- COMMENT this to make the autocmd work
vim.cmd.colorscheme('catppuccin')
```

**Comment by nullchilly** [comment]
Unable to reproduce with your minimal config.

Running `:messages` shows `AlphaReady called`

**Comment by sharpenedblade** [comment]
> Unable to reproduce with your minimal config.
> 
> Running `:messages` shows `AlphaReady called` as expected

It might be my system install, I will try in a fresh VM.

**Comment by sharpenedblade** [comment]
It was caused by a borked `luajit` install, reinstalling luajit fixed the problem.
