### ISSUE TITLE
Revert transparent background when `winblend`/`pumblend` option is set?

### ISSUE THREAD

**Issue by jamestansx** [catppuccin/nvim#401]
**Is your feature request related to a problem? Please describe.**
When the `transparent_background` is set, setting `winblend` and/or `pumblend` would cause the bg to set to black. As a result, I have to override all the highlight that is set to `None` (including the integration's colors).

**Describe the solution you'd like**
Perhaps just add a condition to check if `winblend` and/or `pumblend` value is set for the respective highlight color.

**Describe alternatives you've considered**
Manually overriding all the highlight groups that is affected, as what I'm doing now. However, it would be better if I do not need to configure manually as I would need to refer to the source code and find the corresponding color name.

**Additional context**
\-

**Comment by nullchilly** [comment]
Can you explain which highlight groups are affected, this is my cmp with winblend and pumblend and it seems correct to me:

![image](https://user-images.githubusercontent.com/56817415/218249408-9c1312f3-09f4-4de6-99cb-389e9db0aef4.png)

**Comment by jamestansx** [comment]
The affected highlight groups are `NormalFloat` and `Pmenu`. For `dressing.nvim` integration, the `NoiceCmdlinePopup`, `NoicePopup`, etc also been affected. I guess if the plugin does not explicitly configure `winblend` or `pumblend` to 0, then it will show as black (just like how the vim's popup menu turns black).

I will be using this minimal `init.lua` to demonstrate the problem that I am talking about.

<details>
<summary>minimal init.lua</summary>

```lua
vim.o.termguicolors = true
vim.o.winblend = 10
vim.o.pumblend = 10
vim.g.mapleader = " "

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath, })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end
  },
  {
    "nvim-telescope/telescope.nvim",
    cmd = "Telescope",
    version = false,
    dependencies = { "nvim-lua/plenary.nvim" },
    config = true,
  }
})
```

</details>

If I open the popup menu, it will show in black colour. Same goes to the `Lazy` float window.

![image](https://user-images.githubusercontent.com/45304579/218259310-c88586dc-f5b6-4420-bca0-bfaf97da5978.png)
![image](https://user-images.githubusercontent.com/45304579/218259460-6535556e-f9fe-4b51-8a56-57c39132e6c8.png)

However, notice that telescope window does not affect because by default [it sets `winblend` to 0](https://github.com/nvim-telescope/telescope.nvim/blob/203bf5609137600d73e8ed82703d6b0e320a5f36/doc/telescope.txt#L212).

![image](https://user-images.githubusercontent.com/45304579/218259510-5d6d9c09-ec90-44eb-b886-337c9b983d87.png)

**Comment by nullchilly** [comment]
So basically

```lua
O.transparent_float = O.transparent_background and vim.o.winblend == 0
Pmenu = { fg = C.text, bg = O.transparent_float and C.none or C.mantle }
```

Is this the desire behavior?

**Comment by jamestansx** [comment]
Yes, indeed!

**Comment by nullchilly** [comment]
Can you checkout the `blend` branch?

```lua
{ "catppuccin/nvim", branch = "blend" }
```

**Comment by jamestansx** [comment]
Looks good to me 👍🏼

![image](https://user-images.githubusercontent.com/45304579/218317284-0f2044ba-0798-4741-8210-f763c7dcadbc.png)

**Comment by Xuer04** [comment]
> Can you explain which highlight groups are affected, this is my cmp with winblend and pumblend and it seems correct to me:
> 
> ![image](https://user-images.githubusercontent.com/56817415/218249408-9c1312f3-09f4-4de6-99cb-389e9db0aef4.png)
> 
> cc @emxxjnm Any insights on this problem?

I am sorry to comment on this closed issue, but I am curious about how to config the nvim-cmp like yours popup window?
