### ISSUE TITLE
Default colorscheme is not the same

### ISSUE THREAD

**Issue by rebebop** [catppuccin/nvim#415]
### Description

Hi,
I am running the default colorscheme `mocha` but the colors are very different as you can see in the image.
Even if try to use `color_overrides` that just messes up the entire colorscheme and turns it into something else. It seems like the `color_overrides` doesn't have any effect. I tried other flavors but none are applied properly (the colors mismatch). I also tried with `CatppuccinCompile` etc.

<img width="1084" alt="Screenshot 2023-02-21 at 12 45 47" src="https://user-images.githubusercontent.com/1941785/220280749-c3ab52fb-9b8a-4f04-ab98-f8c1bb41f84b.png">

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

### Operating system and version

macOS 13.1

### Catppuccin version / branch / rev

v1.0.0

### Steps to reproduce

load nvim with default colorscheme config

### Expected behavior

Colorscheme should apply the correct colors

### Actual behavior

Colorscheme doesn't apply the correct colors

### Minimal config

```Lua
require("catppuccin").setup({
	flavour = "mocha",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by nyxkrage** [comment]
What terminal are you using? and since I can see you're using tmux, what is the output of `echo $TERM`

**Comment by rebebop** [comment]
Ah just figured out that the problem was `alacritty`. I just set this
```
env:
  TERM: xterm-256color
```
And then configured `tmux` to set the same TERM in the config and everything is all good now. Sorry for the non-issue.

**Comment by nullchilly** [comment]
For any future visitor you need to enable true color support: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
