### ISSUE TITLE
highlight unnecessary keys

### ISSUE THREAD

**Issue by RigottiG** [catppuccin/nvim#428]
### Description

it is highlight incorrect keys like `if, else, then, end`

![image](https://user-images.githubusercontent.com/13246770/224011118-dcf0f567-650a-4eb2-8be6-0af5cf435501.png)

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura
```

### Terminal and multiplexer

tmux 3.3

### Catppuccin version / branch / rev

catppuccin 1.1.0 upgrade with master today

### Steps to reproduce

1. upgrade the catppuccin

### Expected behavior

does not highlight keywords

### Actual behavior

highlight every keyword like `if, else, then`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nullchilly** [comment]
Did I just put those links for nothing...

![image](https://user-images.githubusercontent.com/56817415/224011865-d162159f-3cf7-4c21-8b07-2e9451409044.png)
