### ISSUE TITLE
Dims the display of  inactive conditionally compiled C/C++ code 

### ISSUE THREAD

**Issue by liuyangzys** [catppuccin/nvim#434]
The tokyonight colorscheme can dims the inactive C/C++ code as follow picture
![image](https://user-images.githubusercontent.com/19203871/226891285-5965c9d0-3222-4a07-b4e9-1ed88630b1ec.png)

Catppuccin or other colorschemes can't dims the code.
![image](https://user-images.githubusercontent.com/19203871/226891769-dbf5e6e0-23ce-4037-aad1-16c34194f112.png)

Is it possible to achieve this feature? It should be very helpful for developers of C/C++.

**Comment by liuyangzys** [comment]
Thanks for your hard working.
Should I do some configurations? I just use the default options of catppuccin. And I have pulled the newest version which contain https://github.com/catppuccin/nvim/commit/dda3122d399cd2dbc62d72ebe788a1ae1ffa1ab4 .
However, the problem seems still exist.

**Comment by nullchilly** [comment]
Try updating again, I hope https://github.com/catppuccin/nvim/commit/8c7d98bf4ace401e633bf762f6c2efab706d69b0 fixed it

**Comment by liuyangzys** [comment]
Yes it does work. Thanks a lot!
 
![image](https://user-images.githubusercontent.com/19203871/227121595-4ee98663-471e-4a27-8262-662d207b6ae0.png)
