### ISSUE TITLE
Make Catppuccin consistent across plugins in regards to floating windows

### ISSUE THREAD

**Issue by 89iuv** [catppuccin/nvim#439]
Thank you very much for this wonderful theme that for me it has become the face of neovim.

There are inconsistencies between how floating windows are displayed. 
For the purpose of visualizing the problem i have provided screenshots from telescope, which-key and nvim-cmp.

### Default:
<img width="1496" alt="Screenshot 2023-03-24 at 07 16 15" src="https://user-images.githubusercontent.com/3298487/227434568-1a21b151-ed85-4657-9ed5-e430261cfa03.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 16 44" src="https://user-images.githubusercontent.com/3298487/227434575-291a6e3e-dda4-49e5-b81a-c07763e2471b.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 18 27" src="https://user-images.githubusercontent.com/3298487/227434583-ab5eda95-c8ec-421d-a851-7ee51c4dc9ca.png">

Given the fact that every plugin can choose how to implement the border for it's window this was inevitable but it can be fixed.

### Solution1: with borders
<img width="1496" alt="Screenshot 2023-03-24 at 07 33 44" src="https://user-images.githubusercontent.com/3298487/227435034-d3dbbfde-9810-4e3c-b94c-29aaf9c56127.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 42 17" src="https://user-images.githubusercontent.com/3298487/227435054-fb846111-75ae-4bfc-9f73-e58d922dd3cf.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 42 04" src="https://user-images.githubusercontent.com/3298487/227435043-98b2b60c-dc25-4e25-b9e5-920f5cad6581.png">

### Solution2: no borders
<img width="1496" alt="Screenshot 2023-03-24 at 07 19 47" src="https://user-images.githubusercontent.com/3298487/227435252-71264885-e21d-4579-868d-13bba7e83c3a.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 20 13" src="https://user-images.githubusercontent.com/3298487/227435258-68254ffc-5221-42f1-96db-066f71a842a0.png">
<img width="1496" alt="Screenshot 2023-03-24 at 07 20 39" src="https://user-images.githubusercontent.com/3298487/227435265-93ae04c0-2240-4c25-b0d2-767fc895582f.png">

**Issue with solution2** 
in order to distinguish the floating window from the rest of the application, the background color needs to be somewhere between base and overlay2. 
To close to base and it will blend with the buffer.
To close to overlay2 and it tends to blend with cursor line and comments making it hard to distinguish them.

### The question
What would be a guideline in regards to floating windows and borders in order to have a consistent experience across plugins in Catppuccin?

I would be happy to help with PR to address this inconsistencies.

**Comment by nullchilly** [comment]
Hey, thank you so much for such high effort suggession!

Due to the ad-hoc nature of floating windows implementation in each plugin, I don't think we can provide a consistent experience out of the box for users (Unless we force no border which wouldn't be sane default). I will be going ahead with adding border option for each plugin integration:

# Solution1: with borders

```lua
cmp = {
  enabled = true,
  border = true
}
```

```lua

![image](https://user-images.githubusercontent.com/56817415/227455608-b82885fc-148a-43cf-a377-1a38bbf59eb2.png)

**Comment by 89iuv** [comment]
I like the idea of having a global variable to toggle the borders on | off or auto, and then using plugin specific configuration to override the border per plugin. 
It makes it easy to have a consistent experience while also providing the flexibility to chose and match styles across different plugins.

On issue i still have is in regards to the background color of the floating window.
Here we have the situation where not all floating windows have the same background and if you select to have no border then it will blend with either the file explorer or the editor.

One solution could be to use crust for all floating windows which will ensure that they are visible distinguishable from the file explorer and editor irrespective of the border settings.

What do you thing would be a good color choice for floating window border and floating window background?

**Comment by nullchilly** [comment]
I think we can set bg to NONE or similar with border on

**Comment by 89iuv** [comment]
The conclusion of this issue is that catppuccin is responsible to configure how the floating window border looks but it is up to the user to configure if a floating window has or does not have a border and what type of border characters to use.

While in some situation we "fake" the absence of a floating window border by setting the bg and fg to the same color, we can not "fake" the presence of a border where a border was not added.

The best approach here is to link from the plugin highlights back to the catppuccin highlights so that the settings will propagate from theme to plugin. 
The user can then decide to add or remove the border of the plugin and he can also overwrite the highlight groups of the theme( and propagate the changes to the plugins), or the plugin only.
