### ISSUE TITLE
Airline is not displaying correctly

### ISSUE THREAD

**Issue by Aniamon** [catppuccin/nvim#441]
### Description

![2023-03-27_06-37](https://user-images.githubusercontent.com/98685606/227827178-ef421045-16cc-4dfd-9fb1-39ccc5016705.png)

Colorscheme is not applied correctly when using vim-airline with powerline fonts on

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Terminal and multiplexer

alacritty 0.12.0

### Catppuccin version / branch / rev

catppuccin 1.1.0

### Steps to reproduce

`nvim -u repro.lua`

### Expected behavior

Colorscheme should apply correctly

### Actual behavior

It doesn't

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  "vim-airline/vim-airline",
}

vim.g.airline_powerline_fonts = 1
vim.g.airline_theme = "catppuccin"

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by nullchilly** [comment]
https://github.com/vim-airline/vim-airline/issues/2467

**Comment by Aniamon** [comment]
> [vim-airline/vim-airline#2467](https://github.com/vim-airline/vim-airline/issues/2467)
> 
> Seems like an alacritty issue.

The same occurs with kitty and konsole.

**Comment by nullchilly** [comment]
Can you elaborate the `expected behavior`?

**Comment by Aniamon** [comment]
The characters at the left are not using the colorscheme.

**Comment by nullchilly** [comment]
Ah got it
