### ISSUE TITLE
Support fzf-lua out the box

### ISSUE THREAD

**Issue by jackfranklin** [catppuccin/nvim#447]
I use fzf-lua for file finding and also for searching the document for symbols.

Recently fzf-lua changed to base its highlighting system on treesitter, and as a result out of the box with fzf-lua and this theme, results have no symbol highlighting:
![not-working](https://user-images.githubusercontent.com/193238/230566004-ed6b0bf4-fd6c-446a-8e1d-93b642fd295f.png)

I opened an issue in fzf-lua (https://github.com/ibhagwan/fzf-lua/issues/719) and was told that this is by design, and now:

>  if you wish to have Variable highlighted you’d need to modify or link your current colorscheme @variable highlight group.

I admit to not really understanding what this means - but I am wondering if there is anything that we could ship as part of this theme to make this work out the box? If you think this is possible and can give me some pointers, I am happy to attempt to PR this into Catppuccin if that makes sense.

Thanks!

**Comment by mrtnvgr** [comment]
I can't [reproduce this](https://i.imgur.com/DvG0sfB.png). In what programming language was your file written?

**Comment by jackfranklin** [comment]
The screenshot is Lua, but I also have the same issue in a TypeScript file:

![Screenshot 2023-04-07 130818](https://user-images.githubusercontent.com/193238/230598898-c7476fcd-6359-4ed3-ba1d-508e7eba62af.png)

**Comment by mrtnvgr** [comment]
> The screenshot is Lua, but I also have the same issue in a TypeScript file:
> 
> ![Screenshot 2023-04-07 130818](https://user-images.githubusercontent.com/193238/230598898-c7476fcd-6359-4ed3-ba1d-508e7eba62af.png)

Can't reproduce on Lua files either.

**Comment by mrtnvgr** [comment]
> I opened an issue in fzf-lua (https://github.com/ibhagwan/fzf-lua/issues/719) and was told that this is by design, and now:
> > if you wish to have Variable highlighted you’d need to modify or link your current colorscheme @variable highlight group.

We already have this `@variable` group.
https://github.com/catppuccin/nvim/blob/73587f9c454da81679202f1668c30fea6cdafd5e/lua/catppuccin/groups/integrations/treesitter.lua#L83

**Comment by jackfranklin** [comment]
I think I found the issue. I needed to explicitly turn off symbols in fzf lua: https://github.com/jackfranklin/dotfiles/commit/1bc564acc86a95339f32cc46caaa72a971f019d0

I am not sure why, but now I do have highlighting:

![Screenshot 2023-04-07 140829](https://user-images.githubusercontent.com/193238/230606494-4c83e0fd-b699-4d33-bd51-b5fb61d3424a.png)

Sorry for the noise!
