### ISSUE TITLE
Push Kitty Themes to the Kitty Themes

### ISSUE THREAD

**Issue by pard68** [catppuccin/nvim#45]
Kitty has a themes kitten which sources themes from their themes [repo](https://github.com/kovidgoyal/kitty-themes) and then can automatically fetch the specified theme. I was wondering if you'd be willing/interested in submitting your themes. I'd have already created PRs for them myself, but you created them and I figured you might want the credit for those contributions.

**Comment by Pocco81** [comment]
Closing because this is no longer the right repo for Kitty related issues.
