### ISSUE TITLE
Mini Statusline doesn't seem to match intended Catppuccin colors

### ISSUE THREAD

**Issue by Diablo-D3** [catppuccin/nvim#451]
### Description

Currently, the colors in Mini Statusline are a shade too dark

### Neovim version

```markdown
NVIM v0.9.0-dev-1258+ge789d6529
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

alacritty with tmux

### Catppuccin version / branch / rev

main

### Steps to reproduce

Not configuration dependent, only requires Mini Statusline.

Changing https://github.com/catppuccin/nvim/blob/f078aa49bef4cb9e7b86f07b607c6e98c95b9fb5/lua/catppuccin/groups/integrations/mini.lua#L34-L35 to match

```lua
            MiniStatuslineFilename = { fg = C.text, bg = C.surface0 },
            MiniStatuslineInactive = { fg = C.blue, bg = C.surface0 },
```

Seems to bring it further in line with the treatment other statusline plugins get in Catppuccin according to the README's screenshots.

### Expected behavior

![image](https://user-images.githubusercontent.com/448731/231597374-f163686d-f278-4626-b140-17eb8cde9254.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/448731/231597302-6810c32b-e6fa-4605-9efa-0ac1deb34c6a.png)

### Repro

```Lua
No repro included, see screenshots and included suggested fix.
```

**Comment by nekowinston** [comment]
Which statuslines are brighter than base?
Other programs and integrations do use `mantle` as the main background color:

https://github.com/catppuccin/nvim/blob/5e31d3ce29aa17b7a047b1a0e6b9ce9d6702c511/lua/lualine/themes/catppuccin.lua#L5
https://github.com/catppuccin/nvim/blob/5e31d3ce29aa17b7a047b1a0e6b9ce9d6702c511/lua/catppuccin/groups/integrations/bufferline.lua#L18
https://github.com/catppuccin/nvim/blob/5e31d3ce29aa17b7a047b1a0e6b9ce9d6702c511/lua/catppuccin/groups/integrations/navic.lua#L3-L5

Feline is the odd one out, IMO that one is in the wrong:
https://github.com/catppuccin/nvim/blob/5e31d3ce29aa17b7a047b1a0e6b9ce9d6702c511/lua/catppuccin/groups/integrations/feline.lua#L27-L40

**Comment by Diablo-D3** [comment]
[The screenshot from the README](https://user-images.githubusercontent.com/56817415/213472445-091e54fb-091f-4448-a631-fa6b2ba7d8a5.png) seems to indicate the darkest color on the statusbar (ex: the ubiquitous middle segment that displays the filename) should be one shade brighter than the normal background.

**Comment by nekowinston** [comment]
That screenshot shows Feline, which is the current outlier.
Other Catppuccin ports, such as VSCode, JetBrains, etc. use `mantle`.
