### ISSUE TITLE
Stock setup misses tabs in lightline-bufferline

### ISSUE THREAD

**Issue by xvoidee** [catppuccin/nvim#459]
### Description

When mengelbrecht/lightline-bufferline used with catppuccin/nvim then only 1 active buffer title is displayed. The image shows 2 buffers opened but only 1 is in lightline-bufferline.
![bug](https://user-images.githubusercontent.com/6661882/232449441-eb25b7ea-885f-43e4-a6f1-0bd23a1874aa.png)

### Neovim version

```markdown
NVIM v0.9.0-dev-1347+gfd32a9875
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

Terminator 2.1.1

### Catppuccin version / branch / rev

catppuccin commit fa9a446

### Steps to reproduce

1. Use VimPlug
2. Add mengelbrecht/lightline-bufferline and catppuccin/nvim
3. Open 2 buffers
4. Only 1 active buffer title will be displayed on top

### Expected behavior

2 or more buffers titles visible

### Actual behavior

1 buffer title visible

### Repro

```Lua
Setup is done using vim-script (old way).

Plug 'mengelbrecht/lightline-bufferline'
Plug 'catppuccin/nvim', { 'as': 'catppuccin' }

colo catppuccin-latte
let g:lightline = {'colorscheme': 'catppuccin'}
```

**Comment by mrtnvgr** [comment]
Does it remain on dark catppuccin variants or other colorschemes?

**Comment by xvoidee** [comment]
Thank you for reply! Unfortunately it did not help. I have it in my configuration: https://github.com/xvoidee/nvi/blob/master/config/.cfg.lightline

I figured out if setup has only 3 plugins:
Plug 'itchyny/lightline.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'catppuccin/nvim', { 'as': 'catppuccin' }

But once line
let g:lightline = {'colorscheme': 'catppuccin'}
added to config - tabs disappear and only 1 (active) is visible.

**Comment by mrtnvgr** [comment]
> But once line
> ```
> let g:lightline = {'colorscheme': 'catppuccin'}
> ```
> added to config - tabs disappear and only 1 (active) is visible.

Maybe because this command overrides all lightline settings?

**Comment by xvoidee** [comment]
> Maybe because this command overrides all lightline settings?
Oh no... Yes... It overrides. Thank you!!! I have this config for 4 years and did not see it... You can close the ticket now.
