### ISSUE TITLE
Project rebranding: needing name suggestions

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/nvim#46]
As it was discussed under #44, one of the objectives was to create an org. The project has been growing so much, not only in stars, but also in users. ATM the most accurate way I know how to get this number is by [searching in all of github for `catppuccino`](https://github.com/search?l=Lua&q=catppuccino&type=Code) (because the name is unique enough) and writing down the amount of times it has been mentioned.

People actually love this, that's why we are creating an org for it.

I thought the name was original enough when I first came up with it, but unfortunately it seems like it wasn't. It sucks a lot to say this but we _need_ to rebrand the project [because of this](https://github.com/Pocco81/Catppuccino.nvim/issues/44#issuecomment-955575127). Of course this won't stop the still ongoing development, however the faster we rebrand the project the easier it will be to update the codebase now that it is so small. Doing this further down the road will disrupt web searches, delay deployments, but most importantly, affect active users negatively.

With that said, feel free to leave name suggestions below :)

## Conditions (maybe?)

Since we now have the freedom to choose a name more keen and inline to the current objectives/color palette I think it'd be good to start from there. The only conditions I'd put for the name would be:
+ give cool vibes.
+ not too short, not too long.
+ preferably be a portmanteau (AKA a word that results from blending two or more words, like Catppuccino = Cat + Cappuccino) 
+ don't start with letters people with speech impediments often struggle to pronounce (R, L, Th, ...)

Feel free to ignore what I just said, just properly justify yourself :)

**Comment by Pocco81** [comment]
## Possible topics

+ Space
+ Coffee
+ Animals
+ Calmness
+ Peace of mind


## Words

+ Shanti (peacefulness)
+ Capybara
+ Vaquita
+ Cappuccino


## Possible names

### Following Catppuccino's trend...
+ Katppuccino
+ Ccinodug
+ Puccino
+ Cuppino
+ Cappuccig

### Others
+ Pascota
+ Moscata

**Comment by LuisxSullivaN** [comment]
Hey! Katppuccino feels good! a couple that come to my mind:

*Yukatccino, or Yukatte: A cat with a yukata and a coffee (cappuccino or latte)
![image](https://user-images.githubusercontent.com/29529436/139595466-f4dc9f97-0b0b-4a32-814e-6c68eaa0dfd3.png)
* Spacecat: a cat floating in space (maybe drinking coffee)

**Comment by Pocco81** [comment]
My three favorites are:

+ Katpuccino: cheapest (in a good way) solution, still cool. Name availability is cool too.
+ Yukatccino: different but I like it, if you say it fast enough it sounds like Catppuccino lol.
+ Puccino: shortest of all three, name availability is """good"""" but there is a coffee brand named "Puccino's" and I don't want this to end up like what happened between npm and Kik. So that's a no go.

**Comment by LuisxSullivaN** [comment]
Yeii I agree with that Edit, I'm voting for katppuccino too ❤️. Can't we name the cat just Yu? or you think it's too short?

**Comment by Pocco81** [comment]
>  or you think it's too short?

Perhaps... Ok then, let's brainstorm again! Yum? Yun? Yuni? Yuri? Yera? Yentl? Yoko? Yumi?

**Comment by LuisxSullivaN** [comment]
I stick with Yuka then! it's not that I didn't like it :3

**Comment by Pocco81** [comment]
So, I'm not sure about the name, yet again... I don't know, I like it but it feels like we were overthinking it a lot. Talking with some IRL friends they proposed some names and we ended up coming up with:

+ Catppuccie
+ Cappuccie
+ Puccie

They "radiate" the same energy as Catppuccino and name availability is perfect/near perfect for all of them.

Thoughts?
@cwebster2 @LuisxSullivaN @NTBBloodbath

**Comment by mrjones2014** [comment]
To me Puccie sounds/looks too much like, uhh, a different word 👀

I like Spacecat suggested by @LuisxSullivaN

**Comment by Pocco81** [comment]
The name is cool and all, but personally I feel like SpaceCat is too generic. Like compared to Gruvbox, Monokai, Ayu, Palenight, ... All those are more brandable names. More unique if you will.

But yeah, about... Hadn't thought about that LOL.

**Comment by cwebster2** [comment]
I like katppuccino

**Comment by mrjones2014** [comment]
Yeah I think katppuccino is the lowest-cost change and still keeps the same vibe.

**Comment by Pocco81** [comment]
Ok then, if the idea is to keep the same vibe then what about _**Catppuccin**_? @mrjones2014 @cwebster2

**Comment by mrjones2014** [comment]
They're both one letter off. I personally prefer Katppuccino, but I've got no dog in this fight, so to speak, I've started using my own theme [lighthaus.nvim](https://github.com/mrjones2014/lighthaus.nvim) about a month ago.

**Comment by redxtech** [comment]
> Ok then, if the idea is to keep the same vibe then what about _**Catppuccin**_? @mrjones2014 @cwebster2
> 
> It's closer to the original _**Catppuccino**_ than _**Katppuccino**_, isn't it?

I don't think that this would fit as well. Your goal with the name catppuccino is a warm and cozy vibe, right? I think that is conveyed well with the cats and warm coffee name.

Catpuccin sounds more like monkeys, and don't get me wrong, I do love my monkeys, but I'm not sure how well it fits.

My vote is for Katppuccino., it seems the closest to the original, which was already a good name I think.

**Comment by cwebster2** [comment]
If you still want Cat (with a C) and coffee, you could drop the milk and go for a Catspresso.

**Comment by mattleong** [comment]
CosmicFeline! 

(jk, don't pick that one 😅)

**Comment by Pocco81** [comment]
@mattleong [I did](https://github.com/catppuccin) lol.

(jk, I'm putting that as a placeholder tho)

**Comment by LuisxSullivaN** [comment]
haha what about Catppuccin0

**Comment by Pocco81** [comment]
Oh if we add numbers to the equation then we better go with:

![image](https://user-images.githubusercontent.com/58336662/140595853-dcfb6be6-722b-4b23-9f38-9db7c0b773d5.png)

LOL

**Comment by hackorum** [comment]
I vote for Yakuatte
