### ISSUE TITLE
Diff colors for mocha not visible enough

### ISSUE THREAD

**Issue by erahhal** [catppuccin/nvim#467]
### Description

Nearly impossible to tell what has been diffed for lines that are partially the same.  Example:

![image](https://user-images.githubusercontent.com/1174130/234463370-00741120-faf6-4f5f-ae71-6b704e20be69.png)

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
```

### Terminal and multiplexer

kitty 0.26.2 and tmux 3.3a

### Catppuccin version / branch / rev

catppuccin v1.1.1

### Steps to reproduce

1. get two text files that are the same except for partial line changes
2. run `nvim -d file1 file2`

### Expected behavior

Distinct colors and highlighting for the portions of the lines that are different.  

### Actual behavior

Added and missing lines are relatively visible, using pastel dark red and green colors, but lines with partial changes do not show a difference almost at all.

**Comment by maciejzj** [comment]
I find the color hard to spot too.

This can be mitigated by changing the "DiffText" highlight. I've picked a nice shade of yellowish-blue color (in lua):

`vim.api.nvim_set_hl(0, "DiffText", { bg = "#40403B" })`

**Comment by nullchilly** [comment]
Bumped darken amount from `0.18` to `0.30`

![image](https://user-images.githubusercontent.com/56817415/235294433-f6e02b81-5dcd-4174-891c-473f3b2aa406.png)
