### ISSUE TITLE
UI issue with bufferline padded style

### ISSUE THREAD

**Issue by ansidev** [catppuccin/nvim#469]
### Description

The colorscheme has issue with bufferline padded style.

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

iTerm2 3.4.19 or Neovide 0.10.4 (20230409.125347)

### Catppuccin version / branch / rev

v1.1.1

### Steps to reproduce

1. Use nvim 0.9.
2. Create folder `~/.config/nvim_repro`.
3. Copy the below minimal `init.lua` to nvim_repro.
4. Run `NVIM_APPNAME=nvim_repro nvim`.
5. Waiting for Lazy to install plugins.
6. Exit nvim.
7. Run `NVIM_APPNAME=nvim_repro nvim`.
8. Run `:tabnew` to open new tab page.

### Expected behavior

The space character (included in the padded style) will be rendered properly.

### Actual behavior

![Screenshot 2023-04-29 at 04 33 21](https://user-images.githubusercontent.com/6688235/235258923-5778286d-c9a0-41c5-8946-fcc84d0a9d85.png)

The separator config for the padded style looks like

`{ "" .. " ", "" .. " " }`

However, the style of space characters does not match with triangle characters.

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
  {
    "akinsho/bufferline.nvim",
    dependencies = {
      {
        "catppuccin/nvim",
        name = "catppuccin",
        event = "VeryLazy",
        config = function()
          require("catppuccin").setup{}
          vim.cmd.colorscheme("catppuccin")
        end,
      },
      "nvim-tree/nvim-web-devicons",
    },
    event = "BufEnter",
    config = function()
      highlights = require("catppuccin.groups.integrations.bufferline").get()
      require("bufferline").setup({
        options = {
          mode = "tabs",
          numbers = "ordinal",
          separator_style = "padded_slant",
          show_tab_indicators = true,
        },
        highlights = highlights,
      })
    end,
  },
}

require("lazy").setup(plugins)
```

**Comment by nullchilly** [comment]
Quoting from [:h bufferline](https://github.com/akinsho/bufferline.nvim/blob/a4bd44523316928a7c4a5c09a3407d02c30b6027/doc/bufferline.txt#L198-L199)

* `padded_slant` - Same as `slant` but with extra padding which some terminals require.
  If `slant` does not render correctly for you try padded this instead.

`padded_slant`
![image](https://user-images.githubusercontent.com/56817415/235291562-27dda873-795b-4b4c-a8ed-53d5d3d04e0b.png)

`slant`
![image](https://user-images.githubusercontent.com/56817415/235291588-b967e40c-4f7a-430d-9e46-d622a4891b9a.png)


So just change `separator_style = "padded_slant"` to `separator_style = "slant"`
