### ISSUE TITLE
Invoking vim.lsp.buf.format temporarily removes highlights

### ISSUE THREAD

**Issue by dmmulroy** [catppuccin/nvim#480]
### Description

When invoking `vim.lsp.buf.format`  highlights + italics are temporarily removed. This is only happening for my `catppuccin` theme and it seems to only occur when an lsp is connected and running.

https://user-images.githubusercontent.com/2755722/236859390-2c942267-c6ba-4634-8e85-509f0ec1a9c9.mov

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

kitty: Version 0.27.1 (0.27.1)

### Catppuccin version / branch / rev

main

### Steps to reproduce

1. Install catpuccin and activate the theme
2. Ensure you have an lsp connected and running
3. Run vim.lsp.buf.fmt

### Expected behavior

No highlights/text should change

### Actual behavior

Italics and highlights are removed and reapplied

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  "neovim/nvim-lspconfig",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
require("lspconfig").lua_ls.setup({})
```

**Comment by dmmulroy** [comment]
Ah, thank you this worked! Do you know if it's the intended behavior to reapply highlights in the way that it current is when using the format function?

**Comment by nullchilly** [comment]
It's "intended" for now. However, languages like C/C++ doesn't have this flickering issue, there are efforts upstream to address this :)

**Comment by AnthonyDugarte** [comment]
Not an actual fix, but I disabled formating from `lua_ls` and instead used the one from `null_ls.builtins.formatting.stylua` and the highlights are not being removed now

```lua
null_ls.setup({
        -- ...,
	sources = {
	        -- ...,
		null_ls.builtins.formatting.stylua,
        }
})


-- formatting with: 
	vim.lsp.buf.format({
				async = true,
				filter = function(client)
					return client.name ~= "lua_ls"
				end,
			})
```
