### ISSUE TITLE
nvim-tree items do not respect transparency

### ISSUE THREAD

**Issue by NotAShelf** [catppuccin/nvim#487]
### Description

My terminal features a transparency option, which I have enabled. If I also enable transparency in catppuccin's configuration, the actively selected item will not follow the transparency option.

### Neovim version

```markdown
$ nvim --version      
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

Footerm

### Catppuccin version / branch / rev

57b421ee5f7380f816791fa451e86f213b625ece

### Steps to reproduce

1. Load catppuccin colors with Footerm's transparency enabled
2. observe nvim-tree sidebar, the currently selected file will have a solid background from active palette's background value.

### Expected behavior

The currently selected file has a transparent background.

### Actual behavior

The currently selected item is not transparent.

**Comment by NotAShelf** [comment]
![image](https://github.com/catppuccin/nvim/assets/62766066/0c0bfe50-5291-496c-907a-cd09131f1fcb)

**Comment by nullchilly** [comment]
Try

```lua
vim.o.cursorlineopt = "number"
```

or

```vim
:set cursorlineopt=number
```
