### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/nvim#490]
We should consider creating a new release, [it has been a while](https://github.com/catppuccin/nvim/compare/v1.1.1...main) and merging the next PR(s) might introduce some breaking changes in the syntax highlighting.

**Comment by nullchilly** [comment]
@mrtnvgr Can you do the honor? :)

**Comment by mrtnvgr** [comment]
> @mrtnvgr Can you do the honor? :)

Thank you, I'm very pleased! I will do it tomorrow _(i'm so sleepy right now, sorry)_.

**Comment by nekowinston** [comment]
I think we can move

> Delete `go.mod`

to "Fixes", or even completely drop it, since most users won't be aware of what this implies. I feel like the breaking changes should be concise.

Other than that, LGTM.

**Comment by mrtnvgr** [comment]
> [Any suggestions?](https://github.com/catppuccin/nvim/releases/tag/untagged-505de05bfdd342ad7897)

@nullchilly

**Comment by nullchilly** [comment]
If doesn't exist in the previous release then no need to include it.

**Comment by mrtnvgr** [comment]
> If it doesn't exist in the previous release then no need to include it.

?

**Comment by nullchilly** [comment]
`go.mod` didn't exist in the previous version (`v1.1.0`)

**Comment by nullchilly** [comment]
@mrtnvgr LGTM!
