### ISSUE TITLE
Define `g:terminal_color_0` through `g:terminal_color_15`

### ISSUE THREAD

**Issue by UrNightmaree** [catppuccin/nvim#491]
**Is your feature request related to a problem? Please describe.**
In [Neovide FAQ about Terminal displays fallback-colors](https://neovide.dev/faq.html#the-terminal-displays-fallback-colorsterminal-does-not-show-my-colors), a colorscheme has to define `g:terminal_color_0` through `g:terminal_color_15` in order to have any effects on the terminal. But the Catppucin colorscheme doesn't have that, so the terminal use fallback colors in Neovide.

**Describe the solution you'd like**
Define `g:terminal_color_0` through `g:terminal_color_15`.

**Describe alternatives you've considered**
None.

**Additional context**
Screenshot of the terminal in Neovide.
![image](https://github.com/catppuccin/nvim/assets/71205197/7f997b54-2197-42c4-964e-b27a4b7fcb9a)

**Comment by mrtnvgr** [comment]
Enable terminal colors in your config:
```lua
require("catppuccin").setup({
    term_colors = true,
})
```
