### ISSUE TITLE
Suggestion: add lunarvim instructions

### ISSUE THREAD

**Issue by olsonperrensen** [catppuccin/nvim#497]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Ex. I'm always frustrated when [...]. My workflow is like this [...]
No.

**Describe the solution you'd like**
Include installation for Lunarvim (lvim.colorscheme = 'catppuccin')

**Describe alternatives you've considered**
Looking it up myself.

**Additional context**
LunarVim using lazy loading: 

lvim.plugins = {
  { "catppuccin/nvim", name = "catppuccin" }
}
lvim.colorscheme = 'catppuccin-mocha'

**Comment by nullchilly** [comment]
This is out of scope for this plugin as there are many nvim distributions out there.

Furthermore I think it's pretty easy to search for instructions on [lunarvim.org](https://www.lunarvim.org/)

![image](https://github.com/catppuccin/nvim/assets/56817415/031427c7-b1c1-4504-9119-02c94edb4787)
