### ISSUE TITLE
Better integration with dropbar.nvim

### ISSUE THREAD

**Issue by Bekaboo** [catppuccin/nvim#503]
**Is your feature request related to a problem? Please describe.**

Hi, first of all thanks for all work and devotion in catppuccin!

[dropbar.nvim](https://github.com/Bekaboo/dropbar.nvim) just added a few new highlight groups: `hl-DropBarMenuHoverEntry`, `hl-DropBarMenuHoverIcon`, and `hl-DropBarMenuHoverSymbol`, where the latter two have their default attributes set to `reverse = true` and `bold = true` but are not linked to existing highlight groups, thus need to be set explicitly in the colorscheme plugin to avoid to be cleared when toggling background or switching among colorschemes.

- `hl-DropBarMenuHoverEntry` provides the background of the current entry under cursor/mouse and is linked to `hl-Visual` by default:
    ![image](https://github.com/catppuccin/nvim/assets/76579810/baf88185-fd9d-4b64-b91b-684c927b91ee)
- `hl-DropBarMenuHoverIcon` is used to highlight the icon under the cursor/mouse:
    ![image](https://github.com/catppuccin/nvim/assets/76579810/45b7146e-3320-46ed-bb14-67622d0e3bde)
- `hl-DropBarMenuHoverSymbol` is used to highight the symbols under the cursor/mouse that have texts:
    ![image](https://github.com/catppuccin/nvim/assets/76579810/385e50cb-7850-4c9d-9594-8b654e4dd254)

**Describe the solution you'd like**

Set highlights for `hl-DropBarMenuHoverIcon` and `hl-DropBarMenuHoverSymbol` in catppuccin.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bekaboo** [comment]
Thanks for quick response!

**Comment by nullchilly** [comment]
I think you can add a dropbar's ColorScheme event to automatically restore this?

**Comment by Bekaboo** [comment]
Yeah that's a solution but that will make it impossible to override these hlgroups if users do not like the default settings.

**Comment by nullchilly** [comment]
I mean that's what `:h default` is for right?

**Comment by Bekaboo** [comment]
> I mean that's what { default = true } is for right?

Didn't realize that `default=true` can be used to prevent setting an existing hlgroup, I only knew that is can be used to set hlgroups that allows overriding before. Thanks for your kind suggestion!
