### ISSUE TITLE
Cannot override the Pmenu background color.

### ISSUE THREAD

**Issue by bitwombat** [catppuccin/nvim#513]
### Description

I am trying to override the Pmenu background color because it is nearly-black-on-black by default:
![image](https://github.com/catppuccin/nvim/assets/3937658/683d2b4e-7fdb-49f3-b18c-c04b9c18d96e)

For simplicity, I'm doing it from the vim command line. So `:hi Pmenu guibg=#FF0000` affects both the wildmenu background _and_ the diagnostics menu if I'm using colorscheme `blue`. However, with `catppuccin`, it only affects the wildmenu background.

See video: 
https://github.com/catppuccin/nvim/assets/3937658/2bd6ae3b-7f0e-4472-b748-f0eb71aeb1df

Note this does not work with a `custom_highlights` function either.

### Neovim version

```markdown
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

kitty 0.27.1

### Catppuccin version / branch / rev

ad63055

### Steps to reproduce

1. `:colorscheme catppuccin`
2. `:hi Pmenu guibg=#FF0000`
3. `:lua vim.diagnostic.open_float()` while in some code that has an LSP diagnostic message.

### Expected behavior

Expecting  `:hi Pmenu guibg=#FF0000` to change the color of the Diagnostic/Pmenu window like it does with other color themes.

### Actual behavior

Diagnostic/Pmenu window does not change color.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by bitwombat** [comment]
Note: repro.lua not useful for reproducing because it doesn't have and LS's and related plugins. If the issue is unclear, I'll create that.

**Comment by mrtnvgr** [comment]
LSP Diagnostics popup uses `NormalFloat` group:

```
:hi NormalFloat guibg=#FF0000
```

**Comment by mrtnvgr** [comment]
`blue` colorscheme links `Pmenu` to `NormalFloat`

**Comment by mrtnvgr** [comment]
`blue` colorscheme links `Pmenu` to `NormalFloat`

**Comment by nullchilly** [comment]
![Screenshot_2023-06-20-10-15-29-560_com termux-edit](https://github.com/catppuccin/nvim/assets/56817415/b75bb099-d68b-47f9-8963-a141ea168118)

**Comment by bitwombat** [comment]
> `blue` colorscheme links `Pmenu` to `NormalFloat`

Arg! Well, that explains it. `slate` and one other built-in theme I tried must also link them (same behavior)... so I figured it must be a catppuccin thing.

Thanks team, much appreciated. And thanks for providing/maintaining this cool theme!
