### ISSUE TITLE
Error when setting term colors

### ISSUE THREAD

**Issue by LuisxSullivaN** [catppuccin/nvim#52]
Hey! when I install catppuccin and set `term_colors` to `true` I get the following error:
`acker.nvim: Error running config for Catppuccino.nvim: /Users/luis/.config/nvim/lua/plugins/catppuccin.lua:55: Vim(lua):E5108: Error executing lua ...ker/start/Catppuccino.nvim/lua/catppuccin/utils/util.lua:120: attempt to index local 'clrs' (a nil value)`

**Comment by Pocco81** [comment]
Thanks for letting me know! https://github.com/catppuccin/nvim/commit/72f0eddaae65dafc66565e0462adbfd11c74c6bb fixes this.
