### ISSUE TITLE
bg error(from prev commit)

### ISSUE THREAD

**Issue by geril2207** [catppuccin/nvim#523]
### Description

Error starting from `b032ced` commit. My config https://github.com/geril2207/nvim-config
E5113: Error while calling lua chunk: vim/_editor.lua:0: /Users/ilya/.config/nvim/init.lua..nvim_exec2() called at /Users/ilya/.config/nvim/init.lua:0../Users/ilya/.local/share/nvim/lazy/catppuccin/colo
rs/catppuccin.vim, line 1: Vim(lua):E5108: Error executing lua /Users/ilya/.cache/nvim/catppuccin/macchiato:0: Invalid 'bg': expected String or Integer
stack traceback:
        [C]: in function 'nvim_set_hl'
        /Users/ilya/.cache/nvim/catppuccin/macchiato: in function 'f'
        ...local/share/nvim/lazy/catppuccin/lua/catppuccin/init.lua:137: in function 'load'

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

iterm2

### Catppuccin version / branch / rev

last

### Steps to reproduce

Check my config https://github.com/geril2207/nvim-config, config theme in /after/plugin/theme.lua

### Expected behavior

Should work

### Actual behavior

Throws errors

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nullchilly** [comment]
I reverted the commit for now.
