### ISSUE TITLE
native_lsp won't affect DiagnosticUnderline* hl-groups on nightly

### ISSUE THREAD

**Issue by rebelot** [catppuccin/nvim#53]
Hi, since neovim nightly changed a few things regarding diagnostics, it would be better to refactor the `native_lsp` integration into a more general `diagnostic` as I think this is the way things are going. This will also transparently apply the same gui and guisp styles for all diagnostics (`Spell*`, `DiagnosticUnderline*` and legacy `LspDiagnosticsUnderline*`)

Also, for some reason DiagnosticHint seems to be unset:
<img width="337" alt="Screenshot 2021-11-12 at 20 11 51" src="https://user-images.githubusercontent.com/36300441/141522149-15a99773-ea21-4e8a-bfd2-c6cc864288f0.png">

I have this in my catppuccin config to solve the issue temporarily.
```lua
    vim.cmd('hi! link DiagnosticHint String')
    vim.cmd('hi DiagnosticUnderlineError gui=undercurl guisp='..require"colors".get_color('DiagnosticError', 'fg'))
    vim.cmd('hi DiagnosticUnderlineWarn  gui=undercurl guisp='..require"colors".get_color('DiagnosticWarn', 'fg'))
    vim.cmd('hi DiagnosticUnderlineInfo  gui=undercurl guisp='..require"colors".get_color('DiagnosticInfo', 'fg'))
    vim.cmd('hi DiagnosticUnderlineHint  gui=undercurl guisp='..require"colors".get_color('DiagnosticHint', 'fg'))
```

Awesome colorscheme btw ;)

**Comment by Pocco81** [comment]
thanks for letting me know :) it should be working now.
