### ISSUE TITLE
Overriding highlight groups set by integrations

### ISSUE THREAD

**Issue by Subjective** [catppuccin/nvim#533]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying to override some highlight groups set by the telescope and leap integrations, but it seems like the highlight groups created by integrations are set after the user-defined groups.

**Describe the solution you'd like**
I would like to override custom highlight groups in by providing a table to the `custom_highlights` config option and have them replace the ones set by integrations.
```lua
custom_highlights = function(colors)
  return {
    LspInlayHint = { style = { "italic" } },
    -- lightspeed-style highlighting for leap
    LeapMatch = { fg = colors.text, bold = true },
    LeapLabelPrimary = { fg = colors.pink, bold = true },
    LeapLabelSecondary = { fg = colors.blue, bold = true },
    -- hide telescope results title
    TelescopeResultsTitle = { fg = colors.mantle },
  }
end,
```

**Describe alternatives you've considered**
I've considered having an autocmd to set the highlight groups after catppuccin loads, or disabling the integration and manually setting all of the telescope highlight groups myself, but I would prefer being able to just override a few specific groups via `custom_highlights`. 

Thanks!

**Comment by nekowinston** [comment]
This should already work if you're using `highlight_overrides` :thinking: 

```lua
highlight_overrides = {
  all = function(colors)
    return {
      LspInlayHint = { style = { "italic" } },
      -- lightspeed-style highlighting for leap
      LeapMatch = { fg = colors.text, bold = true },
      LeapLabelPrimary = { fg = colors.pink, bold = true },
      LeapLabelSecondary = { fg = colors.blue, bold = true },
      -- hide telescope results title
      TelescopeResultsTitle = { fg = colors.mantle },
    }
  end,
},
```

**Comment by nullchilly** [comment]
`custom_highlights` is alias of `highlight_overrides.all` so there shouldn't be any difference

![image](https://github.com/catppuccin/nvim/assets/56817415/5c177237-93ab-400e-92ef-972b4213bcbd)

Can you provide more context, i.e. your telescope config

**Comment by Subjective** [comment]
It works when I set telescope integration to true:
<img width="914" alt="image" src="https://github.com/catppuccin/nvim/assets/56745535/829dd738-2009-42b3-967a-43a189a3debb">

But not when I enable the "nvchad" style:
```lua
opts = {
  integrations = {
    telescope = { enabled = true, style = "nvchad"}
  }
}
```
<img width="906" alt="image" src="https://github.com/catppuccin/nvim/assets/56745535/65524a41-5271-4af3-b93b-2683ce4b071d">

**Comment by Subjective** [comment]
As for my telescope config, I don't think it makes a difference, but the issue persists with a fairly minimal config:
```lua
return {
  "nvim-telescope/telescope.nvim",
  dependencies = {
    { "nvim-telescope/telescope-fzf-native.nvim", enabled = vim.fn.executable "make" == 1, build = "make" },
  },
  cmd = "telescope",
  opts = {},
  config = function(_, opts)
    require("telescope").load_extension("fzf")
  end
}
```

**Comment by nullchilly** [comment]
`custom_highlights` works similar to `:highlight` which extends the current highlight group. You should override the bg value too

```lua
TelescopeResultsTitle = { fg = colors.mantle, bg = colors.none }
```

**Comment by Subjective** [comment]
Thank you so much!
