### ISSUE TITLE
missing color in lazygit.nvim

### ISSUE THREAD

**Issue by mbriggs** [catppuccin/nvim#54]
Hey :)

I have been using Catppuccino for awhile, just switched to Catppucin. Something I noticed is a color seems to have disappeared that is used in [lazygit](https://github.com/kdheepak/lazygit.nvim) that was there before the switch

![image](https://user-images.githubusercontent.com/89260/141603414-c6e48b11-e580-480f-885e-bf3322b2329d.png)

**Comment by Pocco81** [comment]
Huh, that's weird, it looks fine on my side:

![lazygit](https://user-images.githubusercontent.com/58336662/141603825-ebf0e8b1-9b09-487d-868d-a60986d87d3b.png)

1. Which branch are you using? if it's not `main` then switch to that one
2. If switching branches didn't help, could you share your Catppuccin config?

**Comment by mbriggs** [comment]
i tried explicitly adding main to packer, which didnt seem to work. I then tried removing lazy loading of lazygit, and it worked o.O So i tried adding lazy loading back, and it is still fine.

No clue what solved this, but it seems to be fine now :) Thanks for the great theme, sorry for bugging you
