### ISSUE TITLE
lualine contrast

### ISSUE THREAD

**Issue by hackorum** [catppuccin/nvim#55]
Hey @Pocco81 as you asked in the VapourNvim issue I will be very happy to team up with you. I am trying to make a rice with this colorscheme but there is just one small issue that there is very less contrast in lualine. It would be great if you could make the text to a lighter color or add a light background to the text. Here is a screenshot:

![Screenshot 2021-11-13 at 9 20 50 AM](https://user-images.githubusercontent.com/70092545/141604795-cab01a48-ff86-400f-9173-45336b0dfb3b.png)

**Comment by Pocco81** [comment]
Sorry about that! The issue was originally reported by @LuisxSullivaN [here](https://github.com/catppuccin/nvim/issues/51#issuecomment-963789887), I just haven't had time to fix it. I'll do that ASAP :+1:

**Comment by hackorum** [comment]
Great!
