### ISSUE TITLE
[Request] Point-out to commit of last good version of neon-latte

### ISSUE THREAD

**Issue by kryzar** [catppuccin/nvim#56]
Pocco,

First of all, I truely admire the effort and transparency you put into this project.

As far as I'm concerned, I don't like the new palette that much and would very much prefer to keep using the *neon-latte* flavor. I hadn't followed #44 closely and I didn't realize that *neon-latte* was removed during the remaster. Could you please add a line to the README that points out to the commit corresponding to the last good version of *neon-latte* (both palette and docs, somehow using `colorscheme neon_latte` was not working for me, so I had to manually configure the theme and I don't remember how (that's on me)).

Thank you and have a nice week-end.

**Comment by Pocco81** [comment]
Oh don't worry about not liking the remastered version, I was expecting that and I actually remembered mentioning that on the dev discussion. Pink, magenta, and fuchsia are not _industry standards_ when talking about the colorscheme marketplace, which is dominated by, you know: Gruvbox, onedark, Monokai, Nord... All of them having bluish and grayish colors as their bases.

I actually promised to fork the project before the remastered version was merged, which I didn't do, so that's on me :)

AFAIK the `dev` branch still has a working Neon Latte theme. Both docs and codebase. I was actually thinking about deleting it yesterday lol. I'll move that into a `old-catppuccino` branch and point it out on the README 👍

**Comment by kryzar** [comment]
Thanks a lot for doing this.

Oh I don't mind discussing this at all. First, I don't like the green. I find it to be very cold, unappealing, and out of tone with the overall warthm of the theme and its purple-ish tone.

I began my journey with purple-ish colorschemes with the very good [embark](https://embark-theme.github.io/). I discovered your theme a few weeks ago, and immediatly tried the neon-latte version because to me, it had the personnality of embark while being warmer --- embark still feels a bit cold, like Nord for example. But neon latte, with its purple background and its very balanced yellow (replacing the white), feels so cosy... To me, it creates desire, it helps me stay focus because it will not bore me out. But it does this while not distracting me from what matters: the code I am writing or reading.

By contrast, the new palette (and especially the green) seems a bit dull to me, I think it is way closer to the goto themes you mentioned than the previous flavor. And sadly, in this case I would rather go with one of the goto themes, because thay are much more maintained (even though you are putting it a *lot* of work) and their fine-tuning will probably be superior. 

I would be pleased to pursue this discussion with you. I am just very happy to find someone that takes colorschemes as seriously as you do. I always wanted to do mine, but I do not underestimate the work, and I am more than happy to have quality people taking care of this thing for me.

A few further remarks:
> Why did you choose to have only one flavor? Would it be too much work to maintain multiple flavors?
> On the new README, the first picture is a bit useless, I think. It's nice, yes, but it does a worse job at showcasing your colorscheme than a well-chosen screenshot.

**Comment by parker789** [comment]
I came here to ask this same question, but for the Soft Manilo flavor.  I find the new theme to be particularly dark, with a lack of contrast between the different colors. It's hard for my eyes to pick up. I really love what you've done here, especially with the integration with other major plugins in the neovim community, so I'd really like to start using your theme! 

With that being said, I have no idea the effort it would take to maintain multiple flavors and give us the integrated functionality for each, but figured I'd ask. Thanks again for the work either way.. how my eyes perceive things aren't an indication of anything actually wrong!

**Comment by cwebster2** [comment]
After trying out the remaster for a week or so, I'm likely going back to the original catppuccino colorscheme.  The remaster has greatly reduced contrast and that contrast is what brought me to catppucion in the first place.

**Comment by Pocco81** [comment]
First off, thank you everyone for the great feedback! I really wish these things were said under #44 (which is the main dev thread), but anyhow, I haven't released Catppuccin yet, so improvements/ideas are welcomed :)

Again, thanks for the suggestions. Most the of the questions asked here were answered in the dev thread, but still, I don't want people trying to find what they want there, so I'll probably sum things up in a different comment. With that said, I want to tackle each _sub issue_ individually for the time being and eventually, in the future, we'll see if everyone's issues with the theme were fixed.

Talking a bit more about actual development, I've gathered the various ideas, features and _fix requests_ (thanks @kryzar!) under the [**Initial Release** project](https://github.com/catppuccin/catppuccin/projects/1) at the main repo. I'll be testing things, so to speak, here, in the nvim port under the [`dev-rc`](https://github.com/catppuccin/nvim/tree/dev-rc) branch.

So far here is what I've got (ignore the blue lines, those are from [tmux](https://github.com/catppuccin/tmux)):

![image](https://user-images.githubusercontent.com/58336662/142109690-68c2f22f-88b6-4aec-b7b2-7233c0bb3461.png)

The one in the top-left corner is this new _remastered remaster_! the one below it is the current one that we have in the `main` branch. The ones to the left are other themes, just to have a better point of comparison.

It's **not** finished yet. I'm currently tackling the _sub issues_ in the `doing` section [here](https://github.com/catppuccin/catppuccin/projects/1).

### More screenshots

Here is a closeup:

![image](https://user-images.githubusercontent.com/58336662/142127401-78aaa777-3c90-41d2-96f7-67f236fad46a.png)

Here is a side-by-side comparison with the current `main`:

![image](https://user-images.githubusercontent.com/58336662/142127972-4e72bf30-ab7e-4b01-858b-f9c9a5ffc5a5.png)

**Comment by Pocco81** [comment]
> On the new README, the first picture is a bit useless, I think. It's nice, yes, but it does a worse job at showcasing your colorscheme than a well-chosen screenshot.

Of course I'm going to remove that soon. That image is a placeholder that I put on every port for when I don't have promo screenshots yet, which is something I'm [working on](https://github.com/VapourNvim/VapourNvim/issues/39).

> are you saying what's now in main was the remastered version, and it's not complete yet?

Yes. As I said, I haven't released anything yet. You can follow the things I'm working on [here](https://github.com/catppuccin/catppuccin/projects/1).

> I am just very happy to find someone that takes colorschemes as seriously as you do. I always wanted to do mine, but I do not underestimate the work, and I am more than happy to have quality people taking care of this thing for me.

Thanks man, I appreciate it!

In addition, [this](https://github.com/catppuccin/nvim/issues/44#issuecomment-947669665) reply to @LuisxSullivaN and the discussion that unfolded answers most (if not all) of the rest of the questions.

**Comment by kryzar** [comment]
Dear Pocco, thanks a lot for this clarity and openness. 

> First off, thank you everyone for the great feedback! I really wish these things were said under #44 (which is the main dev thread)

Sorry for this. I arrived a bit late to the party, and everything seemed decided. And furthermore, I would not have intervened because the direction you chose seemed to different, and I respect that.

I like the remastered-remaster a lot better. Colors are more pastel, which gives a bit of the warmth I like. The green is better, but it remains a bit dull *to me*. For exemple, in neon latte, the green was a bit poppy, which made sense because it was used for string, which are a totally different kind of object / syntax than the rest of the code.

I still like Neon latte more, because of the yellow replacing the white. But since this is *your* theme, don't feel at all the need to do like *I* wish. Stay true to your vision. And I am still glad to be able to use the old flavor. That being said, I will install the remastered-remaster asap, and I will frequently change with the old neon-latte, to compare. This is all very exciting!

P.-S.: What is the bottom-right theme? The blue is very beautiful.
P.-S.: I insist, please don't do too much to comply with my critics. I really *really* think that this is your project and that you have the right to do how you want it.

**Comment by hackorum** [comment]
> What is the bottom-right theme? The blue is very beautiful.
It is indeed a very beautiful colorscheme. It is called rosé pine

**Comment by kryzar** [comment]
Thanks!

**Comment by Pocco81** [comment]
Awe thanks @kryzar for the feedback and the kind words once more! 

> Sorry for this. I arrived a bit late to the party, and everything seemed decided 

Well not yet. As you can see I haven't even released v0.1.0 yet + it's better to make all this tweaks before the project grows more. 

> I like the remastered-remaster a lot better 

I just pushed some things feats too ;) 

> Stay true to your vision 

I will. But I'm always welcoming recommendations and such. 

> I insist, please don't do too much to comply with my critics. I really really think that this is your project and that you have the right to do how you want it. 

I too insist, since this is a project that I _want_ and _expect_ people to use, making it very opinionated would be the least smart idea. You have awesome ideas and like so I'm taking them into consideration; not necessarily for complying with your critics but because it's likely that other people feel the same that you do and rethinking how we have structured the project so far is important.

**Comment by Pocco81** [comment]
Awe thanks @kryzar for the feedback and the kind words once more! 

> Sorry for this. I arrived a bit late to the party, and everything seemed decided 

Well not yet. As you can see I haven't even released v0.1.0 yet + it's better to make all this tweaks before the project grows more. 

> I like the remastered-remaster a lot better 

I just pushed some things feats too ;) 

> Stay true to your vision 

I will. But I'm always welcoming recommendations and such. 

> I insist, please don't do too much to comply with my critics. I really really think that this is your project and that you have the right to do how you want it. 

I too insist, since this is a project that I _want_ and _expect_ people to use, making it very opinionated would be the least smart idea. You have awesome ideas and like so I'm taking them into consideration; not necessarily for complying with your critics but because it's likely that other people feel the same that you do and rethinking how we have structured the project so far is important. 

> P.-S.: What is the bottom-right theme? The blue is very beautiful. 

Huh, contrary to you, the blue is my least favorite color from Rose's palette lol. It's a bit too dull compared to, for instance, Embark's blue, which is more vivid and is overall really gorgeous!

**Comment by kryzar** [comment]
Ok!

**Comment by parker789** [comment]
Yea, sorry as well - I just jumped on board the Catppuccino ride when I heard about the theme on a reddit post, so I wasn't around to give any feedback for dev-remaster either. I like the updated images though! Awesome work :) Looking forward to the 0.1.0 release.

**Comment by Pocco81** [comment]
@parker789 @kryzar @hackorum @danymat thoughts?

# Palette

![image](https://user-images.githubusercontent.com/58336662/143660949-e7e0ccd0-1f78-4e17-98db-b7f99259c874.png)
![image](https://user-images.githubusercontent.com/58336662/143660959-66490115-3fc0-4963-8c9b-16433b806637.png)

# Examples

![image](https://user-images.githubusercontent.com/58336662/143660359-99660d95-c7d0-47fd-9525-73eb700a7ca0.png)
![image](https://user-images.githubusercontent.com/58336662/143660568-86cc895c-8826-4d1a-89b2-d77bedefe7ff.png)



Although I "finished" it very recently I've been using it as my daily driver and it looks very good under any light condition. I've also ported it to Obsidian (Markdown note-taking app) and the "base" colors have a better balance now.

Overall it's more contrast-y and not too dark.

**Comment by hackorum** [comment]
Wow! This looks so good! I love it

**Comment by Mangeshrex** [comment]
This looks great. The thing I like most in this is that the background and thr foreground colors match very much. It isn't like the background is dull and the foreground is light. The colors look very nice from all the views. + I would like to know the second pallette you have put in the message.

**Comment by LuisxSullivaN** [comment]
Hey! I like it so much! those are warm colors and make a nice contrast.

Do you have a link to wallpaper btw?

**Comment by Pocco81** [comment]
@LuisxSullivaN I'll publish that one and others in a separate repo (probably now).

**Comment by parker789** [comment]
@Pocco81 this looks awesome! I'll have to try it out and see how things feel with some actual work.

**Comment by Pocco81** [comment]
@parker789 keep in mind I'm still making some final touches, so it might not look exactly like in the screenshot when you try it.

**Comment by danymat** [comment]
I love the new palette !!

**Comment by Pocco81** [comment]
@LuisxSullivaN Wallpapers: https://github.com/catppuccin/wallpapers

**Comment by kryzar** [comment]
Peach and blue look amazing, congrats @Pocco81!!! I will try this version asap.

I've been using commit `d262f03` for a week and although I still prefer the yellow of *neon_latte* (it's mostly dark where I leave in this season, so it's easier on the eye, and this is probably the game killer for me), there are things I much prefer in `d262f03`:
- the color of the selected text (visual mode) is pink text over darker-pink, it is very beautiful and --- thanks to the higher contrast --- is more readable than the corresponding color in *neon_latte*;
- in the *kitty* conf, the green cursor is better than the yellow cursor because it has more contrast.

However, a thing that I think you should bring to the new version, the comments are much darker in *neon_latte* and therefore they interfere less with the semantic code. This is particularly nice in Python, where PEP8 tells you not to add blank lines (most of the time), and instead I add small title-comments; the dark comments make this visually un-bloated.

**Comment by Pocco81** [comment]
- [x] Improve yellow's contrast with the background
- [x] Blend comments (gray) more with the background

For the yellow:

Current Yellow:
![image](https://user-images.githubusercontent.com/58336662/143957194-d5a93ba6-4fdb-42a0-a7f4-742e237534b0.png)

Neon Latte's yellow:
![image](https://user-images.githubusercontent.com/58336662/143957230-0033ba98-f1ec-44e0-a61d-4aa477ff817a.png)

Intermediate one:
![image](https://user-images.githubusercontent.com/58336662/143957274-a50ed79e-a309-445a-a475-a2bc46136203.png)

## Changes:

The yellow: (the one in the middle)

![image](https://user-images.githubusercontent.com/58336662/143957315-0d4b12bb-f18e-4cf0-96f4-4a5d37a287d6.png)

The gray: (the one in the right-hand side)

![image](https://user-images.githubusercontent.com/58336662/143960967-5a4de79b-5fd0-4241-bbb5-1765e91f6502.png)

> there are things I much prefer in d262f03:

I think you referenced the wrong commit there? AFAIK there is no _pink highlighting_  on Neon Latte lol

**Comment by kryzar** [comment]
> I think you referenced the wrong commit there? AFAIK there is no pink highlighting on Neon Latte lol

My mistake! I was using `dev-rc` and both things I mentioned are better in `dev-rc` than in *neon_latte* (as far as I'm concerned); I edited my comment.

- For the yellow, I'd say the intermediate one has more personality than the current one while being more appropriate to `dev-rc` than the one from *neon_latte*.
- For the comments, I'd say the darker the better.

**Comment by Pocco81** [comment]
To conclude this discussion, a Reddit post of mine for the v0.1.0 release: https://www.reddit.com/r/neovim/comments/r9619t/catppuccin_v010_a_midtone_dark_theme_for_neovim/
