### ISSUE TITLE
Integration of nvim-ufo

### ISSUE THREAD

**Issue by testinfected** [catppuccin/nvim#577]
It would be great to add an integration to [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo)

It defines the following highlight groups:

> hi default UfoFoldedFg guifg=Normal.foreground
> hi default UfoFoldedBg guibg=Folded.background
> hi default link UfoPreviewSbar PmenuSbar
> hi default link UfoPreviewThumb PmenuThumb
> hi default link UfoPreviewWinBar UfoFoldedBg
> hi default link UfoPreviewCursorLine Visual
> hi default link UfoFoldedEllipsis Comment
> hi default link UfoCursorFoldedLine CursorLine
 

> UfoFoldedFg: Foreground for raw text of folded line.
> UfoFoldedBg: Background of folded line.
> UfoPreviewSbar: Scroll bar of preview window, only take effect if the border is missing right horizontal line, like border = 'none'.
> UfoPreviewCursorLine: Highlight current line in preview window if it isn't the start of folded lines.
> UfoPreviewWinBar: Virtual winBar of preview window.
> UfoPreviewThumb: Thumb of preview window.
> UfoFoldedEllipsis: Ellipsis at the end of folded line, invalid if fold_virt_text_handler is set.
> UfoCursorFoldedLine: Highlight the folded line under the cursor

Any colors suggestion to make it blend with Cappuccin?

Thanks

**Comment by nullchilly** [comment]
> Any color suggestions to make it blend with Cappuccin?

I personally like the default highlight groups the way it is:

![image](https://github.com/catppuccin/nvim/assets/56817415/634437c0-44a5-4639-8f2a-9309a3771586)

Perhaps you want something more eye candy? There is not much to work with here.

**Comment by testinfected** [comment]
Hum, I do not get any highlight of folded code. Any idea?

**Comment by nullchilly** [comment]
What's the output of `:hi Folded`? Perhaps if you're using transparent
background?

https://github.com/catppuccin/nvim/blob/044e19ad9f5e48fabd1d96771f814db5dd48008c/lua/catppuccin/groups/editor.lua#L18

**Comment by testinfected** [comment]
Transparent background, that's it.

Thanks ☺️

**Comment by emxxjnm** [comment]
Hello, @nullchilly. I have a question regarding the recent modification.

When the `transparent_background=true` parameter is set, I expect a completely transparent setup. However, when the fold is not respected, too many folds can ruin the entire transparent background. 

Would UfoFoldedEllipsis be a better solution for @testinfected's problem?

For example:
```
UfoFoldedEllipsis = { bg = colors.green, fg = colors.blue }
```

It looks like this:
<img width="581" alt="image" src="https://github.com/catppuccin/nvim/assets/54089360/d1d6fd5c-8b3f-4a19-ab5f-5a46d6c5eb7e">

Users have the ability to customize the style of `nvim-ufo` to their liking.

**Comment by nullchilly** [comment]
I hope https://github.com/catppuccin/nvim/commit/846388d137590e653390ce2f84fea5351a7516ac is good enough :)

![image](https://github.com/catppuccin/nvim/assets/56817415/1d39dccb-6f9d-4cbe-b175-a18797fb4ce1)
