### ISSUE TITLE
Disable Transparent background doesn't work if kitty share the same background

### ISSUE THREAD

**Issue by fecet** [catppuccin/nvim#578]
Kitty's opacity setting will change background if they share the same color:

> Note that it only sets the background color’s opacity in cells that have the same background color as the default terminal background,

So if I use the same flavour in nvim and kitty, and set kitty transparent, then nvim will be transparent whether `transparent_background` is true or false

**Comment by vincenthongzy** [comment]
facing this exact issue as well!

**Comment by nullchilly** [comment]
This should do it I think:

```lua
require("catppuccin").setup({
	kitty = true,
})
```

**Comment by vincenthongzy** [comment]
@nullchilly can confirm is working,, thank you
