### ISSUE TITLE
Is bufferline intergration work? 

### ISSUE THREAD

**Issue by tin-pham** [catppuccin/nvim#59]
is this the bufferline of this theme, I feel like that exactly the same when I set 'false' and 'true' to bufferline in the setup 

![image](https://user-images.githubusercontent.com/20679090/144983312-e1762589-993f-44f3-8f50-a36c6a570229.png)

**Comment by Pocco81** [comment]
The nvim port (this repo) has been updated after [Catppuccin v0.1.1](https://github.com/catppuccin/catppuccin/releases/tag/v0.1.1). This should be working just fine.

Cheers!
