### ISSUE TITLE
todo-comments.nvim integration

### ISSUE THREAD

**Issue by joshmedeski** [catppuccin/nvim#590]
I want to integrate with [todo-comments.nvim](https://github.com/folke/todo-comments.nvim)

- I will do the work and open a PR soon, I wanted to create an issue to track it.

**Comment by mrtnvgr** [comment]
It seems to me that [todo-comments.nvim](https://github.com/folke/todocomments.nvim) plugin doesn't require integration 🤔

Default [configuration](https://github.com/folke/todo-comments.nvim/blob/3094ead8edfa9040de2421deddec55d3762f64d1/lua/todo-comments/config.lua#L60-L65C2) uses some highlight groups from `native_lsp` integration, so overriding them in another integration would cause conflicts.

Feel free to reopen this issue! ❤️

**Comment by joshmedeski** [comment]
I don't see anything significant that needs to be added. All good for now.

**Comment by augustocdias** [comment]
I'm having an issue where the comments are not being highlighted at all... When I use another colorscheme it works as intended. When I enable catppuccin I only get greyed comments.

![image](https://github.com/user-attachments/assets/801418d8-a8e1-494c-a130-7d931931cec7)

Here is my config: https://github.com/augustocdias/dotfiles/blob/main/.config/nvim/lua/setup/catppuccin.lua

Can you help me troubleshoot this?
