### ISSUE TITLE
`dashboard` - missing highlight groups from `doom` theme

### ISSUE THREAD

**Issue by xfzv** [catppuccin/nvim#591]
### Description

It seems that the [`dashboard-nvim`](https://github.com/nvimdev/dashboard-nvim) integration doesn't include the highlight groups for the `doom` theme:

https://github.com/catppuccin/nvim/blob/fc537040147f0374a22b88142a20eb6781141f0b/lua/catppuccin/groups/integrations/dashboard.lua#L1-L15

Full highlight groups (from the [dashboard-nvim README](https://github.com/nvimdev/dashboard-nvim#highlight))

```
-- General
DashboardHeader DashboardFooter
-- Hyper theme
DashboardProjectTitle DashboardProjectTitleIcon DashboardProjectIcon
DashboardMruTitle DashboardMruIcon DashboardFiles DashboardShortCutIcon
-- Doom theme
DashboardDesc DashboardKey DashboardIcon DashboardShortCut
```

As a result, the elements from the `center` section aren't highlighted with Catppuccin colors.

### Neovim version

```console
$ nvim --version

NVIM v0.10.0-dev-1336+g9c2270b83-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Terminal and multiplexer

kitty 0.30.1

### Catppuccin version / branch / rev

fc53704

### Steps to reproduce

1. Run `nvim -u repro.lua`
2. Wait for Lazy and plugins to be installed
3. Close Neovim and re-open it with `nvim -u repro.lua` again

### Expected behavior

Icons, descriptions and keys from `center` section should be highlighted with Catppuccin colors. Example with the Doom theme from the dashboard README:

![image](https://user-images.githubusercontent.com/41671631/214518543-d7d6afbf-f405-4a6f-a505-568c5a101e92.png)

### Actual behavior

Header and Footer are getting proper highlighting/style with Catppuccin colors (blue for header, yellow and italic for footer):
https://github.com/catppuccin/nvim/blob/fc537040147f0374a22b88142a20eb6781141f0b/lua/catppuccin/groups/integrations/dashboard.lua#L6
https://github.com/catppuccin/nvim/blob/fc537040147f0374a22b88142a20eb6781141f0b/lua/catppuccin/groups/integrations/dashboard.lua#L8

 but icons, descriptions and keys from `center` section are not highlighted with Catppuccin colors:

![image](https://github.com/catppuccin/nvim/assets/78810647/dd6248e9-59de-406a-9164-7fc63eea1a8a)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "catppuccin/nvim",
    config = function()
      require("catppuccin").setup({
        flavour = "mocha",
        term_colors = true,
        integrations = {
          dashboard = true,
        },
      })
    end,
  },
  -- add any other plugins here
  {
    "glepnir/dashboard-nvim",
    event = "VimEnter",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = function()
      local opts = {
        theme = "doom",
        hide = { statusline = true },
        config = {
          header = {
            [[                                                                       ]],
            [[                                                                     ]],
            [[       ████ ██████           █████      ██                     ]],
            [[      ███████████             █████                             ]],
            [[      █████████ ███████████████████ ███   ███████████   ]],
            [[     █████████  ███    █████████████ █████ ██████████████   ]],
            [[    █████████ ██████████ █████████ █████ █████ ████ █████   ]],
            [[  ███████████ ███    ███ █████████ █████ █████ ████ █████  ]],
            [[ ██████  █████████████████████ ████ █████ █████ ████ ██████ ]],
            [[                                                                       ]],
            [[                                                                       ]],
          },
          center = {
            { icon = " ", key = "e", action = "ene | startinsert", desc = "New file" },
          },
          footer = function()
            local stats = require("lazy").stats()
            local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
            return { "⚡ " .. stats.count .. " plugins | " .. ms .. "ms" }
          end,
        },
      }

      return opts
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by mrtnvgr** [comment]
> Thanks. I think there's still an issue though:
> 
> https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/dashboard.lua#L12
> 
> `orange` doesn't exist in any palette, so the keys are still not highlighted:
> 
> ![image](https://github.com/catppuccin/nvim/assets/78810647/219805fa-ea46-419e-89e3-fcc52174140c)
> 
> Shouldn't it be `peach` instead?
> 
> ```lua
> DashboardKey = { fg = C.peach },
> ```
> 

Oops
