### ISSUE TITLE
`styles.types` option might be incorrect for ts* files

### ISSUE THREAD

**Issue by skoch13** [catppuccin/nvim#596]
### Description

Enabling ﻿types styles might not work as expected. I have identified at least two issues when applying the ﻿`types` directive:

* `variable declarator(name)` changes
* `predefined_type` is not changed

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
```

### Terminal and multiplexer

wezterm 20230712-072601-f4abf8fd

### Catppuccin version / branch / rev

catppuccin 1.5.0

### Steps to reproduce

```
--lazy.nvim
return {
  {
    "catppuccin/nvim",
      flavour = "mocha",
      styles = {
        types = { "italic" },
      },
    },
  },
```

### Expected behavior

1. All types custom and built_in types become italic
2. Variable names aren't touched

### Actual behavior

![Screenshot2023-10-22 at 09 28 30](https://github.com/catppuccin/nvim/assets/29177689/0aac8225-0bfc-4bd2-ab74-23681408df6c)

**Comment by nullchilly** [comment]
`MY_VAR` is both `@constant` and `@type`

![image](https://github.com/catppuccin/nvim/assets/56817415/c3803e21-319b-448f-b4bf-fe5ab91cdde3)

`key` was linked to `@parameter` which uses `styles.variables`

![image](https://github.com/catppuccin/nvim/assets/56817415/88ccb47c-f38b-41ab-8dee-390b0e189f08)

I think this setting is fine as is

```lua
{
  "catppuccin/nvim",
  flavour = "mocha",
  styles = {
    types = { "italic" },
    variables = { "italic" }
  },
},
```
