### ISSUE TITLE
Windows Terminal + FiraCode strange behavior

### ISSUE THREAD

**Issue by ls-devs** [catppuccin/nvim#598]
### Description

Hi, 
Switching from `Linux` to `Windows` with `WSL`, I just discovered that using `Fira Code Nerd Font` with my actual neovim configuration cause strange looking things.

Please see : 
![image](https://github.com/catppuccin/nvim/assets/58638832/69c29a8c-10a3-4dc5-9891-5af7bb3fe051)
![image](https://github.com/catppuccin/nvim/assets/58638832/16efdd35-5fc3-4ce7-b95a-4496f91ab201)
![image](https://github.com/catppuccin/nvim/assets/58638832/97d80564-b016-470a-b90c-8ad8d4ac1919)

I tried switching font and everything looks correct, also I keeped Fira Code and switched for another coloscheme and everything looks correct. So I guess there's something with catppuccin actually.

### Neovim version

```markdown
NVIM v0.10.0-dev-1412+g1094d0c0d-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905
```

### Terminal and multiplexer

Windows 11 Terminal

### Catppuccin version / branch / rev

catppuccin v1.5.0 (main)

### Steps to reproduce

Actually I dont have any steps to reproduce since the configuration is correct from my Linux PC.

The only thing I can share is my neovim configuration if anyone wants to try it on Windows Terminal with Fira Code Nerd Front.

[ls-devs/nvim](https://github.com/ls-devs/nvim)

### Expected behavior

Everything looks correct, without any glitches, Italic or `/` instead of `|`

### Actual behavior

Weird symbols ( `/` instead of `|`), everything is italic...

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nullchilly** [comment]
Seems like an lspsaga's issue: https://github.com/nvimdev/lspsaga.nvim/issues/529
