### ISSUE TITLE
Is this true color?

### ISSUE THREAD

**Issue by tin-pham** [catppuccin/nvim#60]
The 'NavBar' and "Home' should be different color (like yellow), I used treesitter (javascript) and also turn it on in the config

Or I miss out something

![image](https://user-images.githubusercontent.com/20679090/145000071-bf1c265f-518c-408e-8dfd-1511a2520838.png)

**Comment by Pocco81** [comment]
There was a big update, it should look like this with latest `main`:

![image](https://user-images.githubusercontent.com/58336662/145088323-970a8829-a05f-4af0-bfa4-40fa860f247e.png)

This is what it should've looked like before:

![image](https://user-images.githubusercontent.com/58336662/145088767-9ef0eb8d-2715-4020-b2d5-e1c755cde77d.png)

**Comment by tin-pham** [comment]
Thanks for the update
