### ISSUE TITLE
Fold with macha is unreadable

### ISSUE THREAD

**Issue by SwannHERRERA** [catppuccin/nvim#609]
### Description

When I fold the code [guide](https://neovim.io/doc/user/usr_28.html#usr_28.txt), the color of the text is unreadable.

### Neovim version

```markdown
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

wezterm and zellij

### Catppuccin version / branch / rev

version of nvchad (sorry)

### Steps to reproduce

1 open nvim with file and multiple line
2 Select multiple line
3 use zf to fold 
4 remove your cursor from the folded line
(there is other way to do it)

### Expected behavior

A lisible line, maybe in a pastel color, nvim base theme seems to make it darker as comment but I think it should be more visible

### Actual behavior

the line is really dark and it's almost unreadable I need to get very close to the screen, but when I put my cursor on the line it's ok.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nekowinston** [comment]
What does
> version of nvchad (sorry)

mean?
