### ISSUE TITLE
More nvim-cmp colors

### ISSUE THREAD

**Issue by pierpo** [catppuccin/nvim#61]
Hey! We can have more colors to the cmp completion menu since this:

https://www.reddit.com/r/neovim/comments/r42njg/here_are_the_vs_code_theme_colors_for_the_new/

It would be nice to add it 😊

**Comment by Pocco81** [comment]
Great idea! How do you like it now?

**Comment by pierpo** [comment]
It's lovely! Thank you :heart_eyes:
