### ISSUE TITLE
Neogit integration breaks since `f90c7c0`

### ISSUE THREAD

**Issue by GotaLoveFiraCode** [catppuccin/nvim#612]
### Description

Since `f90c7c0` neogit integration functions, but the cursorline becomes extremely brightly colored and makes everything else illegible. This makes neogit unusable. The color in question looks like lavender, but I'm not sure there :)

### Neovim version

```markdown
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

alacritty 0.12.3

### Catppuccin version / branch / rev

catppuccin commit 9f3c13bbcf16fcaec3a429c03743a13e5923f3e3

### Steps to reproduce

Install everything the normal way with the latest commit and enable neogit integration. 

### Expected behavior

Legible cursorline.
![Picture of catppuccin and neogit with normal cursorline](https://i.ibb.co/StpBj26/catppuccin-img-neogit-proper.png)

### Actual behavior

Illegible cursorline.
![image of neogit with bright color instead of normal cursorline](https://i.ibb.co/CMR6wL0/catppuccin-img-neogit-bug.png)

* * *

I really love the colorscheme and am utterly convinced that it is the greatest ever. Please keep going :)

### Neogit version
`d3c5687`

**Comment by aaronmcadam** [comment]
I'm still seeing issues when the cursor is outside of a diff block/hunk:
![CleanShot 2023-11-14 at 22 10 57@2x](https://github.com/catppuccin/nvim/assets/37928/91a1dd14-9d57-4da6-8a2d-9386d8d708a6)

**Comment by aaronmcadam** [comment]
@mrtnvgr Do you need a new issue for the above?
