### ISSUE TITLE
selection color almost invisible

### ISSUE THREAD

**Issue by halturin** [catppuccin/nvim#619]
### Description

here is how it looks 
![image](https://github.com/catppuccin/nvim/assets/118860/b8860616-e68b-4c94-889e-fac9f12e71bf)
In this example `Reco` has been selected.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

### Terminal and multiplexer

tmux 3.3a

### Catppuccin version / branch / rev

latest version of Nvchad (it has preinstalled this color theme)

### Steps to reproduce

install the latest nvchad

### Expected behavior

i'm expecting to see the selected text

### Actual behavior

The selection is almost invisible.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nekowinston** [comment]
Please see https://github.com/catppuccin/catppuccin/issues/2207#issuecomment-1793789479, the version you use isn't related at all ot this repo; please report it upstream or switch to our plugin :slightly_smiling_face:

**Comment by halturin** [comment]
> Please see [catppuccin/catppuccin#2207 (comment)](https://github.com/catppuccin/catppuccin/issues/2207#issuecomment-1793789479), the version you use isn't related at all to this repo; please report it upstream or switch to our plugin 🙂

thanks for the details. didn't know that.

**Comment by Faetu** [comment]
> Please see [catppuccin/catppuccin#2207 (comment)](https://github.com/catppuccin/catppuccin/issues/2207#issuecomment-1793789479), the version you use isn't related at all to this repo; please report it upstream or switch to our plugin 🙂

Hi, found this issue while searching for a solution.

I want to use catppuccin latte. But I have done the same (mistake) and installed nvchad. Currently I dont want to reinstall everything. So can you show me how do I change to your plugin for nvchad 2.0?

best regards
