### ISSUE TITLE
Indent blank line doesn't accept to change the color

### ISSUE THREAD

**Issue by KevenGoncalves** [catppuccin/nvim#621]
### Description

In the configurations says that we can change the color of the indent blank line but seems like is not working, I put lavender in scope_color but it stuck in a blue color
![Captura de Tela 2023-11-30 às 10 01 56](https://github.com/catppuccin/nvim/assets/80492657/15938fd4-4a7f-4917-9128-f94bdc46dc3d)

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699180677
```

### Terminal and multiplexer

kitty 0.27.1

### Catppuccin version / branch / rev

branch main

### Steps to reproduce

Install lunarvim, indent_blankline and active the option for the highlight the indentlines, and try to install catppuccin

### Expected behavior

change the color of the indent blank line

### Actual behavior

the color stuck in blue only

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by KevenGoncalves** [comment]
Manage to solve it using:
```lua

custom_highlights = function(colors)
    return {
      IndentBlanklineContextChar = { fg = colors.lavender },
      IndentBlanklineContextStart = { sp = colors.lavender, style = { "underline" } }
    }
  end,
```

**Comment by mrtnvgr** [comment]
`indent-blankline` integration supports only [v3](https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v3.0.0) highlight groups, update your plugin to the latest version :)
