### ISSUE TITLE
Can not install with Vim Plug

### ISSUE THREAD

**Issue by broccoli5** [catppuccin/nvim#63]
I get this error:
```
x nvim:
    fatal: invalid reference: master
```
After I quit and try to install it again it is marked as "already installed"

When I try to use it I get this:
```
Error detected while processing /home/rgamuf.configinvim/pluginvim/colors/catopuccin.vim: line 3: E5105:
Error while calling lua chunk: ...mq.configinvim/pluginvim/lua/catopuccin/core/mapper.lua:191: attempt to call field 'ttildeep_extend' (a nil value) Press ENTER or type command to continue' 
```
Also the first installation that I did was successful, but then I got the above error

**Comment by Pocco81** [comment]
> I get this error:

That's because you probably specified/Plug specified by default to fetch the theme from the `master` branch. Vim Plug has a parameter to point to one specific branch to fetch from. In this case you'd want to set it to `main`.

**Comment by broccoli5** [comment]
Ah, I didn't know that was a thing. Now it installs without issues, but I still get the second error

**Comment by Pocco81** [comment]
so apparently [this](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/core/mapper.lua#L191) line is the one throwing the error. Maybe the `vim.tbl_deep_extend()` is not available in your nvim built? could you show me the output of `nvim-v` and `:help vim.tbl_deep_extend()`?

**Comment by broccoli5** [comment]
>Maybe the vim.tbl_deep_extend() is not available in your nvim built?

 Yea, it isn't. I forgot that I stayed on v0.4.4 because v0.5.0 broke the undo files (https://github.com/neovim/neovim/issues/14978). Feel free to close this

**Comment by Pocco81** [comment]
Oh well, guess we'll have to add a prerequisites section in the README :^)
