### ISSUE TITLE
OctoEditable xxx cleared on startup

### ISSUE THREAD

**Issue by joshmedeski** [catppuccin/nvim#634]
### Description

When I start up NeoVim with an Octo command

```
nvim -c ":Octo issue edit 98"
```

the following message is logged and I'm forced to hit `enter` to dismiss it

```
OctoEditable   xxx cleared
```

<img width="463" alt="SCR-20231226-ibpu" src="https://github.com/catppuccin/nvim/assets/2036594/b1b72696-65a1-4328-92c5-b95283859c8a">

---

I'm using [lazy.nvim](https://github.com/folke/lazy.nvim) to load Octo and Catppuccin:

```lua
  {
    "pwntester/octo.nvim",
    cmd = "Octo",
    -- ...
  },
  {
    "catppuccin/nvim",
    priority = 1000,
  }
```

I've confirmed that this only happens because of Catppuchin.

Can the `OctoEditable xxx cleared` message be removed? I look through the source code and can't figure out what is causing the message to be displayed in the first place. It seems it may be an issue with Octo loading before Catppuchin then the highlight group is cleared, causing the message.

## Workaround

Putting `silent` in front of the command will ignore the message and open the Octo buffer directly.

```
nvim -c ":silent Octo issue edit 98"
```

### Neovim version

```markdown
NVIM v0.9.4
Build type: release
LuaJIT 2.1.1700008891
```

### Terminal and multiplexer

wezterm 20231017-091526-fec90ae0

### Catppuccin version / branch / rev

  "catppuccin": { "branch": "main", "commit": "4fbab1f01488718c3d54034a473d0346346b90e3" },

### Steps to reproduce

1. Install Octo and Catppuchin plugins
2. Open Neovim with an Octo command 
```
nvim -c ":Octo issue edit 98"
```
3. You will see the `OctoEditable   xxx cleared` that requires user interaction to dismiss.

### Expected behavior

I can open Neovim with an Octo command and be taken directly to the Octo buffer with no messages.

### Actual behavior

The message is shown and has to be dismissed

### Repro

```Lua
n/a
```

**Comment by nullchilly** [comment]
Cannot reproduce with `nvim -u /tmp/repro.lua -c "Octo issue edit 1"`

https://github.com/catppuccin/nvim/assets/56817415/3e79f323-2cbe-4647-9029-8f65b45b7116

`/tmp/repro.lua` content:
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	{
		"pwntester/octo.nvim",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope.nvim",
			"nvim-tree/nvim-web-devicons",
		},
		config = true,
		cmd = "Octo",
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by joshmedeski** [comment]
Hey, thanks for the response. I played around with your feedback and realize that this is something to do with LazyVim and I actually ended up seeing another plugin do this.

I originally thought it was a trailing debug print statement or something, but I don't think so now.

Thanks for the feedback.
