### ISSUE TITLE
The color of lualine theme is different from the screenshot

### ISSUE THREAD

**Issue by mrbeardad** [catppuccin/nvim#635]
This is screenshot in README

![](https://user-images.githubusercontent.com/56817415/213473285-7bd858be-6947-4d9e-8c01-2573cbc7e76c.png)

This is my local looks, the background colors of lualine are different from above.

![image](https://github.com/catppuccin/nvim/assets/54128430/d1f5512b-ddcd-4305-9c09-583222ce8c97)

**Comment by holykremowka2137** [comment]
Lualine needs you to specify theme, have you done that? Colors can be different, because lualine is simply not setted to use catppuccin

**Comment by mrbeardad** [comment]
1. Lualine will detecte the colorscheme by using `g:colors_name` automatically
2. Although I specify the theme manually, it is still different from the screenshot
3. I noticed that the [code here](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/utils/lualine.lua#L8) does not set the correct color

**Comment by nullchilly** [comment]
Screenshot of README used feline not lualine.

**Comment by DinkyTrady** [comment]
Will be good if lualine colors change to make different from tokyonight colorscheme

**Comment by gmcmillan82** [comment]
> Will be good if lualine colors change to make different from tokyonight colorscheme

Agreed. Why have Lualine integration when the theme doesn't apply the colours?

**Comment by vollowx** [comment]
@gmcmillan82 What do you mean? The current `lualine` colors are already from the `catppuccin` integration, not `tokyonight` (though might looks similar), while you can still configure the colors manually like [this config](https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/ui/lualine.lua#L12).

**Comment by gmcmillan82** [comment]
Yeah my bad, I know they look similar. I just expected the lualine theme to closer resemble the main catppuccin theme, as currently it feels like it's from a different theme altogether.

<img width="1943" alt="image" src="https://github.com/catppuccin/nvim/assets/30657475/ec1212c5-9849-44be-a78a-c5e05eb8f26f">

**Comment by vollowx** [comment]
Maybe:
1. Customize the lualine highlights in your own config like I mentioned before
2. Create a new issue asking for a change / make it a PR by yourself, though this might be for long as it will be a _breaking change_ that changes many users' Neovim appearance
3. Try other statusline plugins like `feline.nvim` and `heirline.nvim` so that it will be even easier to manually define highlights

On the other hand, @mrbeardad I guess that this issue can be closed as there're no more things unsolved under the title of this issue?

**Comment by vollowx** [comment]
Feel free to op-open if you have other issues :heart:
