### ISSUE TITLE
Encountering an error with the appearance of 'Notify' after setting the background to transparent.

### ISSUE THREAD

**Issue by CofCat456** [catppuccin/nvim#636]
### Description

When I set the theme to transparent, this error occurred.

![截圖 2023-12-27 晚上7 18 03](https://github.com/catppuccin/nvim/assets/93901409/d34d10a5-be34-48d4-871f-5da3f86f4bc0)

### Neovim version

```markdown
NVIM v0.9.4
```

### Terminal and multiplexer

kitty

### Catppuccin version / branch / rev

Catppuccin v1.4.0

### Steps to reproduce

Default configuration

### Expected behavior

No error.

### Actual behavior

There is an error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"catppuccin/nvim",
	"rcarriga/nvim-notify"
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by CofCat456** [comment]
I have identified that this is an issue with [notify](https://github.com/rcarriga/nvim-notify).

[Issue](https://github.com/rcarriga/nvim-notify/issues/188)

Perhaps adding the background color for notify in the theme configuration can prevent errors, or we can wait for notify to be fixed."

**Comment by mrtnvgr** [comment]
> I have identified that this is an issue with [notify](https://github.com/rcarriga/nvim-notify).
> 
> [Issue](https://github.com/rcarriga/nvim-notify/issues/188)
> 
> Perhaps adding the background color for notify in the theme configuration can prevent errors, or we can wait for notify to be fixed."

I think this is not related to that issue
