### ISSUE TITLE
All colors have 1 extra blue

### ISSUE THREAD

**Issue by name-tar-xz** [catppuccin/nvim#639]
### Description

Every color has 1 extra in its blue value

### Neovim version

```markdown
NVIM v0.10.0-dev-6f6abd8
Build type: Release
LuaJIT 2.1.1693350652
```

### Terminal and multiplexer

kitty 0.31.0

### Catppuccin version / branch / rev

latest git (commit: 5e36ca599f4aa41bdd87fbf2c5aae4397ac55074)

### Steps to reproduce

1. `nvim -u repro.lua`
2. :hi or :lua vim.print(require("catppuccin.palettes").get_palette("mocha"))

### Expected behavior

colors match [palette](https://github.com/catppuccin/catppuccin#-palette)

### Actual behavior

all colors have 1 added to their blue value

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nullchilly** [comment]
We do this to workaround kitty transparency issue: https://github.com/catppuccin/nvim/issues/578

If you wish to disable the behavior do `require("catppuccin").setup { kitty = false }`

**Comment by name-tar-xz** [comment]
Shouldn't this be documented in the README
