### ISSUE TITLE
I just installed the neovim, lazy and catppuccin theme and my screen turned into blue

### ISSUE THREAD

**Issue by khanakia** [catppuccin/nvim#641]
### Description

I just installed the neovim, lazy and catppuccin theme
After I close and reopen all the turned blueturned-blue

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

### Terminal and multiplexer

macos zsh

### Catppuccin version / branch / rev

1.6.0

### Steps to reproduce

I just installed the neovim, lazy and catppuccin them.
After I close and reopen all the turned blueturned-blue

### Expected behavior

It should load the theme

### Actual behavior

All turned blue

![Screenshot 2024-01-07 at 2 19 33 PM](https://github.com/catppuccin/nvim/assets/2174170/bb2bb03b-b0cf-4fef-acd1-5b671ba6dd22)

### Repro

```Lua
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 }
}
local opts = {}

require("lazy").setup(plugins, opts)

vim.cmd.colorscheme "catppuccin"
```

**Comment by nullchilly** [comment]
See [Colors doesn't match preview screenshots](https://github.com/catppuccin/nvim?tab=readme-ov-file#colors-doesnt-match-preview-screenshots)

Catppuccin doesn't support default macos terminal, consider switching to iterm2.
