### ISSUE TITLE
nvim-treesitter breaking changes on highlight

### ISSUE THREAD

**Issue by hinell** [catppuccin/nvim#648]
See related discussions:
* https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/
* https://github.com/nvim-treesitter/nvim-treesitter/issues/2293

**Comment by nullchilly** [comment]
Already been done [3 days ago](https://github.com/catppuccin/nvim/pull/630)
