### ISSUE TITLE
Highlight in visual mode hard to see

### ISSUE THREAD

**Issue by ZenithDS** [catppuccin/nvim#65]
I'm not sure if this is just an issue because my terminal has a slightly transparent background, and subsequently, so does nvim. But it's incredibly hard to see what is being selected when I'm in visual mode.

**Comment by Pocco81** [comment]
Could you post a pic? This is how it looks on my end (fully opaque background):

![image](https://user-images.githubusercontent.com/58336662/145519085-4b60ba8e-eafb-4425-a329-9fc3a898a12a.png)

**Comment by wijaksanapanji** [comment]
Yes I'm having similar problem, is there a way to customize visual selection color.
here is my screenshot
![2021-12-13-205813_408x445_scrot](https://user-images.githubusercontent.com/18242489/145816866-9a0b4aa6-c032-443a-b8e7-8ab95e4f3838.png)

**Comment by premell** [comment]
I agree that the visual selection is to hard to see. I like that the selection is a muted color, however I think there is a balance to strike. For example I sent an image of onedarkpro's visual selection, which is way easier to see, but can be quite demanding for the eyes. I think something in between  these two extremes would have been perfect
![image](https://user-images.githubusercontent.com/65544203/145863351-c7d05bd9-05be-4cd9-b37c-aa5a11c0e4b5.png)
![image](https://user-images.githubusercontent.com/65544203/145866044-b4270801-3adb-4dce-b815-d553650cbf0d.png)

**Comment by ZenithDS** [comment]
Sorry it took me a little bit to get around to this but yeah like others said, the visual selection color is very hard to see with even a slightly transparent background

![Visual](https://user-images.githubusercontent.com/77712443/146113769-20b85ed9-2cde-47e5-9a2b-05cb8e8194f6.png)

**Comment by Pocco81** [comment]
I promise that everything will look better after the release of Catppuccin v0.1.5.

**Comment by samrathchadha** [comment]
Is it possible for it to have a white selection like how the alacritty colorscheme has? Or maybe a dark default select with the same text highlights(when you select yellow text the highlight is yellow).

<img width="938" alt="image" src="https://user-images.githubusercontent.com/69572668/146483869-b4fa4f38-58b2-4ca2-9f45-f3675537125c.png">

**Comment by Pocco81** [comment]
As promised, [Catppuccin v0.1.1](https://github.com/catppuccin/catppuccin/releases/tag/v0.1.1) has been released and the Nvim port (this repo) has been updated with it as well. It now looks like this:

![image](https://user-images.githubusercontent.com/58336662/146965137-c4b287f3-a300-4a21-b75f-3bbb6b56d3f7.png)

Cheers!
