### ISSUE TITLE
color become very cyan

### ISSUE THREAD

**Issue by quantrpeter** [catppuccin/nvim#656]
### Description

why my color become abnormal?

<img width="1125" alt="image" src="https://github.com/catppuccin/nvim/assets/50471577/e8ce4415-d093-4b7c-a837-1b5b4c6dade5">

thanks

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

### Terminal and multiplexer

mac terminal

### Catppuccin version / branch / rev

v0.9.5

### Steps to reproduce

color become abnormal

### Expected behavior

color become abnormal

### Actual behavior

color become abnormal

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nekowinston** [comment]
catppuccin/nvim does not support Terminals that don't support true color: https://github.com/catppuccin/nvim#colors-doesnt-match-preview-screenshots
Terminal.app does not support true color, please switch to iTerm2, Kitty, Wezterm, or similar.
