### ISSUE TITLE
Map @lsp.mod.readonly to constant

### ISSUE THREAD

**Issue by tkrause** [catppuccin/nvim#662]
**Is your feature request related to a problem? Please describe.**
Highlighting does not work for some LSPs with constants when semantic tokens are enabled. This is due to a missing `@lsp.mod.readonly` mapping and can be seen with gopls and likely others.

**Describe the solution you'd like**
Add support for `["@lsp.mod.readonly"] = { link = "Constant" }`

**Describe alternatives you've considered**
I'm using the above in my custom_overrides which solves my issue but it would be nice if this was just built-in.

**Comment by nullchilly** [comment]
Hi, we try to set highlights based on what we think the majority wants

Unfortunately, I don't think it's a good idea to make this builtin

![image](https://github.com/catppuccin/nvim/assets/56817415/0558c6df-166a-4061-9a51-0f7cdcb8c332)
