### ISSUE TITLE
bug: black screen and small delay when opening a python file

### ISSUE THREAD

**Issue by datwaft** [catppuccin/nvim#668]
### Description

Lately I have been having a problem in which when I opened a python file I had for a few milliseconds a black screen. This only happened when opening a python file and I could pinpoint the issue to this colorscheme. I tried with other colorschemes and the issue doesn't happen with them.

See the following asciinema for evidence (https://asciinema.org/a/HlbysnhqXlsJr0I0OJ2xNfJEg):

<a href="https://asciinema.org/a/HlbysnhqXlsJr0I0OJ2xNfJEg" target="_blank"><img src="https://asciinema.org/a/HlbysnhqXlsJr0I0OJ2xNfJEg.svg" /></a>

As you can see I only have catppuccin installed.

### Neovim version

```markdown
NVIM v0.10.0-dev-2451+g8b4e26915
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```

### Terminal and multiplexer

wezterm 20240203-110809-5046fc22 with tmux 3.4

### Catppuccin version / branch / rev

catppuccin main

### Steps to reproduce

1. Have a neovim configuration with catppuccin installed
2. Open a python file (e.g. `file.py`)

### Expected behavior

There should not be a black screen for a few milliseconds.

### Actual behavior

There is a black screen for a few milliseconds.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by tkkcc** [comment]
It's may be you are not using `priority = 1000`, as in readme.

**Comment by datwaft** [comment]
> It's may be you are not using `priority = 1000`, as in readme.

Already tried that, whether I use priority or not it happens.

**Comment by datwaft** [comment]
Just tested this once again and it seems to be fixed now. I will be closing the issue.
