### ISSUE TITLE
NeoTree background does not blend with the WinSeparator as shown in README screenshots.

### ISSUE THREAD

**Issue by UtkarshVerma** [catppuccin/nvim#670]
### Description

In the screenshots, the background of NeoTree and the window separator is the same which gives a consistent look to the sidebar. It can be achieved by setting the fillchar appropriately.

```lua
vim.opts.fillchars.vert = "▎", -- Used for window separator.
```

I have to use the following custom_highlight to fix it:

```lua
      custom_highlights = function(colors)
        return {
          -- Make window separator blend with neo-tree.
          WinSeparator = { fg = colors.mantle, bg = colors.none },
        }
      end,
```

### Neovim version

```markdown
NVIM v0.9.5 
Build type: Release 
LuaJIT 2.1.1702233742 
 
   system vimrc file: "$VIM/sysinit.vim" 
  fall-back for $VIM: "/usr/share/nvim" 
 
Run :checkhealth for more info
```

### Terminal and multiplexer

st

### Catppuccin version / branch / rev

catppuccin v1.6.0

### Steps to reproduce

Just open neovim and observe the separator.

### Expected behavior

Window separator color is same as NeoTree background.

### Actual behavior

The border looks different.

![image](https://github.com/catppuccin/nvim/assets/31820255/74e7fc92-3f1d-49ac-9009-8a82cd5ec212)

**Comment by idm1try** [comment]
on screenshot is nvimtree with https://github.com/catppuccin/nvim/blob/c0de3b46811fe1ce3912e2245a9dfbea6b41c300/lua/catppuccin/groups/integrations/nvimtree.lua#L11 
neotree also has this like defined here https://github.com/catppuccin/nvim/blob/c0de3b46811fe1ce3912e2245a9dfbea6b41c300/lua/catppuccin/groups/integrations/neotree.lua#L37 but neotree catppuccin integration disabled by default (so just enable this integration in your config)

**Comment by UtkarshVerma** [comment]
I had the integration for neotree turned on. Here is the repro.lua for this if you want to test:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"catppuccin/nvim",
		main = "catppuccin",
		opts = {
			integrations = {
				neotree = true,
			},
		},
	},

	{
		"nvim-neo-tree/neo-tree.nvim",
		dependencies = {
			{ "MunifTanjim/nui.nvim" },
			{ "nvim-lua/plenary.nvim" },
			{ "nvim-tree/nvim-web-devicons" },
		},
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.opt.fillchars = { vert = "▎" }
vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by idm1try** [comment]
tested its working with `NeoTreeWinSeparator` hightlight

**Comment by UtkarshVerma** [comment]
So, would it be added upstream, or do I have to update my config?

**Comment by idm1try** [comment]
for now you can use custom_hightlights 
`NeoTreeWinSeparator = { fg = colors.base, bg = colors.base }`
