### ISSUE TITLE
React (JSX) code does not show different colors for variables.

### ISSUE THREAD

**Issue by escapingSamsara** [catppuccin/nvim#672]
### Description

When using a variable in a jsx file in neovim using catppuccin theme, the variable doesnt get a different color to regular text, is this intended ? If so i would suggest to create a different color for it so it gets more visible. If it is not intended, please let me know how I can fix it for me

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

### Terminal and multiplexer

gnome terminal with tmux latest

### Catppuccin version / branch / rev

latest

### Steps to reproduce

open a react project, create a jsx file, use a variable for example:

`function App(){
const header = "I am a header"
return(
<h1>{header}. But i have the same color as this string inside of neovim</h1>
)
}`

see screenshot:

![image](https://github.com/catppuccin/nvim/assets/111993187/9bcd8bbe-7fad-4803-9d61-f30b7b53c7aa)

### Expected behavior

i expected to see another color highlighting for the variable inside the p tag

### Actual behavior

same color as the string

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by mrtnvgr** [comment]
That's because treesitter treats variable names exactly the same in different contexts.

![20240302_09h46m04s_grim](https://github.com/catppuccin/nvim/assets/48406064/6ee5f369-8d7b-479e-aeff-08f5b8abd318)
![20240302_09h46m15s_grim](https://github.com/catppuccin/nvim/assets/48406064/ab4a7631-0d01-424f-b6af-83ff7e7d915e)

![20240302_09h46m53s_grim](https://github.com/catppuccin/nvim/assets/48406064/788bc254-1f88-4e32-b3f6-52582d98b0f0)
![20240302_09h47m03s_grim](https://github.com/catppuccin/nvim/assets/48406064/fee47fff-eacb-4232-9b5b-d04d6d796b67)

This behaviour is consistent between many languages that treesitter supports (e.g. python).

**Comment by thenickbit** [comment]
Hey @mrtnvgr! Would that be the same reason why props (or ts types) have different colors on different editors? Or could that just be a theme implementation difference? 
This is my test with both using `catppuccin-macchiato`

vscode:
![image](https://github.com/catppuccin/nvim/assets/17451465/2901ac2a-e511-49a9-8913-55a718c14478)

nvim:
![image](https://github.com/catppuccin/nvim/assets/17451465/780603ea-64f4-4e6a-8df6-063968a05c45)

(I'm in my early nvim days, so there might be something off with my config as well!)

**Comment by nullchilly** [comment]
It seems like you're missing [lsp semantic highlights](https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight)

![image](https://github.com/catppuccin/nvim/assets/56817415/1e043012-10ff-4014-a68a-c24b1ed92925)
