### ISSUE TITLE
Semantic Highlighting - basedpyright

### ISSUE THREAD

**Issue by karimlevallois** [catppuccin/nvim#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

With the release of the new pyright fork basedpyright, semantic highlighting has now been enabled within Python. However, it looks like something might have to be updated in catppuccin as enabling semantic highlighting seems to change functions from peach to blue.

Please see my comments / screenshots on the below issue:-

https://github.com/DetachHead/basedpyright/issues/176

**Comment by backwardspy** [comment]
just been reminded issues can be transferred :)

**Comment by sgoudham** [comment]
Not read the full context of the issue but its worth saying that according to the [style-guide](), methods/functions should be **blue**.

afaik, Neovim still needs to get updated according to the revamped style guide so that might be part of the reason for the colour change?

**Comment by karimlevallois** [comment]
Ah OK, so have methods / functions have now changed from peach to blue? There was just too much blue going on for my liking, hard to spot the differences.

Before:-

<img width="1680" alt="IMG_1382" src="https://github.com/catppuccin/nvim/assets/80129273/e3c36d5f-4c65-4848-8bd6-733f18c7d899">

Afrer:- 

<img width="1680" alt="IMG_1381" src="https://github.com/catppuccin/nvim/assets/80129273/d371b7df-2374-4a58-9ae4-5fc12a61b921">

**Comment by nullchilly** [comment]
You can try [Overwriting highlight groups](https://github.com/catppuccin/nvim#overwriting-highlight-groups) to adjust to your liking

```lua
require("catppuccin").setup {
  custom_highlights = function(C)
    return {
      ["@lsp.typemod.function.builtin"] = { fg = C.peach },
    }
  end
}
```

**Comment by karimlevallois** [comment]
Out of curiosity, why are my functions peach if they have been updated to blue under the below?

https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/syntax.lua

 I am not currently overriding any colours and this is the same on both LazyVim and Lunarvim - peach from functions.
