### ISSUE TITLE
Treesitter context highlighting when transparent_background=true

### ISSUE THREAD

**Issue by victorkamoto** [catppuccin/nvim#683]
The context from nvim-treesitter-context doesn't get highlighted when transparent_background=true. 

![context](https://github.com/catppuccin/nvim/assets/43573646/5084e615-bb76-4b3e-894d-6dfc1526761c)

The cursor line highlight color would be perfect:

![Screenshot from 2024-03-25 15-48-49](https://github.com/catppuccin/nvim/assets/43573646/ee5511c0-44e4-4647-8e87-bf3fc04fad1e)

Similar in folke/tokyonight.nvim transparent background:

![Screenshot from 2024-03-25 15-38-20](https://github.com/catppuccin/nvim/assets/43573646/ffc4d79f-51ea-4dcc-8893-e750bbcc7d2e)

**Comment by victorkamoto** [comment]
Thanks for the reply. 
That works. How do I go about enabling that support? Is that option in catppuccin?
For reference, in nvim-lspconfig, I have underline enabled for diagnostics and they work (shows undercurl?)

![Screenshot from 2024-03-25 17-29-04](https://github.com/catppuccin/nvim/assets/43573646/8e113b63-f972-422f-806d-1030b6af665a)

**Comment by nullchilly** [comment]
I added `treesitter_context` integration to the default option now, try to update catppuccin

**Comment by victorkamoto** [comment]
Awesome it works now. Thanks again :)
