### ISSUE TITLE
Incorrect Typescript keyword color with TreeSitter enabled

### ISSUE THREAD

**Issue by stanley2058** [catppuccin/nvim#699]
### Description

Hi, after updating to 1.7.0 I found that keywords in Typescript are not highlighted like they used to be in 1.6.0. I tried with and without TMUX, the stable and nightly versions of Neovim, and all produced the same result, so it seems like it may be a bug in 1.7.0.

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188
```

### Terminal and multiplexer

kitty 0.34.1

### Catppuccin version / branch / rev

catppuccin v1.7.0

### Steps to reproduce

1. Create a test file with content:
	```ts
	class Foo {
	  hello() {
	    const bar = 10;
	    return typeof bar;
	  }
	
	  toString() {
	    return this.hello();
	  }
	}
	
	const foo = new Foo();
	console.log(foo instanceof Foo);
	```
2. nvim -u repro.lua test.ts
3. After TreeSitter downloads and compiles the Typescript highlighting, keywords are in the wrong color.

### Expected behavior

Same `repro.lua` with `catppuccin` set to `v1.6.0`
![image](https://github.com/catppuccin/nvim/assets/22907128/1b6e6657-7cc2-46aa-a507-e2f253c1e802)

### Actual behavior

![image](https://github.com/catppuccin/nvim/assets/22907128/e0beb72e-3df8-45b4-84cf-c8885841857a)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"catppuccin/nvim",
	-- add any other plugins here
	{
		"nvim-treesitter/nvim-treesitter",
		version = false,
		build = ":TSUpdate",
		init = function(plugin)
			require("lazy.core.loader").add_to_rtp(plugin)
			require("nvim-treesitter.query_predicates")
		end,
		opts = {
			highlight = { enable = true },
			ensure_installed = {
				"typescript",
			},
		},
		---@param opts TSConfig
		config = function(_, opts)
			if type(opts.ensure_installed) == "table" then
				---@type table<string, boolean>
				local added = {}
				opts.ensure_installed = vim.tbl_filter(function(lang)
					if added[lang] then
						return false
					end
					added[lang] = true
					return true
				end, opts.ensure_installed)
			end
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by fioncat** [comment]
This is because of #694.

If you don't like it, you can overwrite `@keyword.operator` to fallback to previous hightlight:

```lua
["@keyword.operator"] = { fg = cp.mauve }
```

**Comment by stanley2058** [comment]
Ah, that's why! Thanks for the information!

It seems like the operator color is set to `sky`, which due to my slight color blindness, can't really tell apart from the color `text`. I was wondering if I have misconfigured something :sweat_smile:

Anyway, thanks a lot for the help, I will close this issue!
