### ISSUE TITLE
Transparent_background option doesn't work

### ISSUE THREAD

**Issue by arionrefat** [catppuccin/nvim#70]
![image](https://user-images.githubusercontent.com/37513070/146328200-ea42ea4b-8b8d-4748-b667-a906fed4a8ff.png)
I use alacritty, transparent_background option doesn't seem to make an effect as you can see above.

**Comment by Pocco81** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/58336662/146964600-562c0ff2-f1cf-4f9d-954f-5133d9e135cd.png)

Can I see your Alacritty conf? and if possible your Catppuccin conf too :)

**Comment by arionrefat** [comment]
Sure,
Alacritty config: https://github.com/arionrefat/dotfiles/blob/master/alacritty/.config/alacritty/alacritty.yml
catppuccin config: https://github.com/arionrefat/dotfiles/blob/master/neovim/.config/nvim/lua/user/colorscheme.lua

Also it doesn't work in st

![image](https://user-images.githubusercontent.com/37513070/146966441-0e9ad344-464a-4811-9e72-2153d5908755.png)

**Comment by Pocco81** [comment]
Well it seems like the problem is that your background is fully opaque: https://github.com/arionrefat/dotfiles/blob/master/alacritty/.config/alacritty/alacritty.yml#L313

**Comment by arionrefat** [comment]
Ow, sorry, I changed it a while ago
Here is a screenshot with the changed value

![image](https://user-images.githubusercontent.com/37513070/146967314-665f811d-8a55-41c9-9329-36a903200e6a.png)

**Comment by Pocco81** [comment]
huh, weird. Does it work if you run:

```bash
hi Normal guibg=NONE ctermbg=NONE
```

**Comment by arionrefat** [comment]
Yes it does!

**Comment by arionrefat** [comment]
Okay, found my stupidity, I called "colorscheme catppuccin" before the setup table, that's why it was not loading the config. Really sorry, should have looked a bit more.

**Comment by Pocco81** [comment]
Hahah no problem!
