### ISSUE TITLE
lazy.nvim: module 'catppuccin.groups.integrations.colorful_winsep'

### ISSUE THREAD

**Issue by Std-Enigma** [catppuccin/nvim#714]
### Description

I recently insalled colorful_winsep plugin and enabled it's integeration and i'm getting this error

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Terminal and multiplexer

kitty 0.35.0

### Catppuccin version / branch / rev

catppuccin v1.7.0

### Steps to reproduce

1. set the colorscheme to catppuccin

### Expected behavior

no error

### Actual behavior

Failed to run `config` for catppuccin

...share/nvim/lazy/catppuccin/lua/catppuccin/lib/mapper.lua:52: module 'catppuccin.groups.integrations.colorful_winsep' not found:
^Ino field package.preload['catppuccin.groups.integrations.colorful_winsep']
cache_loader: module catppuccin.groups.integrations.colorful_winsep not found
cache_loader_lib: module catppuccin.groups.integrations.colorful_winsep not found
^Ino file './catppuccin/groups/integrations/colorful_winsep.lua'
^Ino file '/usr/share/luajit-2.1/catppuccin/groups/integrations/colorful_winsep.lua'
^Ino file '/usr/local/share/lua/5.1/catppuccin/groups/integrations/colorful_winsep.lua'
^Ino file '/usr/local/share/lua/5.1/catppuccin/groups/integrations/colorful_winsep/init.lua'
^Ino file '/usr/share/lua/5.1/catppuccin/groups/integrations/colorful_winsep.lua'
^Ino file '/usr/share/lua/5.1/catppuccin/groups/integrations/colorful_winsep/init.lua'
^Ino file './catppuccin/groups/integrations/colorful_winsep.so'
^Ino file '/usr/local/lib/lua/5.1/catppuccin/groups/integrations/colorful_winsep.so'
^Ino file '/usr/lib/lua/5.1/catppuccin/groups/integrations/colorful_winsep.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './catppuccin.so'
^Ino file '/usr/local/lib/lua/5.1/catppuccin.so'
^Ino file '/usr/lib/lua/5.1/catppuccin.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /catppuccin/lua/catppuccin/lib/mapper.lua:52 _in_ **apply**
  - /catppuccin/lua/catppuccin/lib/compiler.lua:24 _in_ **compile**
  - /catppuccin/lua/catppuccin/init.lua:113 _in_ **compile**
  - /catppuccin/lua/catppuccin/init.lua:186 _in_ **setup**
  - lua/config/bootstrap.lua:48
  - init.lua:4

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
  },
  {
    {
      "nvim-zh/colorful-winsep.nvim",
      event = "WinNew",
      config = true,
    },
    {
      "catppuccin",
      optional = true,
      opts = {
	integrations = {
	  colorful_winsep = {
	    enabled = true,
	  },
	},
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by vollowx** [comment]
It's likely that you're not using the latest version of catppuccin.nvim. Try to update this plugin.

**Comment by Std-Enigma** [comment]
> It's likely that you're not using the latest version of catppuccin.nvim. Try to update this plugin.

nope that isn't the problem i'm using the latest stable version

**Comment by vollowx** [comment]
Is this problem still here? Among all your Neovim configs, I couldn't find any file requiring or configurating `catppuccin.nvim`. If it's still happening, you can provide a config that can reproduce this problem, so that we can solve this quicker.

**Comment by Std-Enigma** [comment]
This is really weird when doing minimal like this:
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
  },
  {
    {
      "nvim-zh/colorful-winsep.nvim",
      event = "WinNew",
      config = true,
    },
    {
      "catppuccin",
      optional = true,
      opts = {
	integrations = {
	  colorful_winsep = {
	    enabled = true,
	  },
	},
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

this isn't an issue at all but in one of my very specific setups that error pops up

**Comment by vollowx** [comment]
Didn't receive such error on Fedora 39, Neovim 0.9.5, too. I still recommend you to remove your current packages, cache, state and package lock, and completely reload all of your config. It just shouldn't happen with the latest version of catppuccin.nvim.
