### ISSUE TITLE
Add support for `mini.statusline`

### ISSUE THREAD

**Issue by kedom1337** [catppuccin/nvim#715]
**Is your feature request related to a problem? Please describe.**
Currently this plugin does not support the highlight groups used by the plugin `mini.statusline`

**Describe the solution you'd like**
Implementing the catppuccin theme colors for the highlight groups defined [here](https://github.com/echasnovski/mini.statusline/blob/94d5e48415bdf872536e5812475fcf19e09f5c0e/lua/mini/statusline.lua#L49).

**Comment by tjkuson** [comment]
There is support for `mini.statusline`, but it is erroneously disabled by default. I made a patch to fix that: #718
