### ISSUE TITLE
Gray delimiters with treesitter enabled

### ISSUE THREAD

**Issue by jacksonludwig** [catppuccin/nvim#72]
I noticed that when using treesitter, the color for delimiters, such as semicolons, parentheses, and brackets are a dark gray, like below:

![image](https://user-images.githubusercontent.com/42984254/146621455-1a0c1d96-98ab-4fff-b733-a775dac6b2bc.png)

This does not occur without treesitter:

![image](https://user-images.githubusercontent.com/42984254/146621493-7aab8d80-04de-41a5-bcd8-4677d6a1c9ec.png)

Is this intentional? In my opinion delimiters should always be a bright color.

**Comment by Pocco81** [comment]
> Is this intentional?

Yep! We are currently discussing syntax highlighting over at the Discord server. I'm gonna mention this there :)

**Comment by Pocco81** [comment]
You can now customize the colors of every highlight group using Catppuccin's remapping function and its API: https://github.com/catppuccin/nvim#overwriting-highlight-groups
