### ISSUE TITLE
mini.nvim integration seems broken

### ISSUE THREAD

**Issue by nicoe** [catppuccin/nvim#724]
### Description

Since 894efb557728e532aa98b98029d16907a214ec05 the mini integration is activated by default and I think it broke some highlights.

For exemple there are some highlights that are overridden there:
https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/mini.lua#L46

But in mini.tabline those are linked to the generic highlight groups:
https://github.com/echasnovski/mini.tabline/blob/321d516d7ef9ab6c3dae60095d35877030905919/lua/mini/tabline.lua#L218

Thus I don't think it's relevant to change those.

If you agree with my reasoning then I can submit a patch fixing those and lookup if the other hl-group are also linked to the generic ones. If you don't then I'm wrong :smile:.

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Terminal and multiplexer

foot

### Catppuccin version / branch / rev

catppuccin on the main branch

### Steps to reproduce

1. Install both catppuccin and mini.tabline
2. :highlight MiniTabLineCurrent and :highlight TabLineSel are different

```
:highlight MiniTablineCurrent                                                                                                                                                         
MiniTablineCurrent xxx cterm=bold,underline gui=bold,underline guifg=#cdd6f4 guibg=#1e1e2e guisp=#f38ba8   
```

```
:highlight TabLineSel                                                                                                                                                                 
TabLineSel     xxx guifg=#a6e3a1 guibg=#45475a
```

### Expected behavior

I would expect both to be the same.

### Actual behavior

It seems very strange to me that `MiniTablineCurrent` uses `cterm=bold,underline`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
      {
        "echasnovski/mini.tabline",
        version = false,
        config = function(_, opts)
            require("mini.tabline").setup(opts)
        end,
    },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by nicoe** [comment]
Sorry for the noise the issue was in my config

**Comment by geodimm** [comment]
@nicoe I'm having the same problem. What was the issue in your configuration?

**Comment by nicoe** [comment]
> [@nicoe](https://github.com/nicoe) I'm having the same problem. What was the issue in your configuration?

I don't remember but I wonder if the specification to load catppuccin in lazy shouldn't be this one:

```
    {
        "catppuccin/nvim",
        name = "catppuccin",
        lazy = false,
        priority = 1000,
    }
```

**Comment by geodimm** [comment]
I already have it configured that way, it must be something else. Thanks for the reply!
