### ISSUE TITLE
Tranceparency not working property with telescope dropdown

### ISSUE THREAD

**Issue by chenxin-yan** [catppuccin/nvim#730]
### Description

After setting `transparent_background = true`, regular telescope pickers display correctly except for the dropdown picker from.`require('telescope.themes').get_dropdown()`. The background Is displayed as follows:
![Xnip2024-07-09_13-37-14](https://github.com/catppuccin/nvim/assets/71162231/c74de8c8-e9cd-48e7-b2fa-248c5a4c28df)

Here is [my config](https://github.com/chenxin-yan/nvim/blob/de6d11339ae8f9eca8dba44c8d12f8136f287eba/lua/cyan/config/lazy.lua#L23)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Terminal and multiplexer

iterm2 Build 3.5.2

### Catppuccin version / branch / rev

catppuccin v1.7

### Steps to reproduce

1. set iterm2 to transparent in the setting
2. enable `transparent_background = true` for the theme
3. open dropdown picker

### Expected behavior

The dropdown is expected to display a transparent floating window.

### Actual behavior

The dropdown selector has a black background without any transparency

**Comment by emxxjnm** [comment]
> my config

https://github.com/chenxin-yan/nvim/blob/ff1b49a0dba853089b401270aa92e036a09ee9b9/lua/cyan/plugins/telescope.lua#L94

set winblend = 0

**Comment by chenxin-yan** [comment]
It works after setting winblend to 0. Thanks!

**Comment by Felipe-9** [comment]
How to set windblend for all builtins to zero? is there another way other than having to redefine all functions (Live grep or fzf, oldfiles, find files,...)?
