### ISSUE TITLE
CmpBorder doesn't work

### ISSUE THREAD

**Issue by CalfMoon** [catppuccin/nvim#732]
### Description

I have set CmpBorder to green but the autocompletion border is still grey.

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Terminal and multiplexer

kitty 0.35.2

### Catppuccin version / branch / rev

catppuccin latest commit main

### Steps to reproduce

set this as your cattppuccin config
```lua 
require("catppuccin").setup({
	integrations = {
		mason = true,
		cmp = true,
	},
	custom_highlights = function(colors)
		return {
			FloatBorder = { fg = colors.green },
			CmpBorder = { fg = colors.green },
		}
	end,
})

vim.cmd("colorscheme catppuccin-mocha")

```

and this as your cmp config
```lua 
local cmp = require("cmp")
cmp.setup({
	sources = { { name = "nvim_lsp" } },
	mapping = cmp.mapping.preset.insert({
		["<Tab>"] = cmp.mapping.confirm({ select = true }),
		["<C-k>"] = cmp.mapping.select_prev_item(),
		["<C-j>"] = cmp.mapping.select_next_item(),
	}),

	window = {
		completion = {
			border = "rounded",
		},
		documentation = {
			border = "rounded",
		},
	},
})
```

### Expected behavior

![image](https://github.com/user-attachments/assets/d708b556-127f-4c9a-bb6e-cf6d6bb3617e) expect these auto complete borders to be green.

### Actual behavior

auto complete borders are grey

**Comment by emxxjnm** [comment]
https://github.com/hrsh7th/nvim-cmp/blob/7e348da6e5085ac447144a2ef4b637220ba27209/lua/cmp/config/default.lua#L110

you should set this to override the default value

```lua
winhighlight = 'Normal:Pmenu,FloatBorder: FloatBorder,CursorLine:PmenuSel,Search:None',
```

**Comment by CalfMoon** [comment]
that woked, thank you.
