### ISSUE TITLE
Bad highlighting in .gitignore files using tree-sitter

### ISSUE THREAD

**Issue by ValdezFOmar** [catppuccin/nvim#734]
### Description

A recent [commit in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/commit/e8d74461da831f9b4eb31d2d652bfd0c99a2bd7b) change the highlighting for wildcards and characters in .gitignore. The new captures link to the same `Special` group in catppuccin, which makes wildcards hard to distinguish:

![image](https://github.com/user-attachments/assets/60a1129b-453b-4ce9-8b21-7cb63167cb7f)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
```

### Terminal and multiplexer

kitty 0.35.2

### Catppuccin version / branch / rev

main

### Steps to reproduce

1. `nvim -u repro.lua`
2. open a .gitignore file

Example .gitignore:

```gitignore
path/to/file

*.extension

dir/**file.*

a/*jj/c/d**g

/abc??ghjk
```

### Expected behavior

Wildcards should stand out from the file/directory names.

### Actual behavior

Almost everything is the same color and makes it hard to read.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"catppuccin/nvim",
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		config = function()
			require("nvim-treesitter.configs").setup {
				ensure_installed = { 'gitignore' },
				highlight = { enable = true },
			}
		end
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by vollowx** [comment]
After searching among this and other colorschemes, I'm sure that this appearance is caused by:
- `@character.special` => `SpecialCharacter` => `Special
- `@string.special.path` => `Special`
And it's common to link the special character like this.

Could you please provide a "expected behavior" image, so that we can decide what/how to change, as changing any of them may break some other user interface.

**Comment by ValdezFOmar** [comment]
This is how it looks using traditional vim regex highlighting, making the glob patterns stand out:

![image](https://github.com/user-attachments/assets/d42a4d02-b33c-4b8f-8525-64e935462243)

Couldn't this be solved by linking any of the specific captures `@character.special.gitignore` or `@string.special.path.gitignore` to something different?

**Comment by vollowx** [comment]
It can, but changing that might also affect the UI in some other places. This should be with further consideration I guess

**Comment by ValdezFOmar** [comment]
According to [neovim documentation](https://neovim.io/doc/user/treesitter.html#treesitter-highlight-groups) this is the intended way:

> As an additional rule, capture highlights can always be specialized by
> language, by appending the language name after an additional dot. For
> instance, to highlight comments differently per language:
>
> ```vim
> hi @comment.c guifg=Blue
> hi @comment.lua guifg=DarkBlue
> hi link @comment.documentation.java String  
> ```

**Comment by vollowx** [comment]
Ah, I just found that I misread your advice here 😉

> Couldn't this be solved by linking any of the specific captures `@character.special.gitignore` or `@string.special.path.gitignore` to something different?

This seems to be a acceptable solution, though I'm not sure if this should be implemented on upstream (nvim-treesitter) or we write custom `queries` in this repo.

**Comment by ValdezFOmar** [comment]
I don't think this is an upstream issue, nvim-treesitter only provides the queries, its the colorscheme responsibility to give them a useful color. I don't think queries are necessary either, just doing `["@character.special.gitignore"] = { whatever }` would be enough.
