### ISSUE TITLE
add support for fzf-lua

### ISSUE THREAD

**Issue by zspher** [catppuccin/nvim#739]
**Is your feature request related to a problem? Please describe.**
Hi, this is a nice theme. I would like to request for support for fzf-lua

**Describe the solution you'd like**
Theme for fzf-lua via integration

**Additional context**
highlight groups for fzf-lua: https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#highlights

**Comment by zspher** [comment]
currently using the ff. colors
```lua
FzfLuaBorder = { link = "FloatBorder" },
FzfLuaTitle = { link = "FloatBorder" },

FzfLuaHeaderBind = { fg = c.yellow },
FzfLuaBufNr = { fg = c.yellow },
FzfLuaTabMarker = { fg = c.yellow },
FzfLuaHeaderText = { fg = c.peach },
FzfLuaBufFlagCur = { fg = c.peach },
FzfLuaLiveSym = { fg = c.peach },

FzfLuaPathColNr = { fg = c.blue },
FzfLuaBufFlagAlt = { fg = c.blue },
FzfLuaTabTitle = { fg = c.sky },

FzfLuaPathLineNr = { fg = c.green },
FzfLuaBufName = { fg = c.mauve },
```
from
```
BlanchedAlmond -> yellow
Brown1 -> peach
CadetBlue1 -> blue
LightGreen -> green
LightMagenta -> mauve
LightSkyBlue1 -> sky
```

**Comment by vollowx** [comment]
Seems to be a nice idea! I'll make this ASAP when I get some time!

**Comment by db757** [comment]
This is what I currently use which complies with the [fzf catppuccin theme](https://github.com/catppuccin/fzf) and some personal preference changes:
```lua
'FzfLuaBorder', { link = "FloatBorder" }
'FzfLuaTitle', { link = "FloatBorder" }
'FzfLuaHeaderText', { foreground = C.mauve } -- Personal preference
'FzfLuaHeaderBind', { foreground = C.rosewater } -- Personal preference
...
fzf_colors = {
	["bg"] = '-1', -- Transparent background, originally base
	["fg"] = C.text,
	["bg+"] = C.ui_selection, -- Custom color, originally surface0
	["fg+"] = C.text,
	["hl"] = C.red,
	["hl+"] = C.red,
	["spinner"] = C.rosewater,
	["header"] = C.mauve, -- Personal preference, originally red
	["info"] = C.mauve,
	["pointer"] = C.rosewater,
	["marker"] = C.rosewater,
	["prompt"] = C.mauve,
	["gutter"] = '-1', -- Transparent background
},

```

**Comment by vollowx** [comment]
At this point of implementing the fzf integration, I'm not sure whether should I 

1. Copy the highlights in `catppuccin/fzf` into `catppuccin/nvim` besides the `fzf_lua` ones
2. Just highlight the `fzf_lua` ones

The 1st way causes duplication and might be out-dated when catppuccin/fzf updates, and the 2nd way makes in-consistency all the time.

**Comment by zspher** [comment]
i think the 2nd option should be better as it allows of more consistency and less maintenance. The fzf highlights should be the user's responsibility, either setting it in the fzf_lua plugin or via ` $FZF_DEFAULT_OPTS ` env.

**Comment by vollowx** [comment]
Will write the PR soon :heart:
