### ISSUE TITLE
TSStrong and TSEmphasis seem to be mixed up

### ISSUE THREAD

**Issue by yigothu** [catppuccin/nvim#74]
In `treesitter.lua` it reads:

```lua
TSEmphasis = { fg = cp.catppuccin5, style = "bold" }, -- bold
TSStrong = { fg = cp.catppuccin4, style = "italic,bold" }, -- italic
```

However normally "emphasis" is italic and "strong" is bold, i.e. they seem mixed up.

**Comment by Pocco81** [comment]
Thanks for the notice! it should look good now :+1:
