### ISSUE TITLE
Classical red/green for diffs

### ISSUE THREAD

**Issue by Mange** [catppuccin/nvim#75]
I was wondering if it is possible to (and in that case *how*) to change the configuration to use a more classical "red" = "deleted", "green = added" colorscheme for diffs.
This would apply both for Vim's built-in diff view, Neogit, Gitsigns, etc.

Right now the color is blue for added, which sometimes confuses me since all other tools in my setup uses green.

Here's an example from `Diffview`, but it's the same in all contexts:
![image](https://user-images.githubusercontent.com/1599/147149504-f6dc1a00-ed0c-4c25-a047-ea62c9fe0581.png)

I suppose I could manually call `hi` and rework some highlight groups, but perhaps there's a smarter way to override it at the source and have it apply consistently?

---

I personally like how tools like `git-delta` highlights, and it's usually how I configure my vim themes to approximate:

![image](https://user-images.githubusercontent.com/1599/147149695-418ec23c-4008-400c-a198-7b9d1de98518.png)
(`git-delta` uses a green background color for added lines)

That means I would prefer if the foreground color remained unchanged (and highlighting still), but the background color would become slightly more green or red (and I guess yellow for vim's "changed line").

**Comment by jorgebef** [comment]
I personally agree with the highlight that it could be green for all git add related text instead of blue.
I've just PR'd the change and linked the issue 😺 

Regarding making it look like `git-delta`, I believe that could be given some thought as it seems a decent option.
Only thing to take into account is the colors used in the palette, as they could be a bit too much if used as is for the background.

**Comment by Mange** [comment]
Looks a lot better now! Thanks! :heart: :1st_place_medal: 

----

Now I just need to fix the gitsigns background highlight rows. (This is not a new problem)
![image](https://user-images.githubusercontent.com/1599/148414006-69eb9c57-5a26-4aea-b043-7486c7b6744a.png)

(It's caused by this highlight)
![image](https://user-images.githubusercontent.com/1599/148414238-1524460f-1768-431e-9d99-da86cbc5c969.png)

I'm unsure if this is something that should be handled by this theme (as an integration), or if it should be up to any person to do it themselves. The Neogit plugin documents them here:
https://github.com/TimUntersberger/neogit/blob/85f2bdc31afb132c9603879bf3a7169a917eb949/README.md#contextual-highlighting

Would a PR be welcome if I figure out a good combo of colors?

**Comment by Pocco81** [comment]
> Would a PR be welcome if I figure out a good combo of colors?

PRs are welcomed! I personally don't use neogit (that's why @jorgebef fixed this), so doing this would help out a lot!

**Comment by Pocco81** [comment]
#92 fixed this.
