### ISSUE TITLE
fzf-lua text invisible

### ISSUE THREAD

**Issue by wuliuqii** [catppuccin/nvim#762]
### Description

In the latte flavour, the selected item in fzf-lua is almost invisible, but in telescope it works fine.

fzf-lua:
![image](https://github.com/user-attachments/assets/80089fdd-0004-4f21-8ec8-df5d2865d697)
telescope:
![image](https://github.com/user-attachments/assets/0f81d2bf-6b86-4082-adaa-3d6f62df2e46)

### Neovim version

```markdown
NVIM v0.11.0-nightly+1d11808
Build type: Release
LuaJIT 2.1.1713773202
```

### Terminal and multiplexer

kitty 0.35.2

### Catppuccin version / branch / rev

catppuccin main

### Steps to reproduce

1. `nvim -u repro.lua`
2. `:FzfLua builtin`
3. `Telescope builtin`

### Expected behavior

Consistent behavior of fzf-lua and telescope.

### Actual behavior

fzf-lua is almost invisible, but in telescope it works fine.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		config = function()
			require("catppuccin").setup({
				flavour = "latte",
			})
		end,
	},
	-- add any other plugins here
	{
		"ibhagwan/fzf-lua",
		config = function()
			require("fzf-lua").setup({
				fzf_colors = true,
			})
		end,
	},

	{
		"nvim-telescope/telescope.nvim",
		branch = "0.1.x",
		dependencies = { "nvim-lua/plenary.nvim" },
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by vollowx** [comment]
1. Make sure that you're using the same flavor of your terminal
2. Try turing `fzf_colors = true` in the fzf configuration off
3. Try [catppuccin/fzf](https://github.com/catppuccin/fzf) , the official port for fzf
