### ISSUE TITLE
Blue channel offset by 1 with kitty without transparency

### ISSUE THREAD

**Issue by SirLarion** [catppuccin/nvim#767]
### Description

Hello!

I was very confused for some time when everything in my customized theme looked slightly bluer than expected. After some digging I ran into this workaround for a kitty bug in `catppuccin/palettes/init.lua`

```lua
if O.kitty then -- https://github.com/kovidgoyal/kitty/issues/2917
  for accent, hex in pairs(ans) do
    local red_green_string = hex:sub(1, 5)
    local blue_value = tonumber(hex:sub(6, 7), 16)

    -- Slightly increase or decrease brightness of the blue channel
    blue_value = blue_value == 255 and blue_value - 1 or blue_value + 1
    ans[accent] = string.format("%s%.2x", red_green_string, blue_value)
  end
end
```

As I understand it, this workaround is meant only for when the background has transparency. If this is the case, then I think the check should be for `if O.kitty and O.transparent_background then ...`

I can work around it just by having #FAFAF9 instead of #FAFAFA but a little annoying regardless :sweat_smile: 

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```

### Terminal and multiplexer

kitty 0.36.1

### Catppuccin version / branch / rev

catppuccin v1.9.0

### Steps to reproduce

0. Have a custom catppuccin theme. (i.e. use the `color_overrides` options), the issue is apparent
1. `nvim` in kitty
2. The problem is apparent in the colors

### Expected behavior

Overriden colors should be as defined, not slightly offset

### Actual behavior

All colors, including overriden ones, are slightly offset.

### Repro

```Lua
-- Any init.lua setup with catppuccin
```

**Comment by vollowx** [comment]
Please simply set `kitty = false` if you're not using a transparent setup, as the `kitty` option only affects here.

**Comment by sgoudham** [comment]
Hey 👋,

We've had to revert the PR that fixes this as it breaks the existing workaround for Kitty terminals. Unfortunately, the blue offset that you're encountering is currently expected behaviour and not a bug. I'll raise a PR in the future documenting this more clearly outside of the source code.
