### ISSUE TITLE
Brighter color for brackets

### ISSUE THREAD

**Issue by premell** [catppuccin/nvim#77]
I personally think the brackets should have a bit of a stronger color to pop more. Right now they are the same color as comments, which makes them harder to read IMO. Here is an example of a side by side with onedarker which have a bit brighter brackets
![image](https://user-images.githubusercontent.com/65544203/147680120-ac221a24-45f6-4287-96ee-b564393c82f3.png)
![image](https://user-images.githubusercontent.com/65544203/147680146-de561889-a0de-4107-ab3a-72f8d5c11058.png)

I feel like the gray color almost makes the brackets look like gaps, for example on line 21.

PS: I was unsure if I would even make this issue, since its a preference thing. But I thought it would be good to let you look at it and decide from the side by side pictures

**Comment by premell** [comment]
I think the same thing applies to the other symbols aswell, like the "." ":" "{" etc, but they are not as noticeable because they are rarely more than one in a row.

Also I much prefer catppuccin to onedarker, so even when I looked at the comparison pictures I posted, I thought the gray brackets looked good. But try to be critical and think if the brackets look good because they simply look good, or if its because catppuccin is a great colorscheme.

**Comment by TheExistingOne** [comment]
Could this maybe be another plugin you've got loaded? I tried a few different languages including lua which it looks like you're writing there and they all look like this with stock catppucci
![Screenshot_2022-01-01_19-59-55](https://user-images.githubusercontent.com/49994945/147865887-0d4687fa-7d2f-44cd-b73d-1ade54fa14cb.png)
n

**Comment by premell** [comment]
@TheExistingOne thanks for your input. I have done some testing and it seems like treesitter makes the brackets gray. These are two side by side comparisons with and without treesitter: 
![image](https://user-images.githubusercontent.com/65544203/147874833-f21707bd-89fa-4de0-9fc2-5f35635922c6.png)
![image](https://user-images.githubusercontent.com/65544203/147874866-0fdb0be2-e89d-4ce1-bcaa-9d235f71a733.png)

So overall the color scheme looks way worse without treesitter, however the brackets are then filled it. (which is personal preference if its good or not)

**Comment by Pocco81** [comment]
This should've been fixed by the latest commits :)
