### ISSUE TITLE
automatic dark/light theme switching doesn't work

### ISSUE THREAD

**Issue by Dieterbe** [catppuccin/nvim#773]
### Description

when switching kitty theme, the automatic switching between dark/light theme (and background) in neovim doesn't work

### Neovim version

```markdown
nvim --version
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```

### Terminal and multiplexer

kitty 0.36.4 created by Kovid Goyal

### Catppuccin version / branch / rev

63685e1562ef53873c9764b483d7ac5c7a608922 (latest main at this time)

### Steps to reproduce

1. in ~/.config/kitty.conf, put "include ./theme.conf"
2. make a symlink from theme.conf to any desired theme (e.g. ayu.conf from github.com:dexpota/kitty-themes)
3. start 2 kitty terminals: a reference (A), and another(B) in which we launch neovim
4. replace the theme.conf symlink to point to another theme which has different color definitions (e.g. ayu-light.conf)
5. run `killall -USR1 kitty`

### Expected behavior

terminal A changes color immediately
terminal B with neovim, changes color immediately, or at least after doing hjkl in normal mode

### Actual behavior

terminal A color changes immediately (this proves that kitty terminals update immediately)
terminal B with neovim, never changes colorscheme, no matter how many times i navigate around in neovim. however, exiting and restarting neovim makes it use the proper theme (a light theme, when i switched kitty from ayu.conf to ayu-light.conf)

--
note, i can repro it with your recommended repro config, although it shows this error:
```
E5113: Error while calling lua chunk: /tmp/repro.lua:2: attempt to concatenate global 'root' (a nil value)
```
I can also repro it with my own minimal config which is a barebones lazyvim + catppuccin. see the config below.
I believe the `require("catpuuccin").setup()` matches the defaults (i copy pasted it from the readme), so i've also tried removing it, but i get the same result.
```
$ find .config/nvim
.config/nvim
.config/nvim/lazy-lock.json
.config/nvim/init.lua
.config/nvim/lua
.config/nvim/lua/plugins
.config/nvim/lua/plugins/example.lua
.config/nvim/lua/config
.config/nvim/lua/config/lazy.lua

$ cat .config/nvim/lua/plugins/example.lua
return {
{ "catppuccin/nvim", name = "catppuccin", priority = 1000 }
}

$ cat .config/nvim/init.lua
require("config.lazy")

require("catppuccin").setup({
    flavour = "auto", -- latte, frappe, macchiato, mocha
    background = { -- :h background
        light = "latte",
        dark = "mocha",
    },
    transparent_background = false, -- disables setting the background color.
    show_end_of_buffer = false, -- shows the '~' characters after the end of buffers
    term_colors = false, -- sets terminal colors (e.g. `g:terminal_color_0`)
    dim_inactive = {
        enabled = false, -- dims the background color of inactive window
        shade = "dark",
        percentage = 0.15, -- percentage of the shade to apply to the inactive window
    },
    no_italic = false, -- Force no italic
    no_bold = false, -- Force no bold
    no_underline = false, -- Force no underline
    styles = { -- Handles the styles of general hi groups (see `:h highlight-args`):
        comments = { "italic" }, -- Change the style of comments
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
        -- miscs = {}, -- Uncomment to turn off hard-coded styles
    },
    color_overrides = {},
    custom_highlights = {},
    default_integrations = true,
    integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        notify = false,
        mini = {
            enabled = true,
            indentscope_color = "",
        },
        -- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
    },
})

-- setup must be called before loading
vim.cmd.colorscheme "catppuccin"

$ cat .config/nvim/lua/config/lazy.lua                                                                                                                                   
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
  spec = {
    -- import your plugins
    { import = "plugins" },
  },
  -- Configure any other settings here. See the documentation for more details.
  -- colorscheme that will be used when installing plugins.
  install = { colorscheme = { "habamax" } },
  -- automatically check for plugin updates
  checker = { enabled = true },
})
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by ilias777** [comment]
For me it works. 
First I have in the `init.lua` file the lazy.nvim bootstrap.
Then in the folder `lua/plugins/` I have a `init.lua` file with this code snippet:
```lua
return {
  {
      'catppuccin/nvim',
      lazy = false,
      name = 'catppuccin',
      priority = 1000,
      config = function()
        require('plugins.theme.catppuccin')
        vim.cmd('colorscheme catppuccin')
      end,
  },
}
```

From there I load the catppuccin configuration under `lua/plugins/theme/catppuccin.lua` and lastly I set the colorsheme to catppuccin with `vim.cmd('colorscheme catppuccin')`

Important to note here is, to not set the background option to `dark` or `light` in your configuration.

You can see my config [here](https://github.com/ilias777/nvim) for reference. Maybe it helps.

**Comment by Dieterbe** [comment]
> You can see my config here for reference. Maybe it helps

i tried your config and indeed, it responds instantly, without even having to press any keys.

i'll dig a bit more.

**Comment by Dieterbe** [comment]
@ilias777 : 

> From there I load the catppuccin configuration under lua/plugins/theme/catppuccin.lua

where does this file come from? i thought returning  '{catppuccin/nvim'} installs the needed files for catppuccin via lazy (this seems to be the case when i check :LazyHealth ), however i don't have such a file

**Comment by ilias777** [comment]
> i thought returning '{catppuccin/nvim'} installs the needed files for catppuccin via lazy

Yes, this is right. Lazy installs the needed files for catppuccin by returning `{catppuccin/nvim}`.

But you have to call also the `require("catppuccin").setup({})` inside the `config function`. 

You can have this:
```lua
return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      -- your configutarion
    })
  end
}
```

or this:
```lua
return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("plugins.theme.catppuccin")
  end
}
```

and in this file, under `lua/plugins/theme/catppuccin.lua`, you have inside the setup function:
```lua
require("catppuccin").setup({
    -- your configutarion
})
```

Only if the setup function is called, the catppuccin theme is applied.

Back to your problem. Look in your configuration for this option: `vim.opt.background = "dark"` or `vim.opt.background = "light"` and remove it.

Neovim can read if your system is on dark or light mode and add light or dark to the background option. Catppuccin read the background option, that is set by neovim, and apply the dark or the light theme.

**Comment by Dieterbe** [comment]
> Back to your problem. Look in your configuration for this option: vim.opt.background = "dark" or vim.opt.background = "light" and remove it

i don't have such an option set. my config is only what i shared before.

i tried to follow your code suggestions but that results in `/home/dieter/.config/nvim/lua/catppuccin.lua:1: loop or previous error loading module 'catppuccin'`

anyway, i think the issue is probably something on my side and not with catppuccin itself. and i should probably learn more about how to make it all work properly under the hood. so i think we can close this for now.

**Comment by sgoudham** [comment]
Thanks for engaging and confirming that it's not an issue with the plugin @ilias777.
Closing now.

**Comment by Dieterbe** [comment]
i don't think i did, but i don't remember for sure. i ended up switching from nvim to codeium windsurf..
