### ISSUE TITLE
Cursorline barely visible in transparent mode

### ISSUE THREAD

**Issue by raknos13** [catppuccin/nvim#779]
I tried the following fix in https://github.com/catppuccin/nvim/discussions/448 by adding `custom_highlights` rule, but it didn't make any noticeable difference.
```lua
require("catppuccin").setup({
  transparent_background = true,
  custom_highlights = function(colors)
    local u = require("catppuccin.utils.colors")
    return {
      CursorLine = {
        bg = u.vary_color(
          { latte = u.lighten(colors.mantle, 0.70, colors.base) },
          u.darken(colors.surface0, 0.64, colors.base)
        ),
      },
    }
  end,
})
```
_Originally posted by @mrtnvgr in https://github.com/catppuccin/nvim/discussions/448#discussioncomment-5560230_

How can I make the cursorline more distinguishable?
I want a color that has nice contrast with the background so that it quickly catches the eye, so that whenever I come back to the editor, I can immediately tell which line the cursor is on. (Like maybe more 'whiteish' or lavendar color in Latte, and something a bit less dark in Macchiato)
![image](https://github.com/user-attachments/assets/e0f0c105-917f-430c-8a15-549849f28ff5)
![image](https://github.com/user-attachments/assets/25eafbc7-545d-4035-9f88-591fb3fed9da)

**Comment by vollowx** [comment]
Try tweaking the 2nd parameter of `lighten` and `darken`? I'm not so familiar with these base functions TBH but it should work.

**Comment by vollowx** [comment]
#778
