### ISSUE TITLE
Allow loading via lazy.nvim `opts` table and `config` function 

### ISSUE THREAD

**Issue by onexbash** [catppuccin/nvim#796]
it is recommended to use the opts {} table over the setup function when using lazy.nvim as plugin manager. 
The opts table automatically calls the setup function and merges the options into it. 
This is not possible with catppuccin-nvim. 

**For example:**
_This works_
```
return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = false,
	priority = 1000,
	config = function()
		require("catppuccin").setup({
			flavour = "mocha",
			transparent_background = "true",
		})
		vim.cmd.colorscheme("catppuccin")
	end,
}
```

_This does not work_
```
return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = false,
	priority = 1000,
	opts = {
		flavour = "mocha",
		transparent_background = "true",
	},
	config = function()
		vim.cmd.colorscheme("catppuccin")
	end,
}

```

**For reference:**
https://lazy.folke.io/spec#spec-setup
![CleanShot 2024-10-30 at 18 25 50](https://github.com/user-attachments/assets/3464a9cd-6155-42b4-bfa6-2fb9da67f4f9)

**Comment by sgoudham** [comment]
Hey 👋,

Thanks for raising the issue. I've not actually tried to put the `vim.cmd.colorscheme()` command inside of the `config` function so I'm not running into this issue. Fwiw, this is a minimal version of my setup:

`lazy.lua`
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup("plugins")

vim.cmd.colorscheme("catppuccin")
```

`plugins/catppuccin.lua`
```lua
return {
  {
    "catppuccin/nvim",
    lazy = false,
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      show_end_of_buffer = true,
    },
  },
}
```

I suppose it might be the structure of our plugin that makes it hard for lazy.nvim to determine how to pass the opts into the setup function. 

I don't have time to dive into our codebase and investigate why so I'd appreciate if someone else could take a look into our setup function and how lazy expects the structure to be. Potentially look at how other colourschemes are doing it if they don't suffer from this issue.

**Comment by vollowx** [comment]
```lua
return {
  "catppuccin/nvim",
  name = "catppuccin",
  lazy = false,
  priority = 1000,
  opts = {
    flavour = "mocha",
    transparent_background = "true",
  },
  config = function(opts)
    require("catppuccin").setup(opts)
    vim.cmd.colorscheme("catppuccin")
  end,
}
```

If you insist on loading plugins such way, this should work.

However, for plugins _that might be_ with massive configuration, I'd recommend making their configurations separated.

```lua
-- where you write plugin specs

return {
  "catppuccin/nvim",
  name = "catppuccin",
  config = function() require('configs.catppuccin') end,
}
```

```lua
-- %/lua/configs/catppuccin.lua

require("catppuccin").setup({
  flavour = "mocha",
  transparent_background = "true",
})
```

```lua
-- %/init.lua

-- ...

-- at the end of file
vim.cmd.colorscheme("catppuccin") -- this calls the setup
```

**Comment by onexbash** [comment]
hey guys, thanks a lot but passing the opts table to the config function doesn't solve the bad practice of using the config function for lazy.nvim plugins.
I also thought about doing it this way and also wonder why lazy considers it a bad practice at all, but I'm in my nvim config refactoring process and wanna make sure I have the best possible result.

**Comment by vollowx** [comment]
Calling the setup in the `config` with the `opts` passed without nothing else in config` is a bad practice b/c it's unnecessary, but in this case you do two things in `config`.

If you have further questions you can raise issues in `folke/lazy.nvim`, but here we are not going to apply the colorscheme in the `setup` in any case.
