### ISSUE TITLE
blink-cmp integration with frappe has low contrast on completion window

### ISSUE THREAD

**Issue by allengueco** [catppuccin/nvim#797]
### Description

Currently, the blink-cmp integration's lsp completion window and documentation has low contrast when using frappe. Kind of unreadable without borders.

Frappe:
![image](https://github.com/user-attachments/assets/5242f04c-a62e-4366-8990-8df4f0744c53)

Comparing to Mocha:
![image](https://github.com/user-attachments/assets/b9d3187d-2dcf-4818-a22a-1cfc0b737d52)

Is this intended?

### Neovim version

```markdown
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

### Terminal and multiplexer

wezterm

### Catppuccin version / branch / rev

main

### Steps to reproduce

1. enable blink_cmp integration
2. use lsp completion/documentation window

### Expected behavior

I'd expect some contrast with the completion windows

### Actual behavior

No contrast

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "catppuccin/nvim",
    config = function()
      require('catppuccin').setup({
        flavour = "frappe",
        integrations = { blink_cmp = true }
      })
     end,
  },
  {
    "saghen/blink.cmp",
    lazy = false,
    version = "v0.*",
    config = function()
      require('blink.cmp').setup({
        keymap = "super-tab",
      })
    end
  }
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
```

**Comment by vollowx** [comment]
Seems that you didn't enable the `blink-cmp` integration at all

**Comment by allengueco** [comment]
I can't seem to get a working repro.lua to reproduce the issue, but I've updated it above to match the relevant bits in my config.

**Comment by vollowx** [comment]
Just found that the original PR is designed for a bordered UI, so the background is meant to be `base`.

I'd like to add an extra option `style = plain/bordered`, what do you think of this?

**Comment by allengueco** [comment]
Yeah that would work!
