### ISSUE TITLE
Light theme version?

### ISSUE THREAD

**Issue by rayturnpike** [catppuccin/nvim#80]
Do you plan to make a light version of Catppuccin?

Yours is my favorite theme, and I use it a home, but my office is too bright for a dark theme. 

If not, do you have any suggestions for a light theme with similar aesthetics? I haven’t found one nearly as pretty as Catppuccin!

**Comment by Pocco81** [comment]
Wrong place. Check out: https://github.com/catppuccin/catppuccin/issues/40
