### ISSUE TITLE
How to get correct cursor color in Neovide?

### ISSUE THREAD

**Issue by Oneechan69** [catppuccin/nvim#810]
### Description

I don't think the cursor color is correct In Neovide.

How it looks in Kitty:
<img width="780" alt="CleanShot 2024-12-12 at 07 50 08@2x" src="https://github.com/user-attachments/assets/1c281747-5057-456e-8cb3-46a0c994b881" />

How it looks in Neovide:
<img width="998" alt="CleanShot 2024-12-12 at 07 50 30@2x" src="https://github.com/user-attachments/assets/c28a5c2f-9dda-4b3a-a3a3-ec5741e7946a" />

### Neovim version

```markdown
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678
```

### Terminal and multiplexer

Neovide NVIM v0.10.2 Build type: Release LuaJIT 2.1.1732813678. No multiuplexer.

### Catppuccin version / branch / rev

catppuccin 1.9.0

### Steps to reproduce

1. Use the minimal init.lua
2. Open Nvim in Neovide

### Expected behavior

Peach-colored cursor?

### Actual behavior

Black cursor

### Repro

```Lua
-- LazyNvim Setup
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
vim.opt.clipboard = "unnamedplus"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
  { 
		"catppuccin/nvim", 
		name = "catppuccin", 
		priority = 1000,
	},
})

require("catppuccin").setup({
    term_colors = true,
})

vim.cmd.colorscheme "catppuccin-latte"
```

**Comment by azdanov** [comment]
Try enabling `term_colors` 
https://github.com/catppuccin/nvim?tab=readme-ov-file#configuration

**Comment by vollowx** [comment]
The cursor in kitty is the one rendered and configured by kitty, which kitty overrides anything related to the terminal cursor. Please check the neovide docs to see if they support customizing cursor color and make issues there.
