### ISSUE TITLE
[Question/Bug] packer.nvim do not run 'config' for this plugin?

### ISSUE THREAD

**Issue by alex-popov-tech** [catppuccin/nvim#84]
It appears only with 'catppuccin' plugin, so im writing here...

Description:
Im using packer.nvim to install 'catppuccin', with a small adjustment:
```
...
{"catppuccin/nvim", as = "catppuccin", config = require("plugins.catppuccin")}
...
```
and contents of `plugins.catppucin` is following:
```
return function()
  require'catppuccin'.setup({ transparent_background = true, term_colors = true, })
end
```
and then after some time i call `colorscheme catppuccin` to enable colors.

Problem:
Is seems that `config` function is not called on startup, as colorscheme still has default settings, and that behavior is ONLY applicable for thin plugin :(

Notes:
- i tried re-installing plugin multiple times
- ensured plugin is installed in correct location
- tried manually `setup` func and then re-load `colorscheme catppucin` to see if `setup` func is working ( it is )
- tried putting `setup` just before `colorscheme catppucin` instead of `config` ( it worked )

**Comment by alex-popov-tech** [comment]
another proposition is that `setup` function is not 'prepared' to be called, as if i change `plugins.catppuccin' to 
```
return function()
  require'catppuccin'.setup({ transparent_background = true, term_colors = true, })
  cmd('echo "hello from config" | sleep 2')
end
```
i can see message and sleep on start ( which means `config` was actually run by `packer`, but `setup` call was somehow...broken? )

**Comment by alex-popov-tech** [comment]
i figured it out. in the end it was that `setup` from `packer`'s `config` was called before `load` for some reason...
in the end i did something like
```
return function()
  require'catppuccin'.setup({ transparent_background = true, term_colors = true, })
  cmd("colorscheme catppuccin")
end
```

...and thank you guys for plugin btw!

**Comment by Pocco81** [comment]
Glad you liked the colorscheme! <3
