### ISSUE TITLE
What is the correct color for the background?

### ISSUE THREAD

**Issue by hahuang65** [catppuccin/nvim#85]
I'm trying to get my terminal  and nvim in sync, but the backgrounds are different.

In the alacritty port, the background is `#1E1E28`
In the kitty port, the background is `#1E1E29`

In the official catppuccin/catppuccin repo, it seems like `#1E1E28` is correct, since there's no mention of `#1E1E29`.

But the weirdest thing is, in nvim, the background is `#1E1D2D`. Is this correct?
I've attached a picture here showing my configs, and you can pretty clearly see the difference in the background colors. The top window is in nvim, the bottom is just my terminal.

![Screen Shot 2022-01-06 at 3 24 24 PM](https://user-images.githubusercontent.com/280972/148466711-77d6f235-567a-422a-8d2a-7301d5e980c0.png)

**Comment by hahuang65** [comment]
Digging in a little deeper, nvim plugin code seems to be at fault:
https://github.com/catppuccin/nvim/blob/bfa735fc85ae195fb6dc37036484937ec9c1ebdd/lua/catppuccin/core/color_palette.lua#L21

While `black2` defined on the main [repository](https://github.com/catppuccin/catppuccin) is `#1E1E28`

**Comment by jorgebef** [comment]
So there has been some development in the colors, particularly to improve the luminance and contrast, which has lead to the background to become `black2=#1E1D2D`

I believe the changes will be pushed to the main theme repo rather soon and everywhere else too.

**Comment by Pocco81** [comment]
I just pushed. You have the new [gorgeous] background :star:
