### ISSUE TITLE
Commit 864416 changed the background color 

### ISSUE THREAD

**Issue by rayturnpike** [catppuccin/nvim#88]
With commit 8644116 the main background color  changed from blackish to blueish. This is a far bigger change than the tweaks to the other colors, but it wasn’t documented. Was this change intended? It also breaks the various terminal Catppuccin themes (eg Kitty).

**Comment by jorgebef** [comment]
I can confirm that the intended new color for background has changed to `#1E1D2F`

It's being updated as we speak and the kitty port as well as all related documentation is being worked on to reflect the changes as we speak.

We're discussing it in the Discord server, you could join in on the action!

**Comment by Pocco81** [comment]
In addition to what @jorgebef said, all changes are documented in the release notes: https://github.com/catppuccin/catppuccin/releases/tag/v0.1.3

Here is the reason why the background changed (taken from the release notes):

> The transition between every color in the black-gray palatte is smoother: this is because the darkest ones of them now have a slight tint of a really deep dark purple which makes colors pop more, so to speak. Purple was chosen since most of the colors that were going to be on top of it (like yellow, green, orange, and red) were opposed to it in the color wheel.

**Comment by wjllm** [comment]
Thanks for letting me know. I like the change, I just was surprised I didn't see it in the commit notes (my bad, I hadn't checked the release notes, only what I saw from running `PackerUpdate`).
