### ISSUE TITLE
finer control over treesitter integration (italicization, etc)

### ISSUE THREAD

**Issue by ledesmablt** [catppuccin/nvim#93]
First off, this colorscheme is really awesome! =) I'd just like to have the option to configure how the treesitter integration behaves. not sure if this is already doable since it's not documented in the readme. Examples below are written in typescript.

setup with `integrations.treesitter = true`
![image](https://user-images.githubusercontent.com/22242264/149649983-f17ff926-7258-4a26-bbc8-b1a83fca0fcf.png)

setup with `integrations.treesitter = false`
![image](https://user-images.githubusercontent.com/22242264/149650006-1cbaadd4-3fd4-409f-b572-146e6da96626.png)

I much prefer the syntax highlighting with treesitter enabled, but I'm not really a fan of the italicization for object properties & function calls. It can be a bit jarring for me if an object has a lot of props, especially deeply nested ones.

I understand that the italicization is hardcoded [here](https://github.com/catppuccin/nvim/blob/e0f5d3bb72ab79de11de5fdf61a412c49c5bc240/lua/catppuccin/core/integrations/treesitter.lua#L100) but am not sure how this can be configured without manually overriding file in the cloned repo. Having a way to control this would be really good imo, especially considering how popular treesitter is. Thanks!

**Comment by Pocco81** [comment]
Every highlight group can be customized: https://github.com/catppuccin/nvim#overwriting-highlight-groups

Let me know if you need help using the API :)

**Comment by ledesmablt** [comment]
Thank you for pointing this out! Some help would be great :)

For example, if i want to remove italicization for this highlight group but keep the color the same:
![image](https://user-images.githubusercontent.com/22242264/149665607-674b354a-f0ed-4303-a2d0-091f31fe1afa.png)

How should i go about this with the API you provided?

**Comment by ledesmablt** [comment]
AH nevermind, after some messing around i got it to work. Big thanks!! Love this colorscheme! ;)
