### ISSUE TITLE
Italics settings not respected if using treesitter highlighting

### ISSUE THREAD

**Issue by jacksonludwig** [catppuccin/nvim#95]
I believe when treesitter highlighting is enabled, the `styles` keys are not respected.

For example:
```lua

require("catppuccin").setup({
  styles = {
    comments = "NONE",
    functions = "NONE",
    keywords = "NONE",
    strings = "NONE",
    variables = "NONE",
  },
  integrations = {
    treesitter = true,
  },
})

```

will still result in italics.

Is this expected? Thanks.

**Comment by LuisxSullivaN** [comment]
yeah i noticed the same, it seems that some styles are set and not don't use settings

**Comment by RaulCote** [comment]
Yes, the same. I would like to avoid all italics but I can't. Lovely theme, but I don't like italics on my code, I don't think is a good choice to default almost everything to italics.

**Comment by teenjuna** [comment]
Okay, I think I understand: this happens when your `colorscheme catppuccin` is executed before the `require('catppuccin').setup { ... }`. Try to change the theme to something else and then back.

As for the fix, should the plugin just reload the theme after `.setup { ... }` is called?

**Comment by RaulCote** [comment]
No. The issue is on the files inside the integrations folder within the plugin the word italic is a string not a variable. As an example the treesitter.lua file;

`	return {
		-- These groups are for the neovim tree-sitter highlights.
		-- As of writing, tree-sitter support is a WIP, group names may change.
		-- By default, most of these groups link to an appropriate Vim group,
		-- TSError -> Error for example, so you do not have to define these unless
		-- you explicitly want to support Treesitter's improved syntax awareness.
		TSField = { fg = cp.rosewater }, -- For fields.
		TSProperty = { fg = cp.yellow, style = "italic" }, -- Same as TSField.
		TSInclude = { fg = cp.teal, style = "italic" }, -- For includes: #include in C, use or extern crate in Rust, or require in Lua.
		TSOperator = { fg = operators, style = "bold" }, -- For any operator: +, but also -> and * in cp.
		TSKeywordOperator = { fg = operators, style = "bold" }, -- For new keyword operator
		TSPunctSpecial = { fg = cp.maroon, style = "bold" }, -- For special punctutation that does not fall in the catagories before.

		TSFloat = { fg = math_logic, style = "bold,italic" }, -- For floats.
		TSNumber = { fg = math_logic, style = "bold,italic" }, -- For all numbers
		TSBoolean = { fg = math_logic, style = "bold,italic" }, -- For booleans.

		TSConstructor = { fg = cp.lavender }, -- For constructor calls and definitions: = { } in Lua, and Java constructors.
		TSConstant = { fg = cp.peach }, -- For constants
		TSConditional = { fg = cl, style = "bold" }, -- For keywords related to conditionnals.
		TSRepeat = { fg = cl, style = "bold" }, -- For keywords related to loops.
		TSException = { fg = cp.peach, style = cnf.styles.keywords }, -- For exception related keywords.
`

There should exist a config variable called italics_enabled that if the value is false it turn them off everywhere with just one variable.

A solution for the time being is to override on your config all the treesitter variables. I have this on my config, and I still need to find some stuff that it's using italics. But it fixes almost everything (you don't need to call style = "NONE" as it's the default but I added it for clearness to remember more easier that I want to override the style). 

`
local cp = require'catppuccin.api.colors'.get_colors()
require("catppuccin").remap({ 
  	ErrorMsg = { fg = cp.red, style = "bold" }, 
		TSProperty = { fg = cp.yellow, style = "NONE" },
		TSInclude = { fg = cp.teal, style = "NONE" },
		TSOperator = { fg = cp.sky, style = "bold" },
		TSKeywordOperator = { fg = cp.sky, style = "bold" },
		TSPunctSpecial = { fg = cp.maroon, style = "bold" },
		TSFloat = { fg = cp.peach, style = "bold" },
		TSNumber = { fg = cp.peach, style = "bold" },
		TSBoolean = { fg = cp.peach, style = "bold" },
		TSConditional = { fg = cp.mauve, style = "bold" },
		TSRepeat = { fg = cp.mauve, style = "bold" },
		TSException = { fg = cp.peach, style = "NONE" },
		TSConstBuiltin = { fg = cp.lavender, style = "NONE" },
		TSFuncBuiltin = { fg = cp.peach, style = "NONE" },
		TSTypeBuiltin = { fg = cp.yellow, style = "NONE" },
		TSVariableBuiltin = { fg = cp.teal, style = "NONE" },
		TSFunction = { fg = cp.blue, style = "NONE" },
		TSParameter = { fg = cp.rosewater, style = "NONE" }, 
		TSKeywordFunction = { fg = cp.maroon, style = "NONE" },
		TSKeyword = { fg = cp.red, style = "NONE" },
		TSMethod = { fg = cp.blue, style = "NONE" },
		TSNamespace = { fg = cp.rosewater, style = "NONE" },
		TSStringRegex = { fg = cp.peach, style = "NONE" },
		TSVariable = { fg = cp.white, style = "NONE" },
		TSTagAttribute = { fg = cp.mauve, style = "NONE" },
		TSURI = { fg = cp.rosewater, style = "underline" },
		TSLiteral = { fg = cp.teal, style = "NONE" },
		TSEmphasis = { fg = cp.maroon, style = "NONE" },
		TSStringEscape = { fg = cp.pink, style = "NONE" },
		bashTSFuncBuiltin = { fg = cp.red, style = "NONE" },
		bashTSParameter = { fg = cp.yellow, style = "NONE" },
		typescriptTSProperty = { fg = cp.lavender, style = "NONE" },
		cssTSProperty = { fg = cp.yellow, style = "NONE" },
})
`

**Comment by teenjuna** [comment]
@Pocco81 any idea on how it can be better implemented?

**Comment by sgoudham** [comment]
Has there been any further progress on this issue?

**Comment by aveaves** [comment]
Issue is still there. Cannot toggle all off the italics using a single setting.

**Comment by dylancromer** [comment]
This is still unresolved

**Comment by jeffock** [comment]
I'm not sure why this is closed, no actual solution has been implemented...

**Comment by nullchilly** [comment]
You can toggle all italics off using a this setting:

```lua
require("catppuccin").setup({
    no_italic = true, -- Force no italic
}
```

**Comment by GotaLoveFiraCode** [comment]
It still seems not to be possible to control italics properly when tree-sitter integration is enabled. One can either turn italics off completely, or live the predefined settings :/

Progress would be appreciated.
