### ISSUE TITLE
Transparent Background for nvim-tree.lua

### ISSUE THREAD

**Issue by hackorum** [catppuccin/nvim#98]
Hi, thanks for this awesome colorscheme :)
I have been trying to find a way to make the nvim tree background transparent but I am not able to do it. Here is the screenshot:
![Screenshot 2022-01-23 at 9 11 16 AM](https://user-images.githubusercontent.com/70092545/150663834-385883e0-7740-4f7f-9a5b-fee7625b9aaa.png)
Could you please help me fix this?

**Comment by hackorum** [comment]
Here is my configuration:
```lua
local catppuccin = require("catppuccin")

catppuccin.setup({
  transparent_background = Vapour.settings.transparent_bg,
  term_colors = false,
  styles = {comments = "italic", functions = "italic", keywords = "italic", strings = "NONE", variables = "NONE"},
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {errors = "italic", hints = "italic", warnings = "italic", information = "italic"},
      underlines = {errors = "underline", hints = "underline", warnings = "underline", information = "underline"}
    },
    lsp_trouble = false,
    lsp_saga = false,
    gitgutter = false,
    gitsigns = true,
    telescope = true,
    nvimtree = {enabled = true, show_root = true},
    which_key = true,
    indent_blankline = {enabled = true, colored_indent_levels = true},
    dashboard = true,
    neogit = false,
    vim_sneak = false,
    fern = false,
    barbar = false,
    bufferline = true,
    markdown = false,
    lightspeed = false,
    ts_rainbow = true,
    hop = false
  }
})
vim.cmd('colorscheme catppuccin')
```

**Comment by Pocco81** [comment]
Here you go: https://github.com/catppuccin/nvim/commit/c63ad901576729c46f443630a1fb61e4a7e93a0f

**Comment by hackorum** [comment]
Thank you for your help :)

**Comment by fnacarellidev** [comment]
@hackorum how do you used it? I'm trying to put this `transparent_panel` option in my nvim-tree.lua setup file and it doesn't recognize :(

**Comment by nullchilly** [comment]
@fnacarellidev The option was removed because it doesn't make sense to have transparen_background and the transparent_panel at the same time

If you wish to change panel background use this instead

```
require("catppuccin").setup {
    flavour = "mocha",
    color_overrides = {
        mocha = {
            base = "#000000",
        },
    },
    integrations = {
        nvimtree = true,
    },
    highlight_overrides = {
        mocha = function(mocha)
            return {
                NvimTreeNormal = { bg = mocha.none },
            }
        end,
    },
}
```

**Comment by fnacarellidev** [comment]
@nullchilly I am not using this catppuccin setup and I'm also fairly new to configuring nvim with Lua, do you have any tips on how to implement this on my own setup? Thank you for you help anyways <3

**Comment by fnacarellidev** [comment]
@nullchilly oh my gosh, I just saw this is a issue on your repo and not on nvim tree, i'm so sorry..
