### ISSUE TITLE
Tmux changes background color

### ISSUE THREAD

**Issue by angarc** [catppuccin/nvim#99]
I copied over the catppuccin configurations for tmux, alacritty, and nvim. And everything looks great! However, for some reason whenever I use tmux and open a neovim session, the background is just a grey color and not the catppuccin purple-ish color and i have no idea why.

This is what it looks like with tmux
<img width="1680" alt="with_tmux" src="https://user-images.githubusercontent.com/18252779/150699639-37d170fe-e22d-44d7-b8d1-ae774dc8d253.png">

This is what it looks like without tmux
<img width="1680" alt="without_tmux" src="https://user-images.githubusercontent.com/18252779/150699646-42bef44c-2735-423f-a7be-baf4cf346b13.png">

Without vim running, tmux or not, alacritty has the purple background color so it's literally just vim that turns on this grey color. What's even weirder is that I have no idea where this grey color is coming from. It must have been set somewhere, i just don't know where. It's definitely not a system color, i think. I'm pretty sure I set this grey color, I just have no idea where. Everything else has the catppuccin config as far as I know.

Any help is appreciated.

**Comment by Pocco81** [comment]
This is a known issue with tmux and the $TERM variable on most terminal emulators: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6

What happens is that while on `tmux` colors tend to look off because `$TERM` mismatches with the one set on your terminal emulators' conf. That Gist should help :)

**Comment by angarc** [comment]
Yep this helped! thanks!
